### ISSUE TITLE
Kernel dies when writing to geopackage

### ISSUE THREAD

**Issue by rutgerhofste** [geopandas/geopandas#1066]
I love geopandas however I struggle with exporting the geodataframe to a geopackage. Often, to_file works with driver = "ESRI Shapefile" but given the shapefile limitations on column number and column name length, I prefer the geopackage standards.

I'm running geopandas on a large virtual instance on AWS with 32GB of RAM and plenty of storage. However when I export a geodataframe to geopackage, half of the time, my kernel dies (Jupyter Notebook).  Any idea why ?

My script is here:
https://github.com/wri/aqueduct30_data_download/blob/master/scripts/Y2019M07D12_RH_Aqueduct30_Data_Download_Monthly_V01.ipynb

The kernel dies without any error and there is no progress bar whatsoever.

**Comment by martinfleis** [comment]
That is really hard to debug. I quite often save geodataframes of 10x more rows and 5x more columns than you have to geopackage and I have never encountered an issue, even on a laptop with 8GB of RAM (it just takes a while). It might be caused by encoding conversion? Just guessing here, as I usually don't specify encoding so that is the only difference I can see. Have you tried letting Fiona decide on encoding?
