### ISSUE TITLE
geopandas package 

### ISSUE THREAD

**Issue by Morenagl** [geopandas/geopandas#1086]
hello, I have a problem with importing geopandas package, I have created my new environment in Conda and I the installation has done but in jupyter book doesn t work 
![geopandas](https://user-images.githubusercontent.com/53742915/62772552-22081700-baa0-11e9-9cd4-5188e74efd48.PNG)

and the error Command "python setup. py egg_info" failed with error code 1 in C so I have noticed that it's not in the same path I mean the same environment which is normal that it could not do it, so how can I change the environment in jupyter book just to import geopandas and the same time not lose all my packages in Conda because I have found already trouble with pysal package and I don't want they have the same issue 
 thank you

**Comment by martinfleis** [comment]
Hi, I would recommend following http://geopandas.org/install.html instructions. It mostly means installing GeoPandas using `conda` from `conda-forge` channel via `conda install -c conda-forge geopandas` rather than pip. Moreover, you should do it using command line, rather than Jupyter notebook. If you want to do it from the notebook, follow this advice: https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by martinfleis** [comment]
Just to add, it seems that `conda install -c conda-forge geopandas` from Jupyter notebook works as well if you restart the kernel afterwards (I learned that right now).

**Comment by Morenagl** [comment]
@martinfleis  thank you so much  , it works on jupyter right now   really thank you

**Comment by martinfleis** [comment]
No worries. Closing.
