### ISSUE TITLE
throw a warning of equal-area projection for .area 

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1095]
I've seen some questions about the issue of area size like this [one](https://stackoverflow.com/questions/57441790/calculating-correct-area-for-polygons-with-geopandas) from time to time. 

I wonder if GeoPandas should convert the projection automatically whiling calculating the area (based on some of the issues I opened before, folks doesn't seem to like this idea) If not, maybe just throw users a warning to remind them to change to the correct projection.

**Comment by martinfleis** [comment]
Using `pyproj` it is actually quite easy to check. For now we could do this:
```
from pyproj import CRS
crs = CRS.from_user_input(gdf.crs)
if not crs.is_projected:
    warning here
```

and if we will once use pyproj.CRS directly (#1003) we could do just:

```
if not gdf.crs.is_projected:
    warning here
```

If we want to do it, it would make sense to make a tiny helper function and call it whenever we do anything expecting projected CRS, not just `.area`. 

Automatic projection is tricky, because it might not be easy to figure out which one is the correct one to minimise error.

**Comment by snowman2** [comment]
You could also add an option to get the Geodesic area. You can get the `pyproj.Geod` for the CRS using [CRS.get_geod](https://pyproj4.github.io/pyproj/stable/api/crs.html#pyproj.crs.CRS.get_geod).

And in the next release of pyproj, you can get the Geodesic area with [Geod.geometry_area_perimeter](https://pyproj4.github.io/pyproj/latest/api/geod.html#pyproj.Geod.geometry_area_perimeter) for geographic projections.

**Comment by martinfleis** [comment]
It is a general issue with geopandas, that it is currently not able to calculate distances from unprojected CRS (#942) and it is something I would like to change in the future. So it might happen once we will switch to pyproj.CRS class, using pyproj's abilities.

**Comment by martinfleis** [comment]
Closed by https://github.com/geopandas/geopandas/pull/1378
