### ISSUE TITLE
GeoSeries.any() does not work with 0.6

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1100]
I know that this is a consequence of #1062, but not sure if the current behaviour is intended. Assuming it is not. From pandas:

> Returns False unless there at least one element within a series or along a Dataframe axis that is True or equivalent (e.g. non-zero or non-empty)

```python
import geopandas as gpd
from shapely.geometry import Polygon, LineString

gpd.__version__

'0.5.1'

polygon = Polygon([(0, 0), (1, 1), (1, 0)])
polygon2 = Polygon([(2, 2), (2, 1), (1, 2)])
gdf = gpd.GeoDataFrame(geometry=[polygon, polygon2])
line = LineString([(0.5, 0), (0.5, 2)])
possible_int = gdf.exterior.intersection(line)
possible_int

 0    (POINT (0.5 0), POINT (0.5 0.5))
 1                                  ()
 dtype: object

if possible_int.any():
    print('there is an intersection')

there is an intersection
```

```python
import geopandas as gpd
from shapely.geometry import Polygon, LineString
gpd.__version__

'0.6.0rc1'

polygon = Polygon([(0, 0), (1, 1), (1, 0)])
polygon2 = Polygon([(2, 2), (2, 1), (1, 2)])
gdf = gpd.GeoDataFrame(geometry=[polygon, polygon2])
line = LineString([(0.5, 0), (0.5, 2)])
possible_int = gdf.exterior.intersection(line)
possible_int

0    MULTIPOINT (0.5 0, 0.5 0.5)
1       GEOMETRYCOLLECTION EMPTY
dtype: geometry

if possible_int.any():
    print('there is an intersection')
```

    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-6-60300b40f0f7> in <module>()
    ----> 1 if possible_int.any():
          2     print('there is an intersection')

    ~/anaconda3/envs/momepy37/lib/python3.7/site-packages/pandas/core/generic.py in logical_func(self, axis, bool_only, skipna, level, **kwargs)
      11030                                       skipna=skipna)
      11031         return self._reduce(f, name, axis=axis, skipna=skipna,
    > 11032                             numeric_only=bool_only, filter_type='bool')
      11033 
      11034     return set_function_name(logical_func, name, cls)

    ~/anaconda3/envs/momepy37/lib/python3.7/site-packages/pandas/core/series.py in _reduce(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)
       3617         elif isinstance(delegate, ExtensionArray):
       3618             # dispatch to ExtensionArray interface
    -> 3619             return delegate._reduce(name, skipna=skipna, **kwds)
       3620         elif is_datetime64_dtype(delegate):
       3621             # use DatetimeIndex implementation to handle skipna correctly

    ~/anaconda3/envs/momepy37/lib/python3.7/site-packages/geopandas/array.py in _reduce(self, name, skipna, **kwargs)
        964         # because this was not yet defined in pandas 0.23
        965         raise TypeError("cannot perform {name} with type {dtype}".format(
    --> 966             name=name, dtype=self.dtype))
        967 
        968     def __array__(self, dtype=None):

    TypeError: cannot perform any with type geometry

The possible workaround is to use `if not possible_intersections.is_empty.all()`  instead which works with both 0.5 and 0.6. But maybe we should support any directly.

**Comment by jorisvandenbossche** [comment]
The error is actually not directly a consequence of #1062. The fact that `any` (and `all`) no longer work at all is due to the ExtensionArray changes (I didn't implemented 'any' and 'all' in `GeometryArray_reduce`, which is where pandas is looking for). 

But, it is correct that even if I implemented that, the behaviour of `any` might have changed due to the missing / empty changes (depending on whether we let it follow isna or isna + empty). I am not really sure what `any` is supposed to do.

**Comment by martinfleis** [comment]
> I am not really sure what any is supposed to do.

Interpreting what pandas says (above), I think it should check whether there is any non empty geometry within GeoSeries. The same as `not possible_intersections.is_empty.all()` does. In this case we do not care if there are NaNs or empty geometries as long as there is at least one non-empty geometry.
The same could be applied for `all`. It should check if all elements in GeoSeries are non-empty geometries.

**Comment by jorisvandenbossche** [comment]
The main problem is that this depended on what shapely returns for the "bool" values of an empty geometry, and this is inconsistent. I actually opened an issue about that a couple of days ago: https://github.com/Toblerity/Shapely/issues/754 

It also depends on the somewhat strange behaviour of `any` and `all` in pandas / numpy for object dtype data: https://github.com/pandas-dev/pandas/issues/27709

Exploring the behaviour in the latest release of GeoPandas:

```
import shapely.geometry 

poly = shapely.geometry.Polygon([(0,0), (0,1), (1,1)])
empty1 = shapely.geometry.Polygon()
empty2= shapely.geometry.Polygon().buffer(0)
empty3 = poly.intersection(shapely.affinity.translate(poly, 2, 2))
empty4 = shapely.geometry.GeometryCollection()   

for case, vals in [
    ("all polygons", [poly, poly]),
    ("poly + None", [poly, None]),
    ("poly + np.nan", [poly, np.nan]),
    ("poly + empty1", [poly, empty1]),
    ("poly + empty2", [poly, empty2]),
    ("poly + empty3", [poly, empty3]),
    ("poly + empty4", [poly, empty4]),
    # ("None + poly", [None, poly]),
    # ("np.nan + poly", [np.nan, poly]),
    ("all None", [None, None]),
    ("all np.nan", [np.nan, np.nan]),
    ("all empty1", [empty1, empty1]),
    ("all empty2", [empty2, empty2]),
    ("all empty3", [empty3, empty3]),
    ("all empty4", [empty4, empty4]),
    ("empty3 + None", [empty3, None]),
]:
    print('### ', case)
    s = geopandas.GeoSeries(vals) 
    print(s)
    res = s.all()
    print('s.all(): ', str(res).ljust(32), ', bool(s.all()): ', bool(res))
    res = s.any()
    print('s.any(): ', str(res).ljust(32), ', bool(s.any()): ', bool(res))
    print()              
```

Output with pandas 0.25 and geopandas 0.5.1:

<details>

```
###  all polygons
0    POLYGON ((0 0, 0 1, 1 1, 0 0))
1    POLYGON ((0 0, 0 1, 1 1, 0 0))
dtype: object
s.all():  POLYGON ((0 0, 0 1, 1 1, 0 0))   , bool(s.all()):  True
s.any():  POLYGON ((0 0, 0 1, 1 1, 0 0))   , bool(s.any()):  True

###  poly + None
0    POLYGON ((0 0, 0 1, 1 1, 0 0))
1                              None
dtype: object
s.all():  True                             , bool(s.all()):  True
s.any():  POLYGON ((0 0, 0 1, 1 1, 0 0))   , bool(s.any()):  True

###  poly + np.nan
0    POLYGON ((0 0, 0 1, 1 1, 0 0))
1                               NaN
dtype: object
s.all():  True                             , bool(s.all()):  True
s.any():  POLYGON ((0 0, 0 1, 1 1, 0 0))   , bool(s.any()):  True

###  poly + empty1
0    POLYGON ((0 0, 0 1, 1 1, 0 0))
1          GEOMETRYCOLLECTION EMPTY
dtype: object
s.all():  GEOMETRYCOLLECTION EMPTY         , bool(s.all()):  True
s.any():  POLYGON ((0 0, 0 1, 1 1, 0 0))   , bool(s.any()):  True

###  poly + empty2
0    POLYGON ((0 0, 0 1, 1 1, 0 0))
1                     POLYGON EMPTY
dtype: object
s.all():  POLYGON EMPTY                    , bool(s.all()):  True
s.any():  POLYGON ((0 0, 0 1, 1 1, 0 0))   , bool(s.any()):  True

###  poly + empty3
0    POLYGON ((0 0, 0 1, 1 1, 0 0))
1                                ()
dtype: object
s.all():  GEOMETRYCOLLECTION EMPTY         , bool(s.all()):  False
s.any():  POLYGON ((0 0, 0 1, 1 1, 0 0))   , bool(s.any()):  True

###  poly + empty4
0    POLYGON ((0 0, 0 1, 1 1, 0 0))
1                                ()
dtype: object
s.all():  GEOMETRYCOLLECTION EMPTY         , bool(s.all()):  False
s.any():  POLYGON ((0 0, 0 1, 1 1, 0 0))   , bool(s.any()):  True

###  all None
0    None
1    None
dtype: object
s.all():  True                             , bool(s.all()):  True
s.any():  False                            , bool(s.any()):  False

###  all np.nan
0   NaN
1   NaN
dtype: float64
s.all():  True                             , bool(s.all()):  True
s.any():  False                            , bool(s.any()):  False

###  all empty1
0    GEOMETRYCOLLECTION EMPTY
1    GEOMETRYCOLLECTION EMPTY
dtype: object
s.all():  GEOMETRYCOLLECTION EMPTY         , bool(s.all()):  True
s.any():  GEOMETRYCOLLECTION EMPTY         , bool(s.any()):  True

###  all empty2
0    POLYGON EMPTY
1    POLYGON EMPTY
dtype: object
s.all():  POLYGON EMPTY                    , bool(s.all()):  True
s.any():  POLYGON EMPTY                    , bool(s.any()):  True

###  all empty3
0    ()
1    ()
dtype: object
s.all():  GEOMETRYCOLLECTION EMPTY         , bool(s.all()):  False
s.any():  GEOMETRYCOLLECTION EMPTY         , bool(s.any()):  False

###  all empty4
0    ()
1    ()
dtype: object
s.all():  GEOMETRYCOLLECTION EMPTY         , bool(s.all()):  False
s.any():  GEOMETRYCOLLECTION EMPTY         , bool(s.any()):  False

###  empty3 + None
0      ()
1    None
dtype: object
s.all():  GEOMETRYCOLLECTION EMPTY         , bool(s.all()):  False
s.any():  False                            , bool(s.any()):  False
```

</details>

Some observations:

- `GeoSeries.any/all` almost never return True or False, but rather a scalar geometry object. But because you typically use this in `if s.any(): ...`, this is not necessarily a problem, but then the behaviour of that snippet depends on the `bool(..)` behaviour of that scalar shapely geometry object.
- `GeoSeries.any/all` doesn't consider missing values at the moment it seems (which seems in line with pandas)
- for empty geometries, it depends on how the empty geometry is created. If it was created from an operation such as `intersection` that resulted in an empty geometry, it did more or less what you expected (hence the use case as described above works). But if you would first have done a `buffer(0)` on the result, `any` would have given a different result.

**Comment by martinfleis** [comment]
Okay, that sounds complicated. Interesting fact is that `GEOMETRYCOLLECTION EMPTY` != `GEOMETRYCOLLECTION EMPTY` in empty1 and 3. It seems that behaviour in 0.5.1. is incorrect as well (returning geometry object instead of bool), but even if it returned bool, it would be inconsistent...

In this situation it might be in fact better not to support `any/all` at all, at least until shapely will make its behaviour consistent. And there is quite simple workaround for now. But we might want to specify this behaviour somewhere in #1098.

**Comment by jorisvandenbossche** [comment]
If we decide that it is better to not have `any`/`all` in the future given those inconsistencies, what we could certainly do is re-enable the functionality (just need to implement `GeometryArray._reduce` for any/all, and keep raising for the others) for now, but with potentially a deprecation warning.

But, we should have a good alternative, because I think the check of "is there at least one non-empty geometry" is something useful to do. And currently it is not that simple, since you also want to ignore missing values (`is_empty` gives False for missing). 
The `if not geoseries.is_empty.all()` is not correct in the case of missing values:

```
In [10]: s = geopandas.GeoSeries([empty1, None])                                                                                                                                              

In [11]: s.is_empty                                                                                                                                                                           
Out[11]: 
0     True
1    False
dtype: bool

In [13]: not s.is_empty.all()                                                                                                                                                                 
Out[13]: True
```

but still there is no non-empty geometry. 

I think you need something like this to be complete:

```
In [14]: not (s.is_empty | s.isna()).all()                                                                                                                                                    
Out[14]: False
```

which is quite verbose ..

**Comment by martinfleis** [comment]
I would like to have `any/all`. But its behaviour currently depends on inconsistent behaviour of shapely, which makes it unreliable.

In the ideal case we would have `any/all` checking for non-empty geometry, where NaN is seen as False. Some kind of construct you made above. While at the same time seeing all `GEOMETRYCOLLECTION EMPTY` and `POLYGON EMPTY` and other as equally empty geometries. Which might need PR on our side to handle empty/NaN for `any/all` and on shapely side to handle emptiness (unless we are able to check it directly, but that does not seem to be ideal solution).

In any case, we should at least re-enable it so we don't do a hard break here.
