### ISSUE TITLE
Proposal: Replace shapely.ops.transform with numpy based solution for reprojection

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#1136]
https://github.com/Toblerity/Shapely/pull/728

Thoughts on adding to geopandas and removing later if Shapely decides they to add it in?

In most cases this has ~2x speedup for transformations. Minor, but still something.

![image](https://user-images.githubusercontent.com/8699967/59140245-9a4b4280-8960-11e9-90fd-5047ae6cfad1.png)

**Comment by martinfleis** [comment]
That is nice! Let's wait a bit to see if Shapely will implement it. Then we can just use it. As we are close to 0.6 release, this would go to 0.7 anyway, so there is a bit of time. It would make the maintenance a bit easier if we would not have to think about possible removal in the future.

**Comment by jorisvandenbossche** [comment]
This is also something that should fit in the C / cython story. @caspervdw is actually implementing this right now in pygeos: https://github.com/caspervdw/pygeos/pull/44

**Comment by snowman2** [comment]
Nice - looks like he is in the c/cython code. Would be interesting to try it out.

**Comment by snowman2** [comment]
I did try it out, but I was surprised that the `pygeos` performance is similar to the proposed implementation in this issue and it does not support 3D yet.
Results here: https://gist.github.com/snowman2/c62d96079725a4d5a83f619a43704908

Currently wondering why? :thinking:

**Comment by jorisvandenbossche** [comment]
@snowman2 since you are also using cython, it might not be that surprising? (in principle doing the same in cython should give more or less the same performance, but didn't check in detail how your shapely PR is working though)

But thanks for testing! I ran your notebook as well, but I think the timing you are doing is dominated by the actual transformation, not by the time it takes to get/set the coordinates. Which could be misleading (although from my examples above the end conclusion is the same).

Eg on the single linestring (using the variables from your notebook), this is the timing you also did with the pyproj transformation

```
In [5]: %timeit pygeos.apply(glinestring, transformation) 
43.3 ms ± 2.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: %timeit array_transform(transformer.transform, linestring) 
42.9 ms ± 1.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

But the time is almost fully attributable to the pyproj transformation. Eg if we do a dummy no-op transformation, it seems this is only a small part of it:
```
In [7]: %timeit pygeos.apply(glinestring, lambda x: x) 
1.99 ms ± 90.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [8]: %timeit array_transform(lambda x, y: (x, y), linestring)  
2.87 ms ± 132 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

```


Testing it on the bigger array:

```
In [34]: arr_glinestring = numpy.array([glinestring for _ in range(1000)], dtype=numpy.object)

In [35]: %timeit pygeos.apply(arr_glinestring, lambda x: x)
2.83 s ± 19.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [36]: arr_linestring = numpy.array([linestring for _ in range(1000)], dtype=numpy.object)

In [37]: %timeit [array_transform(lambda x, y: (x, y), l) for l in arr_linestring]
2.89 s ± 182 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

it seems that both approaches basically take the same time to get and set coordinates. So I suppose that it is the actual geting / setting of the coordinates and creating of geometries (the GEOS operations) that dominates the time, not the time to iterate through all geometries / coordinate pairs (a pure python version would then maybe also not be much slower ..). 

You could then somewhat question the benefit of using C over cython, as the C code is quite a bit more complex. One thing is that the pygeos version is ufunc like, so works on any input shape out-of-the-box (although that could probably also be done in cython).

**Comment by snowman2** [comment]
> since you are also using cython, it might not be that surprising?

Actually, I just copied regular python code into the cython file as it was the only place `numpy` was required. So, the main benefit was using `numpy` I think. So, your conclusion towards the end of your response is probably correct.

> You could then somewhat question the benefit of using C over cython, as the C code is quite a bit more complex.

Definitely want the code to be maintainable, and the C code is not as easy to maintain as Python. But, the Python interface in `pygeos` is clean and has impressive speedups. Depending on when `pygeos` is ready to include into pandas, the method proposed in this issue could be an intermediate solution.

**Comment by snowman2** [comment]
Closing for preference for to the shapely/pygeos integration.
