### ISSUE TITLE
PROPOSAL: to_crs method to accept an optional transformer kwarg

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#1175]
Follow up from: https://github.com/geopandas/geopandas/issues/1142#issuecomment-537634477

Currently there are several options for transforming geometries. The the current method is to use pyproj + shapely as it is quite performant. However, it does not fit all use cases at the moment (e.g. antimeridian). As such, it might be useful to allow for alternate transformation methods in `to_crs()`.

Some defaults could potentially be added to `geopandas.transformers` or something.

This would be similar to what we do in geocube to allow users to rasterize their points:
https://corteva.github.io/geocube/html/examples/rasterize_point_data.html

The initial supported ones could be based on current dependencies:
1. pyproj + shapely transform(default)
2. fiona's `transform_geom` (based on https://github.com/geopandas/geopandas/issues/448#issuecomment-539778719)

It could look something like:

```python
def to_crs(..., transform_maker=None):
    ...
    if transform_maker is None:
        transform_maker = pyproj_transform_maker

    transformer = partial(transform_maker, src_crs=self.crs, dst_crs=crs)
    result = self.apply(transformer)
```

And the transform maker would use `functools.partial` to return a transformer based in the src_crs and dst_crs that would accept a geometry to transform.

Then, could have different transform makers in `geopandas.transformers` that could be extended based on various use cases.

Thoughts?

**Comment by jorisvandenbossche** [comment]
I am personally not fully we should add this to `to_crs`. It makes the function more complex, and it also kind of exposes implementation details. Eg if we would change to use pygeos.get/set_coordinates/apply functionality under the hood, we would no longer transform geom by geom, making this inconsistent with the `transform_maker` argument (which I think users will expect to be called per geometry, otherwise that would eg defeat the purpose of the geometry-aware projection in fiona).

But "transforming geometries given a transformation function" seems something generally useful that we should have (actually adding it to `to_crs` would enable that you can do other transformations than crs transformations with `to_crs` ..). Basically it would be exposing `shapely.ops.transform` in a better way than doing a `df.geometry.apply(lambda geom: transform(func, geom))` as what you need to do currently. 
And if we provide this generic transformation functionality, we can point there from the `to_crs` docs for custom CRS transformations (and have example's in the docs).

I actually thought we already had a `GeoSeries.transform`, but it seems we only have the `affine_transform`. There *is* a `GeoSeries.transform`, but that is the one inherited from pandas so which does not what we would want here.

**Comment by snowman2** [comment]
> And if we provide this generic transformation functionality, we can point there from the to_crs docs for custom CRS transformations (and have example's in the docs).

I think adding an example of how to do the fiona `transform_geom` to the docs might be a good start. I think the `Managing Projections` docs could use an update anyways.

**Comment by snowman2** [comment]
> It makes the function more complex, and it also kind of exposes implementation details.

Hmmm, maybe have an `engine` kwarg instead?

**Comment by snowman2** [comment]
@jorisvandenbossche, I am thinking instead to just add an example in the docs for how to transform geometries using `Fiona` in the `managing projection` section. Any issues with that?

**Comment by jorisvandenbossche** [comment]
That's certainly welcome!

(and I also still think a general `transform` method would be useful)

**Comment by snowman2** [comment]
> Basically it would be exposing shapely.ops.transform in a better way than doing a df.geometry.apply(lambda geom: transform(func, geom)) as what you need to do currently.
...
I actually thought we already had a GeoSeries.transform, but it seems we only have the affine_transform. There is a GeoSeries.transform, but that is the one inherited from pandas so which does not what we would want here.

Interesting :thinking:. I haven't used the pandas `transform` method. Would overwriting it lose any capability someone might need?

**Comment by martinfleis** [comment]
> Would overwriting it lose any capability someone might need?

I think so, pandas `transform` can be helpful on some occasions.

**Comment by jorisvandenbossche** [comment]
> I think so, pandas transform can be helpful on some occasions.

In general yes, but maybe less so for GeoSeries? (assuming we would only override it for GeoSeries, not for GeoDataFrame)

**Comment by jorisvandenbossche** [comment]
Alternative might be a method name like `geom_transform()` ?

**Comment by snowman2** [comment]
Another option could be to add a `.geo` accessor: #166.

**Comment by snowman2** [comment]
https://github.com/pyproj4/pyproj/discussions/863

It could also enable `Transformer.from_pipeline`

**Comment by snowman2** [comment]
Related: #2406
