### ISSUE TITLE
BUG: Some column names results into an error when write to a file

### ISSUE THREAD

**Issue by Doev** [geopandas/geopandas#1231]
```
import pandas as pd
import geopandas as gpd

# Error
test = pd.DataFrame([[1, 1, 1],],columns = ['x', 'y', 'Straßenschlüssel'])

# no Error
# test = pd.DataFrame([[1, 1, 1],],columns = ['x', 'y', 'Strassenschlüssel'])

shp = gpd.GeoDataFrame(test,geometry=gpd.points_from_xy(test.x,test.y))

shp.to_file('bug')
```

**Comment by martinfleis** [comment]
Thanks for the report. To add more details - it affects saving to ESRI Shapefile only, as GPKG or GeoJSON works. It raises `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 4: invalid continuation byte` due to ß in the name. 

If you specify encoding, the file saves correctly. 
```py
shp.to_file('file.shp', encoding='utf-8')
```

GeoPandas lets Fiona to take care of encoding, and its documentation says following:

> The format drivers will attempt to detect the encoding of your data, but may fail. In my experience GDAL 1.7.2 (for example) doesn’t detect that the encoding of the Natural Earth dataset is Windows-1252. In this case, the proper encoding can be specified explicitly by using the encoding keyword parameter of fiona.open(): encoding='Windows-1252'.

If you pass `encoding` to `to_file()`, it is passed to `fiona.open()` used under the hood. Honestly, I am not sure if there is anything we can do about it. If there is some solution, I think it should be in fiona.

**Comment by jorisvandenbossche** [comment]
@martinfleis thanks for the analysis.

cc @sgillies do you know if fiona should be expected to detect the field name encoding on writing automatically?

**Comment by sgillies** [comment]
This problem comes with the (shapefile) territory. Strictly speaking, Windows-1252 is a shapefile's default encoding.

@jorisvandenbossche OGR has to know the encoding to use before the shapefiles are initialized. In fiona (or geopandas) we could test the schema field names to see if they are Windows-1252 compatible, and if not, use utf-8, but I think it would still be possible to later find that some field values are not compatible, yes?

It might be okay for geopandas to default to `encoding=utf-8`. Export would most often work. The downside would be that some older GIS desktop software wouldn't be able to read default shapefile output.

**Comment by jorisvandenbossche** [comment]
If it is not shapefile's default, I am hesitant making UTF8 the default in geopandas (as you mention, that might not be good for interoperability).

If Fiona would like to do something like checking if the field names need UTF8, that would be a nice feature I think. But I am also fine with accepting that this is a limitation of shapefile's default we have to live with. 
We should document the `encoding` option maybe more prominently in the geopandas docs then (eg the `to_file` docstring), as now you actually need to look into fiona's docs to know this option.

**Comment by Doev** [comment]
I want to add, that it is not the special char 'ß' only. The behaviour is strange, i.e. 'Teßt' is working as name.

**Comment by martinfleis** [comment]
> I want to add, that it is not the special char 'ß' only. The behaviour is strange, i.e. 'Teßt' is working as name.

It might be related to necessary truncating of names for shapefile as it allows only 10 characters...
