### ISSUE TITLE
setting a tuple in a cell works in pandas but fails in geopandas

### ISSUE THREAD

**Issue by rbolgaryn** [geopandas/geopandas#1238]
Dear geopandas developers,

I am trying to add a new line in a GeoDataFrame with the method .loc.
The following code runs when tab is a pandas.DataFrame:

tab.loc[0, "coords"] = ((0,1), (2,3))

but fails, if tab is a GeoDataFrame:

File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\indexing.py", line 205, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\indexing.py", line 527, in _setitem_with_indexer
    "Must have equal len keys and value "
ValueError: Must have equal len keys and value when setting with an ndarray

I would expect that DataFrame and GeoDataFrame would behave in the same way in this situation.

pandas.__version__:  '0.25.3'
geopandas.__version__: '0.6.2'
python 3.7.3

Regards, Roman

**Comment by martinfleis** [comment]
Hi @rbolgaryn,
thank you for the report. Can you provide full reproducible example? Because I am getting the same error with pandas as well, so both behave the same in my case.

**Comment by jGaboardi** [comment]
This appears to be suspiciously similar to pandas-dev/pandas#28924.

**Comment by rbolgaryn** [comment]
Hi @martinfleis,

the minimal example would be:

```python
import pandas as pd
import geopandas as gpd
tab = pd.DataFrame(columns=['coords'], dtype=object)
tab.loc[0, 'coords'] = ((1,2), (3,4))

from shapely.geometry import LineString
gtab = gpd.GeoDataFrame(tab, geometry=tab.coords.apply(LineString))
gtab.loc[1, 'coords'] = ((2,3),(4,5))
```

The last line reproduces the error. The line with tab.loc[...] does not raise an error.

Regards, Roman

**Comment by martinfleis** [comment]
Thanks! Even though it looks like a different behaviour, it is the same. `tab` has only one column, while `gtab` has two. If you do following, you get the same error.

```py
tab = pd.DataFrame(columns=['coords'])
tab['col'] = 1
tab.loc[0, 'coords'] = ((1,2), (3,4))
```

Pandas expects that you are passing an array to be matched with the shape of the df and raises the error because it has a different shape. there is a lot of discussion on this topic on [SO](https://stackoverflow.com/questions/52552198/how-to-set-the-value-of-a-pandas-column-as-list/52552330#52552330), with some arguing that [one should not do this](https://stackoverflow.com/a/52563718/9978945). You might find workarounds there.

Anyway, it does seem to be pandas issue, not geopandas (unless my theory does not fit to your experience).
