### ISSUE TITLE
current access to vectorized operations anywhere?

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#1246]
Hi All -- killing myself on some intersections -- I know there's a plan to eventually get pygeos' vectorized ops integrated [via Shapely](https://github.com/Toblerity/Shapely/issues/782). Anyone know if there's a working implementation of geopandas with vectorized geometric operations available (e.g. hiding on someone's branch)?

**Comment by brendan-ward** [comment]
@nickeubank , for a recent project where I needed the performance from `pygeos` I just used it directly, and moved to / from Geopandas as needed.  It was a bit messy but got the job done.  It will be awesome when `pygeos` lands in `shapely` and `geopandas`.

For what I was doing, I largely worked with the `pygeos` geometries in a regular DataFrame.

Here's my code for going to / from, in case it is helpful for you:

```
import numpy as np
import pandas as pd
import geopandas as gp
import pygeos as pg
from pygeos import from_wkb, to_wkb
from shapely.wkb import loads


def to_pygeos(geoseries):
    """Converts a GeoSeries to a Series of pygeos geometry objects.

    Parameters
    ----------
    geoseries : GeoSeries

    Returns
    -------
    Series
    """
    return pd.Series(from_wkb(geoseries.apply(lambda g: g.wkb)), index=geoseries.index)


def from_pygeos(geometries):
    """Converts a Series or ndarray of pygeos geometry objects to a GeoSeries.

    Parameters
    ----------
    geometries : Series or ndarray of pygeos geometry objects

    Returns
    -------
    GeoSeries
    """
    def load_wkb(wkb):
        return loads(wkb)

    wkb = pg.to_wkb(geometries)

    if isinstance(geometries, pd.Series):
        return gp.GeoSeries(wkb.apply(load_wkb))

    return gp.GeoSeries(np.vectorize(load_wkb, otypes=[np.object])(wkb))


def to_gdf(df, crs):
    """ Convert a data frame that has pygeos geometry to a GeoDataFrame
    Parameters
    ----------
    df : DataFrame
        must have pygeos geometry in "geometry" column
    crs : geopandas CRS object
    Returns
    -------
    GeoDataFrame
    """
    df = df.copy()
    df["geometry"] = from_pygeos(df.geometry)
    return gp.GeoDataFrame(df, crs=crs)
```

For my particular stack (involves lots of intermediate files and a chain of processing steps), I also implemented support in [geofeather](https://github.com/brendan-ward/geofeather) for going directly to / from `pygeos` geometry objects; this cut down on several places where I would otherwise have to convert to / from GeoDataFrames.  Longer term, this will be obviated by the `parquet` support we are working on in `geopandas`.

I built several other shims to replicate some of the geopandas functions I needed: `explode()`, `dissolve()`, and a rough stab at `sjoin()`.  Direct message me if these would be helpful for you.

Note: since prepared geometries are not yet supported in `pygeos`, some operations are still faster in `geopandas` than `pygeos`  (e.g., spatial join from few, large polygons against many much smaller features).

**Comment by nickeubank** [comment]
That's terrific, thanks @brendan-ward !

**Comment by martinfleis** [comment]
Check also #1154
