### ISSUE TITLE
PROPOSAL: Load subset of columns on read file

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#1268]
Related:
- https://gis.stackexchange.com/questions/129414/only-read-specific-attribute-columns-of-a-shapefile-with-geopandas-fiona#129422
- https://gis.stackexchange.com/questions/348064/rasterising-multiple-shapefiles-into-a-single-raster/348065#348065
- #1157 

Thoughts?

**Comment by martinfleis** [comment]
See this discussion https://github.com/jGaboardi/geopackage_tutorial/issues/1#issuecomment-573103316

I like this idea.

cc @ljwolf

**Comment by brendan-ward** [comment]
In #1180, we're planning to surface this capability for `parquet` format files, since it is builtin to the `parquet` driver.  In my own work with a similar format (`geofeather`), being able to load subsets of columns can lead to significant performance improvements - so it seems like it would be a good addition to `geopandas` overall.  Not sure about the performance benefits for reading subsets through `fiona`.

Worth considering: sometimes it is very useful to load only the attributes and not the geometry from a geo format.

**Comment by goatsweater** [comment]
I've actually done this type of work in the past to avoid loading all the columns on large datasets. It results in a significant savings of memory. The `usecols` argument name is also consistent with pandas interfaces.

Using `fiona` to produce a `pd.DataFrame` through a similar interface is also convenient when trying to load attribute tables from layered data sources that pandas can't understand itself (like FGDB). 

```py
def table(filename, usecols, **kwargs):
  with fiona.open(filename, **kwargs) as source:
    for feature in source:
      f = {k: feature['properties'][k] for k in usecols}
      yield f

# read from FGDB
pd.DataFrame.from_records(table(path, columns_of_interest, layer=attrib_tbl))
```
