### ISSUE TITLE
Remove unused points_from_xy

### ISSUE THREAD

**Issue by jsignell** [geopandas/geopandas#1296]
I don't think this `points_from_xy` is used anywhere:
 https://github.com/geopandas/geopandas/blob/9e45a12bcf114e13fc530ce9ff8a7eb533c9de86/geopandas/array.py#L204

The init does:

https://github.com/geopandas/geopandas/blob/9e45a12bcf114e13fc530ce9ff8a7eb533c9de86/geopandas/__init__.py#L3

**Comment by martinfleis** [comment]
I think someone just forgot to change it. `points_from_xy` should be used as it ensures that resulting points are returned as GeometryArray. So instead of removing it, I think we should change  
`from geopandas.array import _points_from_xy as points_from_xy` to 
`from geopandas.array import points_from_xy`.

**Comment by jorisvandenbossche** [comment]
Yeah, I think it stemmed from before introducing GeometryArray, and it wasn't updated to return that. But I think it is good to change that.
