### ISSUE TITLE
Fail to install geopandas with Anaconda 2020 

### ISSUE THREAD

**Issue by VietEcon** [geopandas/geopandas#1357]
Hi I tried to install geopandas as follow:

- Install fresh anacoda 2020.02 for Window (Python 3.7, 64 bit) from https://www.anaconda.com/distribution/
- Install geopandas by conda install geopandas

However geopandas installation failed with a long report of conflicted packages. 

Any help is appreciated. Thanks!

**Comment by martinfleis** [comment]
Have you tried using `conda-forge` channel as docs suggests? https://geopandas.readthedocs.io/en/latest/install.html#using-the-conda-forge-channel

**Comment by jorisvandenbossche** [comment]
Alternatively, I would also try creating a new environment:

```
conda create -n geo geopandas
```

that works for me at the moment (but on linux, not windows).

In general, issues with the default channel can be reported at https://github.com/ContinuumIO/anaconda-issues/issues (we don't have any control over that)

**Comment by VietEcon** [comment]
Thanks @martinfleis @jorisvandenbossche  for suggestions.

I tried both, installation via conda-forge and creating new environment but the error remains (long list of conflicted packages) :(

**Comment by jorisvandenbossche** [comment]
Can you show the commands you are running and the output? 
For conda-forge, it might also be needed to create a new environment, since the base environment from Anaconda is full of packages from the defaults channel). See here https://geopandas.readthedocs.io/en/latest/install.html#creating-a-new-environment for exact instructions how to create an environment with the proper settings enabled.

**Comment by VietEcon** [comment]
Cool, it works for me now using a new environment with conda-forge as strict priority. Many thanks!
