### ISSUE TITLE
Legend: problem with legend_kwds and scheme

### ISSUE THREAD

**Issue by Tegomena** [geopandas/geopandas#1368]
Hello,
I have a problem with combining legend_kwds and scheme in a plot. I'm plotting a map which works fine:

```
merged.plot(column="confirmed", cmap='OrRd',  edgecolor='black', linewidth=0.1, legend=True,  legend_kwds={'label': "Confirmed cases",'orientation': "horizontal"}) 
```

Now, I wanted to add "scheme" parameter to the plot (the only difference to the command above is the scheme='Percentiles' parameter):

```
merged.plot(column="confirmed", cmap='OrRd',  edgecolor='black', linewidth=0.1, legend=True,  legend_kwds={'label': "Confirmed cases",'orientation': "horizontal"}, scheme='Percentiles') 
```

That results in an error:

```
File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 406, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'label'
```

**Comment by martinfleis** [comment]
Once you use `scheme`, your legend is no longer colorbar, but categorical one. Because scheme gives you categories. And for categorical legend, `'label'` and `'orientation'` do not work. You can use `'title'` instead of label. If you want to use colorbar, you will have to normalise colormap ([this](https://gis.stackexchange.com/questions/330008/center-normalize-choropleth-colors-in-geopandas) might help with that).

**Comment by Tegomena** [comment]
Thanks a lot, I got it!!
