### ISSUE TITLE
BUG: CRS not propagated to array

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1374]
I have found one issue caused by #1339. OSMnx [uses](https://github.com/gboeing/osmnx/blob/a4b4dc9efb8223b8aab257ff8825454d4bd06ddc/osmnx/projection.py#L71-L75) following pattern:

```py
geometry = Point(0,0)  # my addition

gdf = gpd.GeoDataFrame()
gdf.crs = 4326
gdf['geometry'] = None
gdf.loc[0, 'geometry'] = geometry
...
gdf.to_crs()  # it fails here due to missing CRS
```

In the end, gdf does have CRS but `geometry` and GeometryArray do not. It just raises two warnings:

```
FutureWarning: Assigning CRS to a GeoDataFrame without a geometry column is now deprecated and will not be supported in the future.

UserWarning: Geometry column does not contain geometry.
```

I would say that we should fix that now, but it is not a pattern I would encourage at all.

**Comment by jorisvandenbossche** [comment]
That's indeed a pattern we want to discourage ;)

I suppose the problem is that `gdf.loc[0, 'geometry'] = geometry` directly involves setting values in the GeometryArray (if there would be one, see below), without going through a GeoDataFrame method (like `__getitem__`) where we can "fix" this to set the gdf's crs. 

> gdf['geometry'] = None
> UserWarning: Geometry column does not contain geometry.

I suppose we can fix this case to ensure that we create an empty GeometryArray here (instead of raising the warning en letting pandas create an empty object dtype column). 
If we then also directly set the gdf's crs, I think that should also solve the above issue.
