### ISSUE TITLE
Properly handle rows with missing geometries

### ISSUE THREAD

**Issue by jwass** [geopandas/geopandas#139]
GeoSeries and GeoDataFrame should support missing values in the geometry column like all of Pandas, with a fill value of `np.nan`.

For rows with missing geometries:
`df.area` should return `nan`
`df.intersects` would return `False`
`df.buffer` would return `nan`

Thoughts? Pretty sure that's in sync with Pandas patterns.

**Comment by IamJeffG** [comment]
To be most completely consistent with Pandas seems we ought to recognize both `None` and `np.nan` as missing geometry values:

> "`NaN` and `None` (in object arrays) are considered missing by the `isnull` and `notnull` functions."
> http://pandas.pydata.org/pandas-docs/stable/missing_data.html

That said, initial support for even just one of these is a win in my book: doesn't matter which as long as we document it clearly.

**Comment by IamJeffG** [comment]
While trying to finish out this issue for some more operations (e.g. `.centroid`, `.bounds`), I notice that `GeoPandasBase.isnull()` is already implemented such that an empty geometry returns true for `isnull`.  The implication is that empty geometries are also a way to signify missing data.

This is fine, except for an edge case that buffering an empty geom doesn't return `nan` (as suggested above), it returns another empty geom.  This may be logically ok since we just said that _both_ `nan` and empties are "missing".  But it's probably confusing to the user.

Is there any preference to keep a distinction between an empty geom vs. missing?

**Comment by oztalha** [comment]
Although isnull() works as expected, dropna() does nothing on geoseries:
```
a = gpd.GeoSeries([1, 2, pd.np.nan, 3])
a.dropna()
```
Actual:
```
0    1.0
1    2.0
2    NaN
3    3.0
dtype: float64
```
Expected:
```
0    1.0
1    2.0
3    3.0
dtype: float64
```

**Comment by jorisvandenbossche** [comment]
@oztalha answered in the other issue (https://github.com/geopandas/geopandas/issues/314#issuecomment-284180090)

**Comment by martinfleis** [comment]
Missing geometries / empty geometries are now all supported and have been recently clarified (https://geopandas.readthedocs.io/en/latest/missing_empty.html).
