### ISSUE TITLE
Warn when writing to Shapefile will change column names

### ISSUE THREAD

**Issue by KarenChen9999** [geopandas/geopandas#1417]
I used gpd.to_file to save my geo dataframe object into a shapefile. However some of my column names have changed. Does anyone know why that occurred and how to fix that? I can rename the columns back to their original names but it would be good to know why that happened.

`sample_target0_ff.to_file(out_path+'shp/sample_target0_ff.shp', driver='ESRI Shapefile')
`
and the name is changed from "ignition_id" to "ignition_i" and from "pbi_grid_id" to "pbi_grid_i"

**Comment by KarenChen9999** [comment]
Just noted that someone mentioned that only 10 characters are allowed. if it is nto the case, can someone suggest what other reasons could be?

**Comment by jorisvandenbossche** [comment]
Indeed, see eg "Maximum length of field names is 10 characters" at https://en.wikipedia.org/wiki/Shapefile#Limitations

We could actually detect this and raise a warning, if we want (since regularly people run into this issue). 
And we should maybe also better document it in our own docs, although it is a general Shapefile issue.
