### ISSUE TITLE
plotting a polygon

### ISSUE THREAD

**Issue by manisekhar-kothuri** [geopandas/geopandas#1461]
I tried to look the polygon of given dataframe
![waste](https://user-images.githubusercontent.com/59639296/83512865-7c220f00-a4ee-11ea-91a4-87fdb2bfd0c4.PNG)
but I got output like
![waste2](https://user-images.githubusercontent.com/59639296/83512924-90fea280-a4ee-11ea-950f-1ac03983bc9a.PNG)
There is change in coordinates.So,I am not able to plot Geodataframe
While plotting the above dataframe I got ouput like:
![waste3](https://user-images.githubusercontent.com/59639296/83513180-04a0af80-a4ef-11ea-9ddb-21465dd1b369.PNG)
which has not polygon shapes
How to handle this?

**Comment by martinfleis** [comment]
This seems to be some issue with your data.

How did you create `s` GeoDataFrame? Is it possible that you have geometries in mixed projections in it?  Is it possible, that your polygons are just very small on the edges of the plot? That could be easily cause by one faulty polygon far from the other. What happens if you try to plot first 5 geometries instead of one?

**Comment by manisekhar-kothuri** [comment]
I used a shapefile created from json data.
![worst](https://user-images.githubusercontent.com/59639296/83525032-0f187480-a502-11ea-8af4-2e4d05f0b8ce.PNG)
It contains only 5 shapes as mentioned above.
Last plot in last post is plot of all 5 shapes which is not visible

**Comment by martinfleis** [comment]
I think that your polygons are just very small and very far away from each other. That is the reason why the plot looks empty (it is not in fact).

**Comment by jorisvandenbossche** [comment]
@manisekhar-kothuri please try to provide a reproducible example (https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)
