### ISSUE TITLE
support for the missing_kwds parameter of the plot function no longer exists in version 0.8.0

### ISSUE THREAD

**Issue by Benidrissa** [geopandas/geopandas#1501]
support for the missing_kwds parameter of the plot function no longer exists in version 0.8.0.
I have to go back v0.7.0 to use it

**Comment by martinfleis** [comment]
Thanks for the report. Are you sure you are on 0.8.0? Because it normally works for me. Can you provide a reproducible example and error message (Traceback)?

**Comment by Benidrissa** [comment]
[](https://colab.research.google.com/drive/1Yb01cV9pJX2mMbts8S3Nw7rxRJP6etuy?usp=sharing)

[](https://drive.google.com/file/d/1Z4vwf6bqYIvORi15WfNvjr3ChfVkWQGD/view?usp=sharing)

[](https://drive.google.com/file/d/1AMx1MMGJzGtrdeOFX7pDELo5nsXQJbAh/view?usp=sharing)

**Comment by martinfleis** [comment]
The colab notebook does not show the issue. I was not able to reproduce it even in colab (see my [notebook](https://colab.research.google.com/drive/1a4LBA20wG07CACMrlZWxx6PdpffUcWsy?usp=sharing)). Everything works as intended. If you can provide an example which fails, I can look at it, but now it seems that the issue was elsewhere.

**Comment by Benidrissa** [comment]
All right. Thanks for the feedback. I'll investigate further then.Why my unchanged code doesn't work with version 0.8.0 anymore until I remove the missing_kwds parameter.

**Comment by martinfleis** [comment]
I would have to see the actual issue with the Traceback to happen to be able to answer that. It always worked when I tried to replicate the issue.
