### ISSUE TITLE
BUG: parquet test failing with arrow 1.0

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1536]
[CI is failing](https://travis-ci.org/github/geopandas/geopandas/jobs/711727213#L2136) due to some changes in arrow. It apparently no longer supports non-unique columns.

@brendan-ward is this something to be reported to `pyarrow` or should we just skip this test?

**Comment by brendan-ward** [comment]
The existing behavior on pyarrow 0.17 is that duplicate column names requested on read of parquet are deduplicated into unique columns:
```
>>> df = gp.read_parquet('/tmp/test.pq', columns=['name', 'name', 'geometry'])
>>> df.columns
Index(['name', 'geometry'], dtype='object')
```

The test here was primarily to make sure that requesting multiple columns deduplicated them.  Writing to a parquet / feather file with duplicate column names fails, so there is no expectation that we'd get back multiple columns.

I think it is OK to let this fail with a `ValueError` on the pyarrow side; this does not harm expected outputs, and is probably a good signal to the user that something is wrong in their request.  Since this takes an edge case in new functionality and switches from passing it silently to failing on duplicate, I think we can proceed without a deprecation warning.

Fix coming up...
