### ISSUE TITLE
DOC: document existing way to add a scale bar to the geopandas plot

### ISSUE THREAD

**Issue by camilogutierrez** [geopandas/geopandas#1597]
![image](https://user-images.githubusercontent.com/60492494/91666533-1f20ff80-eac3-11ea-9238-015858a52dbf.png)

**Comment by martinfleis** [comment]
Yes, you can use `matplotlib-scalebar` - https://github.com/ppinard/matplotlib-scalebar. 

```py
import geopandas as gpd
from matplotlib_scalebar.scalebar import ScaleBar
import matplotlib.pyplot as plt

df = gpd.read_file(gpd.datasets.get_path('nybb'))

ax = df.to_crs(32619).plot()  # re-projecting from feet to metres
ax.add_artist(ScaleBar(1))
```

![download](https://user-images.githubusercontent.com/36797143/91764492-4cf36a80-ebcf-11ea-87b0-66f1516b4ce2.png)


Note that this assumes projected CRS in metres, for other options and details refer to the documentation of `matplotlib-scalebar`. 

I'll keep this open because it would be nice to have this snippet in our examples section in docs.
