### ISSUE TITLE
BUG: categories passed as a series are not properly sorted

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1634]
If you pass a series of categories to plot, those are used directly as an array, even though the series might have an index of a different order than df. See the example below.

```python
from shapely.geometry import Point
import pandas as pd

pts = [Point(x, x) for x in range(10)]
df = gpd.GeoDataFrame(geometry=pts)

# this is correct, since gdf.index and colors.index are in the same order
colors = pd.Series(['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a'])
df.plot(colors, legend=True)
```
![image](https://user-images.githubusercontent.com/36797143/94190673-54dbbd00-fea4-11ea-865d-845bd77ad929.png)

```python
# I would assume that this gets sorted based on the index first, but it does not - the index is ignored
colors_ord = pd.Series(['a', 'a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c'], index=[0, 3, 6, 9, 1, 4, 7, 2, 5, 8])
df.plot(colors_ord, legend=True)
```
![image](https://user-images.githubusercontent.com/36797143/94190771-789f0300-fea4-11ea-9fc3-b23a11caf568.png)

```python
# if you assign the same series as a column before plotting, it works properly
df['colors_ord'] = colors_ord
df.plot('colors_ord', legend=True)
```
![image](https://user-images.githubusercontent.com/36797143/94190841-90768700-fea4-11ea-9320-9c63fab23a63.png)

I would say that in these cases, we should check the index first and sort it properly before using values.

**Comment by jorisvandenbossche** [comment]
Indeed, this is certainly a bug. In "pandas terminology", we are missing alignment. Like in other operations in pandas, you expect the passed Series with values/colors to be aligned with the Series/DataFrame with geometries that is being plotted. 

In this case, this can be solved with using the `reindex` function (instead of sorting), I think. If the passed values are a Series, do a `values.reindex(df.index)` will ensure the values are aligned with the dataframe being plotted.
