### ISSUE TITLE
ENH: allow all predicates in sindex.query

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1696]
We have a hard-coded list of valid predicates for `sindex.query` and `query_bulk`. But pygeos now supports more of them (`contains_properly`, maybe more I did not check). Would be ideal to let pygeos/rtree to raise an error if an unsupported predicate is passed, so we don't have to keep track of what is supported where.

I vaguely remember some discussion on this, but I could not find it, so I am not sure if there is not a good reason for this solution (maybe @adriangb remember?).

https://github.com/geopandas/geopandas/blob/aa687662791863d55d3e27e8d468d9eb2eed82bd/geopandas/sindex.py#L8-L16

**Comment by adriangb** [comment]
I agree. I do not remember the discussion really.

I'd say the only real requirement to do this is to standardize the error raised. We should also have a standard error for geometry types (eg: a KDTree based spatial index can only handle points, not polygons).

I think we should add standardized errors for both and catch and convert the specific errors within our wrappers.

**Comment by brendan-ward** [comment]
pygeos also supports `covers` and `covered_by` predicates in addition to `contains_properly` and the set above.  Not sure if these are also supported by rtree implementations here.

I recall the set above was used to define the subset of predicates known to be available in both, and also to provide standardized error handling.

One option might be to use the [enumeration in pygeos strtree](https://github.com/pygeos/pygeos/blob/0.8/pygeos/strtree.py#L9) to check predicates supported by pygeos for `query` / `query_bulk`, since that has to be in sync with the underlying implementation.

Otherwise, pygeos emits a `ValueError` on unsupported predicate, but that would require checking also the error message (since a number of things raise `ValueError`s) - which seems brittle, since that error message may get changed at any point without being aware that things here depend on that value.

**Comment by adriangb** [comment]
Hmm. I feel that from the GeoPandas side we should have:
- A standard error message for unknown predicates.
- A standard error message for unsupported geometries.
- A standard API for querying available predicates.

Now, if for example someone wanted to generate a wrapper for a spatial index that does not have _any_ way to query what predicates it supports (and they aren't listed in the docs or anything), the user could _not_ implement the method in which case a `NotImplementedError` would be raised.

As to how to catch and convert errors from the underlaying spatial index within the wrapper, I think that's an implementation detail. We can get as messy as we want with PyGEOS (since we're familiar with the internals).

This may be better described as part of a PR. I'll try to cook one up within the next couple of days.

**Comment by brendan-ward** [comment]
Perhas this hard-coded set of predicates could be replaced by a bit of custom code in each sindex backend, which in the case of pygeos could simply obtain that from the enumeration mentioned above. 

Then internally, for all intents and purposes, this could be used similar to how the hard-coded set is used now.

I think the main point is to push the maintenance of the set of available predicates down to the underlying backends, and load it dynamically here.

**Comment by jorisvandenbossche** [comment]
We can move `VALID_QUERY_PREDICATES` variable from module level to be a class attribute/property? And then it can be different for both implementations?

Also, I don't think there is a specific reason that the rtree-based sindex couldn't also support `covers` and `covered_by`. We are simply using Shapely geometry objects in the query method, and so whather shapely supports, can be supported in the query as well (I think `covered_by` is not yet in a released version though). 
Even `contains_properly` is actually available in Shapely.
