### ISSUE TITLE
BUG: explode() conflicts with native pandas explode() method

### ISSUE THREAD

**Issue by iboates** [geopandas/geopandas#1719]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import geopandas as gpd

df = pd.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})
gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.Longitude, df.Latitude))
gdf["list_col"] = gdf["Country"].split("n")
gdf.explode("listcol")
```

#### Problem description

Pandas has a method called `explode()` and it seems that it gets shadowed by the Geopandas function of the same name, requiring you to do an unwrap and a wrap to pandas and back to get the pandas functionality.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.explode.html#pandas-dataframe-explode

#### Expected Output

```python
import pandas as pd
import geopandas as gpd

df = pd.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})
gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.Longitude, df.Latitude))
gdf["list_col"] = gdf["Country"].split("n")
gpd.GeoDataFrame(pd.DataFrame(df).explode("n"), geometry="geometry")
```

#### Output of ``geopandas.show_versions()``

```
SYSTEM INFO
-----------
python     : 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
executable : [redacted]
machine    : Linux-5.4.0-42-generic-x86_64-with-glibc2.29
GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 2.4.4
GDAL data dir: [redacted]
PROJ       : 7.0.1
PROJ data dir: [redacted]
PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.4
fiona      : 1.8.17
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : None
pyproj     : 2.6.1.post1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : 2.8.6 (dt dec pq3 ext lo64)
geoalchemy2: 0.8.4
pyarrow    : None
```

</details>

**Comment by jorisvandenbossche** [comment]
@iboates thanks for the report. This is indeed an issue, since pandas added this `exlode` method (the geopandas method predates pandas). 
See also https://github.com/geopandas/geopandas/issues/1140, we should update our `GeoDataFrame.explode` method to use pandas' version when the specified column is not the geometry column.

**Comment by martinfleis** [comment]
Closed by #1720

**Comment by Robbie-Palmer** [comment]
#1720 has resolved calling a GeoSeries object's `.explode()` method
But applying the `GeoSeries.explode` class method triggers the same issue
It doesn't fallback to using `Series.explode` for non-geometric series wrapped in a `GeoSeries`

The reason I triggered this is because I want to use the `apply` function to apply an "explosion" to all columns in the GeoDataFrame, including the non-geometric ones
Because all columns have lists of values that map to each other

```
singular_values = nested_values.apply(GeoSeries.explode)
```

I'm not sure whether this should be linked to this issue, or issue #1140 or have its own issue

**Comment by martinfleis** [comment]
@Robbie-Palmer can you report it as a separate issue?
