### ISSUE TITLE
ENH: GeoPandas with concave hull computation from AlphaShape

### ISSUE THREAD

**Issue by PeterFogh** [geopandas/geopandas#1739]
#### Is your feature request related to a problem?

I wish I could use GeoPandas to do concave hull computation.

#### Describe the solution you'd like

The package [AlphaShape](https://alphashape.readthedocs.io/en/latest/alphashape.html) (e.g. via conda https://anaconda.org/conda-forge/alphashape already facilitates concave hull computation I wish was in GeoPandas. AlphaShape already integrates with GeoPandas - I just like geopandas to facilitate a `concave_hull` function like the existing `convex_hull` (https://geopandas.org/geometric_manipulations.html#GeoSeries.convex_hull)

#### API breaking implications

None

#### Describe alternatives you've considered

None

#### Additional context

None

**Comment by martinfleis** [comment]
Hey, thanks for the suggestion!

Just to clarify - `AlphaShape` seems to generate a single shape out of all points in GeoDataFrame. That is different behaviour than our `convex_hull` has, which generates convex hull for each geometry separately. Which of the two would you like to see in GeoPandas?

There are more packages which can do alpha shape (i.e. [libpysal can do it as well](https://pysal.org/libpysal/generated/libpysal.cg.alpha_shape.html#libpysal.cg.alpha_shape) si we would have to choose the implementation.

Do you think it would be enough to add an example to the documentation on how to generate alpha shape using external packages? Because the only gain I can see from the introduction of `concave_hull` method would be convenience. This method is not part of GEOS (I think) so we would not be able to provide fast vectorized version using pygeos anyway.

**Comment by PeterFogh** [comment]
Hello @martinfleis 

Thanks for your answer :) and sorry for the late reply.

---------------------------

> AlphaShape seems to generate a single shape out of all points in GeoDataFrame.

I think GeoPandas should keep its way of processing individual rows of the GeoDataFrame - thus forcing the user to use `geoseries.unary_union.convex_hull` or `geoseries.unary_union.concave_hull()` if the user wants the hull of all points in the geoseries.

--------------------------

> There are more packages which can do alpha shape (i.e. libpysal can do it as well) so we would have to choose the implementation.

I do not know the current design choice of GeoPandas - do you prefer to depend on 3-party packages? If so I would choose the package with the biggest support/userbase or the one you already depend on.
Personally, my opinion is to avoid package dependencies for only a single functionality (e.g. alpha shape implementation) - instead, I think it is better to just implement it as part of in GeoPandas.

----------------------------

> Do you think it would be enough to add an example to the documentation on how to generate alpha shape using external packages? Because the only gain I can see from the introduction of concave_hull method would be convenience.

Yes, this feature request is only for convenience, i.e. no need to explicit install AlphaShape. Again, I do not know the current design choice of GeoPandas, but yes, documenting how to generate alpha shape using external packages could be a minimal solution/hot-fix.

**Comment by jdmcbr** [comment]
The 3.11 GEOS release includes support for concave hull calculations (https://libgeos.org/doxygen/classgeos_1_1algorithm_1_1hull_1_1ConcaveHull.html). This may make it relatively straightforward to incorporate a performant implementation in pygeos/geopandas.

**Comment by m-richards** [comment]
Concave hull is actually already in shapely 2.0 (https://github.com/shapely/shapely/pull/1518) so this should just be a matter of exposing geometryarray/geoseries bindings along the same line as others in #2010.
