### ISSUE TITLE
BUG: GeoDataFrames with MultiIndex as columns do not support CRS

### ISSUE THREAD

**Issue by adamjstewart** [geopandas/geopandas#1763]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample

```python
>>> import pandas as pd
>>> import geopandas
>>> df = pd.DataFrame([[1, 0], [0, 1]], columns=[['location', 'location'], ['x', 'y']])
>>> gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df['location', 'x'], df['location', 'y']))
>>> print(gdf.crs)
None
>>> gdf = geopandas.GeoDataFrame(df, crs="EPSG:4326", geometry=geopandas.points_from_xy(df['location', 'x'], df['location', 'y']))
>>> print(gdf.crs)
None
>>> gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df['location', 'x'], df['location', 'y'], crs="EPSG:4326"))
>>> print(gdf.crs)
None
>>> gdf = geopandas.GeoDataFrame(df, crs="EPSG:4326", geometry=geopandas.points_from_xy(df['location', 'x'], df['location', 'y'], crs="EPSG:4326"))
>>> print(gdf.crs)
None
>>> gdf = gdf.set_crs("EPSG:4326")
>>> print(gdf.crs)
None
```

#### Problem description

The first print-statement works as expected because I never specified a CRS, but the following 4 methods of setting the CRS should work. They seem to work for `pd.Index`, but not `pd.MultiIndex`. Since many `geopandas` operations like `sjoin` require a matching CRS, this causes problems for other operations as well. Obviously in this trivial example I don't _have_ to use a MultiIndex, but there are many applications where a MultiIndex is required.

#### Expected Output

I would expect the last 4 print-statements to show:
```python
>>> print(gdf.crs)
EPSG:4326
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.7 (default, Dec 30 2020, 11:40:19)  [Clang 12.0.0 (clang-1200.0.32.28)]
executable : /Users/Adam/.spack/.spack-env/view/bin/python
machine    : macOS-10.15.7-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.1
GEOS lib   : /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/geos-3.8.1-vlrmv4vvnmfcvabpu6t4boks5fxtllko/lib/libgeos_c.dylib
GDAL       : 3.2.0
GDAL data dir: /Users/Adam/.spack/.spack-env/view/share/gdal
PROJ       : 7.1.0
PROJ data dir: /Users/Adam/.spack/.spack-env/view/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.2.0
fiona      : 1.8.18
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : None
pyproj     : 2.6.0
matplotlib : 3.3.3
mapclassify: 2.4.2
geopy      : 2.1.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None

</details>

P.S. I'm happy to contribute a PR to fix this if someone can point out where the problem might be.

**Comment by martinfleis** [comment]
This is an interesting one :). Thank you for the report.

During initialization of gdf, we go via `set_geometry` here (in this case):

https://github.com/geopandas/geopandas/blob/36521787c3e6484c00c2ffb8cdde60798d6d1616/geopandas/geodataframe.py#L151

With the method itself defined here:
 
https://github.com/geopandas/geopandas/blob/36521787c3e6484c00c2ffb8cdde60798d6d1616/geopandas/geodataframe.py#L185

However, what puzzles me a bit is the fact than the initialization of the GeoDataFrame is not done once but 16x. If you add `print("init")` after `def __init__`, you get one print for normal index and 16 prints for the case above. While in the first loop CRS seems to be preserved, it gets lost in the other. 

The same happens with the pure `gdf.copy()`. With a normal index, it calls `__init__` once. With `MultiIndex`, it gets called 36x times.

I'd love to point you to a more specific section but I am not entirely sure what is going on. A fix would be very appreciated.

**Comment by adamjstewart** [comment]
Strangely enough, this doesn't seem to affect `GeoSeries`, only `GeoDataFrame`:
```python
>>> import pandas as pd
>>> import geopandas
>>> from shapely.geometry import Point
>>> s = geopandas.GeoSeries([Point(1, 1), Point(2, 2), Point(3, 3)])
>>> index = pd.MultiIndex.from_tuples([(0, 1), (0, 2), (1, 3)])
>>> s.index = index
>>> s = s.set_crs("EPSG:4326")
>>> print(s.crs)
EPSG:4326
```

**Comment by adamjstewart** [comment]
Why does `GeoSeries` use `__new__` but `GeoDataFrame`, `Series`, and `DataFrame` all use `__init__`?

**Comment by martinfleis** [comment]
The issue is not with `MultiIndex` as an index but as columns. That is why it does no affect `GeoSeries.

> Why does GeoSeries use __new__ but GeoDataFrame, Series, and DataFrame all use __init__?

from the code:
```
# we need to use __new__ because we want to return Series instance
# instead of GeoSeries instance in case of non-geometry data
```

**Comment by adamjstewart** [comment]
If I remove this curious bit of code, everything works as expected and `__init__` doesn't get called dozens of times:
https://github.com/geopandas/geopandas/blob/master/geopandas/geodataframe.py#L1227,L1229

This seems to be a `pandas` thing that I don't know much about.

**Comment by martinfleis** [comment]
We need `_constructor` to make sure we always return `GeoDataFrame` and not `DataFrame`. 

One workaround, for now, is to create geometry column in `DataFrame` and pass only its name.

```python
>>> import pandas as pd
>>> import geopandas
>>> df = pd.DataFrame([[1, 0], [0, 1]], columns=[['location', 'location'], ['x', 'y']])
>>> df["geom"] = geopandas.points_from_xy(df['location','x'], df['location', 'y'])
>>> gdf = geopandas.GeoDataFrame(df, geometry="geom", crs="EPSG:4326")
gdf.crs

<Geographic 2D CRS: EPSG:4326>
...
```

So the issue is with the creation using the pattern above only.

The loop calling `__init__` multiple times may not be an issue but a result of some operations pandas does under the hood. We have to figure out where we lose CRS and how to preserve it.

**Comment by martinfleis** [comment]
The issue boils down to some logic in `set_geometry`, which does not preserve CRS in this specific case.
```py
>>> import pandas as pd
>>> import geopandas
>>> df = pd.DataFrame([[1, 0], [0, 1]], columns=[['location', 'location'], ['x', 'y']])
>>> gdf = geopandas.GeoDataFrame(df)

>>> geom = geopandas.points_from_xy(df['location','x'], df['location', 'y'])

# this should return CRS but returns None
>>> gdf.set_geometry(geom, crs=4326).crs
```

And it does not matter if you specify crs in `set_geometry` or above in `points_from_xy`.

**Comment by adamjstewart** [comment]
@martinfleis thanks for the workaround! Interestingly, if I name the column `geometry` instead of `geom` it breaks.

It sounds to me like this may be a pandas issue. I don't see why `__init__` needs to be called multiple times, but if it does, it should be passing all of the same args that it received at the first call.

**Comment by m-richards** [comment]
I've had a look at this now - using the Jan 1 example, but it's far more complicated rabbit hole than I thought. I'll still document what I've found.

> The loop calling `__init__` multiple times may not be an issue but a result of some operations pandas does under the hood. We have to figure out where we lose CRS and how to preserve it.

The multiple calling to `__init__` is triggered by accessing `self.geometry` when the geometry column is a multi-index. 
This occurs in `set_geometry` via the crs setting, (https://github.com/geopandas/geopandas/blob/cb88dd4a9100bb990f6eb9b286e1ef3a0b185e3c/geopandas/geodataframe.py#L305) which in turn accesses `self.geometry` (https://github.com/geopandas/geopandas/blob/cb88dd4a9100bb990f6eb9b286e1ef3a0b185e3c/geopandas/geodataframe.py#L401-L403). Tracing this back, the method sequence is https://github.com/geopandas/geopandas/blob/cb88dd4a9100bb990f6eb9b286e1ef3a0b185e3c/geopandas/geodataframe.py#L1298
to `DataFrame.__getitem__` in pandas [1.2.4 in the environment I'm testing this] (which doesn't have nice previews here it seems) https://github.com/pandas-dev/pandas/blob/bf157517d08914e2cbaa7a0bf975952e303dd43e/pandas/core/frame.py#L3419
 -> to `DataFrame._getitem_multilevel(self, key)`
https://github.com/pandas-dev/pandas/blob/bf157517d08914e2cbaa7a0bf975952e303dd43e/pandas/core/frame.py#L3504. 
-> `DataFrame.reindex()` -> `NDFrame.reindex()` -> `DataFrame._reindex_axes` -> `DataFrame._reindex_columns` -> `NDFrame._reindex_with_indexers`. And this at long last calls `self._constructor` with a block manager for the multindex containing the geometry as its sole argument, roughly
```python
new_data = 
Items: MultiIndex([('geometry', '')],
           )
Axis 1: RangeIndex(start=0, stop=2, step=1)
ExtensionBlock: slice(0, 1, 1), 1 x 2, dtype: geometry
self._constructor(new_data)
```
So that's part one... This calls the the geodataframe init, and the whole thing begins again when the geometry column is queried:
https://github.com/geopandas/geopandas/blob/cb88dd4a9100bb990f6eb9b286e1ef3a0b185e3c/geopandas/geodataframe.py#L123-L127
The tour goes `GeoDataFrame.__getitem__()` ->  `DataFrame.__getitem__()` -> `DataFrame._getitem_multilevel()`, and this time around `self._is_mixed_type` is false, and the else block fires:
```python
    def _getitem_multilevel(self, key):
        # self.columns is a MultiIndex
        loc = self.columns.get_loc(key)
        if isinstance(loc, (slice, np.ndarray)):
            new_columns = self.columns[loc]
            result_columns = maybe_droplevels(new_columns, key)
            if self._is_mixed_type:
                result = self.reindex(columns=new_columns)
                result.columns = result_columns
            else:
                new_values = self.values[:, loc]
                result = self._constructor(
                    new_values, index=self.index, columns=result_columns
                )
                result = result.__finalize__(self)
``` 
(https://github.com/pandas-dev/pandas/blob/bf157517d08914e2cbaa7a0bf975952e303dd43e/pandas/core/frame.py#L3504-L3518)
Here is the first place the crs gets lost (I think, wouldn't be surprised if there's an error in the above, it's been pretty tricky to follow)
`new_values = self.values[:, loc]` creates the full ndarray for the dataframe, so a GeometryArray isn't created and the crs is lost in the next call to constructor. 

At this point, I've got no idea how this can be fixed. There might be a hack fix along the lines of `GeoDataFrame._constructor = functools.partial(GeoDataFrame, crs=self._crs)` but this seems flakey and error prone. 

If `new_values = self[:, loc].values` then a GeometryArray would be returned and the crs would flow to the constructor (and appears to actually propagate the crs in this case - albeit tested by editing the source of my environment to check, I don't have a develop install of pandas itself setup). There's probably a good reason for doing the operation in the order it's done though.
