### ISSUE TITLE
ENH: Return make_valid to overlay and use to skip the buffer(0) calls

### ISSUE THREAD

**Issue by bretttully** [geopandas/geopandas#1799]
In https://github.com/geopandas/geopandas/pull/1553 `make_valid` was removed. However, in our code the unexpected calls to `buffer(0)` exposed this bug in GEOS https://github.com/Toblerity/Shapely/issues/1069. 

I propose `make_valid=True` is restored and the `buffer(0)` calls are skipped if `make_valid=False`. In this case documentation could warm the user to ensure that geometries are valid before the call.

**Comment by martinfleis** [comment]
I am afraid we need them until `make_valid` is exposed in shapely. The operations within overlay have a tendency to create invalid geometries. 

We may skip those two on input here https://github.com/geopandas/geopandas/blob/27d07dd15aa24224c9141b2e7e851e7eb9e87319/geopandas/tools/overlay.py#L203-L206

But I am not sure if it is going to help much in the case you linked above since buffer(0) will be applied later anyway.

**Comment by bretttully** [comment]
Thanks for the response. Interestingly, it was the `buffer(0)` calls before the intersection operation that you linked that discovered the bug reported above. If we called the private `_overlay_intersection` method, the results in this particular case for what we were doing we're fine. I appreciate that might not generalise.

Is there a way to make L203-206 optional? `preprocess_make_valid=False`?

**Comment by martinfleis** [comment]
Long-term, we would probably want to replace `buffer(0)` with `make_valid()`, therefore having a keyword like `make_valid=True` or `validate=True` seems to be reasonable. We can reintroduce `make_valid` and use it here to control whether these four lines are skipped or not.

Would you like to propose that as a PR? It will need a test starting with some invalid geometry probably (like a bowtie).

**Comment by bretttully** [comment]
I'll take a look at a PR over the next few days

**Comment by bretttully** [comment]
@martinfleis Please see here: https://github.com/geopandas/geopandas/pull/1802
