### ISSUE TITLE
REF: Lazy load CRS from WKT string

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#1842]
`pyproj.CRS` objects aren't meant to be shared across threads, but they can exist if created within the thread ([ref](https://pyproj4.github.io/pyproj/stable/advanced_examples.html#multithreading)). Sharing the same CRS object across threads so can cause issues ([ref](https://github.com/pyproj4/pyproj/issues/589)).

This has an impact on using geopandas with dask ([ref](https://github.com/corteva/geocube/issues/41))

One potential solution is to store the WKT string for the CRS on the geopandas geodataframe as the `_crs` property and then construct the `pyproj.CRS` object when the `crs` property is requested.

Thoughts?

**Comment by martinfleis** [comment]
Interesting. The changes on master probably don't fix this right? The move of CRS to `GeometryArray`.

> One potential solution is to store the WKT string for the CRS

Yes, that sounds like a reasonable solution. Note that all this has to happen on `GeometryArray` level, not on `GeoDataFrame` https://github.com/geopandas/geopandas/blob/4444f1adb6e1bc2c6aaedc87be2b5627e7061799/geopandas/array.py#L337

**Comment by snowman2** [comment]
> The changes on master probably don't fix this right?

Unfortunately no. The CRS object is still shared across threads.

Another thing that should be taken into account with the design is that re-creating CRS objects does take time (https://github.com/pyproj4/pyproj/issues/661).

With this in mind, I had a couple of ideas:

1. Add a `crs_wkt` property like the one Fiona has and leave the `crs` property alone. This could be used be external applications. The downside of this is that any internal usage of `crs` in geopandas will still have issues.
2. Have a `crs_uuid` for each `GeometryArray` in each thread. Then, if the CRS object hasn't been created yet, it will add it to a dict of geopandas CRS stored on each thread. This will make it thread safe and reduce the number of times the CRS object is created.

**Comment by martinfleis** [comment]
> Add a crs_wkt property like the one Fiona has and leave the crs property alone. This could be used be external applications. The downside of this is that any internal usage of crs in geopandas will still have issues.

I'd prefer to have a fix that works out of the box, so you don't need to figure out that you need to access `crs_wkt` instead of `crs` if you're multithreading.

> Another thing that should be taken into account with the design is that re-creating CRS objects does take time (pyproj4/pyproj#661).

How big of a problem it is? I see that there was some slowdown initially and then speedups later. Because that seems to be the cleanest solution to create CRS on request, unless it will have a significant impact on performance.

**Comment by snowman2** [comment]
> I'd prefer to have a fix that works out of the box, so you don't need to figure out that you need to access crs_wkt instead of crs if you're multithreading.

I agree. I have a solution I am working on using `threading.local` to store the CRS on the dataframe. I need to test it out multithreading, but seems to be stable on single threaded applications.

> How big of a problem it is? I see that there was some slowdown initially and then speedups later.

Unfortunately, the speedups are for single threaded applications only. The slowdown can be significant for repeated operations: 
https://github.com/corteva/rioxarray/discussions/234.

**Comment by jorisvandenbossche** [comment]
Is every usage of a CRS object in a threaded application unsafe? Or only certain methods? 

What I thought before (assuming doing a parallel `to_crs` conversion): because in each thread we create a thread-local Transformer that performs the actual coordinate transformation, this is safe to do. 
But is actually creating this Transformer from 2 CRS objects already unsafe?

**Comment by snowman2** [comment]
> Is every usage of a CRS object in a threaded application unsafe? Or only certain methods?

It is only safe if it was created in the thread. Otherwise it may or may not work. As mentioned in https://github.com/corteva/geocube/issues/41, it is only an issue when there are many threads sharing the same CRS (i.e. large raster).

> But is actually creating this Transformer from 2 CRS objects already unsafe?

This is likely okay because no C methods are called. It uses the `srs` attribute [ref](https://github.com/pyproj4/pyproj/blob/6b860dec5db6612328b7adffc0bddb0386101c38/pyproj/_transformer.pyx#L348-L349).

**Comment by jorisvandenbossche** [comment]
Personally, I have the feeling this is something that ideally should be solved in pyproj itself (just a feeling, didn't think it through technically ;)) 

Because now, with pyproj.CRS object not being thread-safe, every user of pyproj will need to be aware of this. Every package that relies on pyproj for representing CRS will need to do something similar to what you propose here for geopandas. 

The `threading.local` trick, is that something that you could use in pyproj as well? (eg make the cython class that holds the actual proj context thread local, and the python CRS class could use composition (have that as an attribute) instead of inheritance; this might be a substantial change, though ..)

**Comment by snowman2** [comment]
> The threading.local trick, is that something that you could use in pyproj as well?

This is something that I have thought about for a while. I haven't attempted it because of concerns about stability.

> Every package that relies on pyproj for representing CRS will need to do something similar to what you propose here for geopandas.

That is true. If they want to be backwards compatible, they will need to do this.

**Comment by snowman2** [comment]
https://github.com/pyproj4/pyproj/issues/782

**Comment by snowman2** [comment]
> The threading.local trick, is that something that you could use in pyproj as well?

Documented what would need to change in https://github.com/pyproj4/pyproj/issues/782. Seems like it is not something that can happen in `pyproj`. Something like #1846 seems like the way things have to be for now.

**Comment by snowman2** [comment]
Actually, I think there is a way forward to implement this in `pyproj` :crossed_fingers:

**Comment by snowman2** [comment]
Going to close for preference to the idea from @jorisvandenbossche.
