### ISSUE TITLE
BUG: .to_wkt() gives different decimals places as data going in

### ISSUE THREAD

**Issue by raybellwaves** [geopandas/geopandas#1927]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
import pandas as pd

lon = -64.11181
lat = 1
expected_wkt = "POINT ({} {})".format(lon, lat)

s = pd.Series(expected_wkt)
gs = gpd.GeoSeries.from_wkt(s)

actual_wkt = gs.to_wkt().values[0]

assert expected_wkt == actual_wkt # -> AssertionError
print(expected_wkt) # -> POINT (-64.11181 1)
print(actual_wkt) # -> POINT (-64.11181000000001 1)
```

#### Problem description

I was creating a key to join on using wkt. I was later using wkt from the geometry and I realized things didn't match up.

#### Expected Output

Roundtrips correctly without truncations issues.

#### Output of ``geopandas.show_versions()``

<details>

Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`

SYSTEM INFO
-----------
python     : 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)  [Clang 11.0.1 ]
executable : /Users/Ray/miniconda3/envs/test_env/bin/python
machine    : macOS-10.15.7-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.2.2
GDAL data dir: /Users/Ray/miniconda3/envs/test_env/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 7.2.1
PROJ data dir: /Users/Ray/miniconda3/envs/test_env/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0+17.gb436ac2
pandas     : 1.2.4
fiona      : 1.8.19
numpy      : 1.20.2
shapely    : 1.7.1
rtree      : None
pyproj     : 3.0.1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Thanks for the report.

I can confirm this behaviour when depending on shapely, which doesn't allow any control over the WKT output, leading to this expression of the floating point error.

With pygeos backend, you can actually directly control how to export WKT (see https://pygeos.readthedocs.io/en/latest/io.html#pygeos.io.to_wkt) and enforce the correct output in this case with `actual_wkt = gs.to_wkt(rounding_precision=7).values[0]`. In any case, I don't think that there's an actual way to always return the same value as was given because the WKT string on input gets converted to float encoding coordinates (and therefore can result in the floating point error).

In any case, there's nothing we can do about this in GeoPandas I am afraid.

**Comment by raybellwaves** [comment]
closing in favor or https://github.com/Toblerity/Shapely/issues/1132
