### ISSUE TITLE
BUG: GeoDataFrame.crs not updated if geometry GeoSeries is reprojected manually

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1960]
Consider following example.

```py
gdf = geopandas.read_file(geopandas.datasets.get_path("nybb"))
gdf.crs

<Projected CRS: EPSG:2263>
...

gdf["geometry"] = gdf.geometry.to_crs(4326)
gdf.crs

<Projected CRS: EPSG:2263>
...
```

GeoDataFrame doesn't load the CRS of its active geometry column if it is re-projected in this way. Assigning re-projected GeoSeries as an attribute (`gdf.geometry = gdf.geometry.to_crs(4326)`) works as expected.

`gdf.crs` should directly return the CRS of the active geometry column in this case.

**Comment by jorisvandenbossche** [comment]
> Assigning re-projected GeoSeries as an attribute (`gdf.geometry = gdf.geometry.to_crs(4326)`) works as expected.

The reason that this way it works is that this (the `geometry` property setter) uses `set_geometry` under the hood, and this method sets `_crs`.

But indeed, we should probably have `.crs` return `self.geometry.values.crs` if an active geometry column is available, and only otherwise return `_crs`? (if I remember correctly, we have the `_crs` to allow having a GeoDataFrame with a crs without geometry column?)

**Comment by Imanflow** [comment]
> if I remember correctly, we have the _crs to allow having a GeoDataFrame with a crs without geometry column?)

I think it's now allowed but was going to be deprecated (If i understood you correctly and we talk about the same) 

```
import geopandas as gpd
from pyproj import CRS
a = gpd.GeoDataFrame(crs=CRS(4326))
<input>:1: FutureWarning: Assigning CRS to a GeoDataFrame without a geometry column is now deprecated and will not be supported in the future.
```
