### ISSUE TITLE
Pass plot kwargs to matplotlib commands

### ISSUE THREAD

**Issue by kjordahl** [geopandas/geopandas#204]
The plot functions don't pass kwargs to matplotlib.

For example, it would be nice to be able to use `df.plot(figsize=(10, 10))` to change output size, especially in the notebook. Currently, all kwargs to `plot_dataframe()` are assumed to be color arguments that are ultimately only options to `plot_multipolygon()`.

**Comment by ozak** [comment]
Hi Kelsey,
it seems the color functions do not work properly(?). If one tries ``df.plot(facecolor='white')`` or any other color it produces an error ``TypeError: plot_multipolygon() got multiple values for keyword argument 'facecolor'``. Was this supposed to work? Or is this what you are referring to in this issue?

**Comment by ozak** [comment]
FYI, I also tried playing with the ``markersize`` for points and it does not seem to work.

It seems the problem is that the functions being called by ``plot_dataframe`` have default values which are not being updated (for markers at least seems to be the case).

**Comment by darribas** [comment]
Related to this question, is there any way in geopandas to tweak (either before passing to the Descartes plotting machinery, or once it's been appended to the axis) some of the attributes, like the linewidth, the color, etc.?

**Comment by darribas** [comment]
I've issued a PR to solve the problems raised by @ozak. In the PR, both `plot_series` and `plot_dataframe` can take a fixed `facecolor` argument, and points can also be specified further. All tests pass locally.

**Comment by IamJeffG** [comment]
`facecolor` in particular is an interesting case because I feel it directly conflicts with the top-level `color` (or `column`) parameter on `plot_series` and `plot_dataframe`.  Current behavior:

* If I pass one or the other (not both), they have the same semantics.
    - However I suspect `legend=True` will only pick up `color`, not `facecolor`.
* If both are specified, `facecolor` will override `color` without a warning.
* If `facecolor` is passed when the GeoSeries contains points or lines, you get `TypeError: There is no Line2D property "facecolor"`

I believe that we should be pushing clients away from `facecolor` and toward `color` (or `column`) because it has semantics for all geometry types, whereas `facecolor` is ignored for lines and points.  Documenting this will also resolve the ambiguity for legends.  Something like this:

    if 'facecolor' in color_kwds:
        warnings.warn("'facecolor' is deprecated, please use 'color' instead "
                      "(for consistency across geometry types)", FutureWarning)
        color = color_kwds.pop('facecolor') if not color else color

**Comment by jorisvandenbossche** [comment]
@IamJeffG for plotting points (at least when using a collection), `facecolor` has a clear meaning I think. Personally, I think I would towards using matplotlibs Collections terminology, where they use `facecolor` and `edgecolor`, and `color` is an alias depending on the type of collection.

**Comment by IamJeffG** [comment]
I agree this makes sense on the surface, though we may have a tough time of it.  Here are some oddities discovered while I was working on adding some tests:

- By your logic, when `color` is set, will polygons lose their black outline? This makes adjacent polys indistinguishable.
- `color` will need to override facecolor, rather than (current behavior) the other way around.
- In a LineCollection, setting `facecolor` is the way you make it "filled", i.e. it will color the area inside line shapes (making it look like a polygon instead).  Do we want this?
- On Collections the appropriate keyword is `fillcolors`, not `fillcolor`.  (though I think I'm noticing inconsistent support for `fillcolor` in some collection subclasses?)

All these can be worked around, but with quite a lot of effort, I'm finding.  I am not opposed to keeping `facecolor`, but I'm trying to understand the benefit tradeoff.

**Comment by jorisvandenbossche** [comment]
>    By your logic, when color is set, will polygons lose their black outline? This makes adjacent polys indistinguishable.

Yes, that would then be the definition of color, that it sets both edgecolor and facecolor. If you only want to set the facecolor, you can use that one. 
Of course, this one is change from the current behaviour (and it is maybe a less intuitive behaviour), so we could think to deviate here from the matplotlib api.

>    color will need to override facecolor, rather than (current behavior) the other way around.

Why is that needed? (but indeed, now precendence goes to facecolor and edgecolor if they are specified and color is ignored, which actually makes sense to me as they are more specific)

>    In a LineCollection, setting facecolor is the way you make it "filled", i.e. it will color the area inside line shapes (making it look like a polygon instead). Do we want this?

Ah, I didn't know that. If you *want* that, nothing wrong with being able to do it? But in most cases you will just specify edgecolor or color and not bother about facecolor when plotting lines? 
I suppose the only problem appears when you have a heterogeneous series with different geometry types, where you want to set the facecolor of a polygon, but not that of a linecolor. But, I personally wouldn't focus on this use case too much, and you can always pass an array of facecolors to set the facecolor for each individual element of the collection manually.

>    On Collections the appropriate keyword is fillcolors, not fillcolor. (though I think I'm noticing inconsistent support for fillcolor in some collection subclasses?)

Which keyword do you mean? The matplotlib Collections api docs don't speak about a fillcolor?

> All these can be worked around, but with quite a lot of effort, I'm finding. I am not opposed to keeping facecolor, but I'm trying to understand the benefit tradeoff.

What I propose is rather to provide *no* workarounds, and to leave this just to matplotlib. And as I understand it, not providing `facecolor` but gearing people to `color` will need some extra code to pass the correct keyword to matplotlib. 
In your idea, would `color` set the `facecolor` for points and polygons, and the `edgecolor`/`color` for lines?

**Comment by jorisvandenbossche** [comment]
@IamJeffG I think the items you listed in the previous post (https://github.com/geopandas/geopandas/issues/204#issuecomment-170365606, facolor raising a TypeError, being ignored if legend=True, ..), they are for the current implementation? And I think they will be solved when switching to using collections?

**Comment by IamJeffG** [comment]
>  facolor raising a TypeError ... they are for the current implementation?

Yes this would be fixed using Collections.

> legend=True will only pick up color, not facecolor

This comment applied to the current implementation. With Collections, a fourth option is introduced, `array`, and the colorbar will always use the `array` and ignore color and facecolor.  (This is very logical.)

> > color will need to override facecolor, rather than (current behavior) the other way around.

> Why is that needed?

My mistake. In matplotlib.collection `color` sets both `facecolor` and `edgecolor`, which I thought would imply that it overrides them as well.  If you set both `facecolor` and `color`, `facecolor` wins.  Same is not always true for `edgecolor` and `color`: see my gist below.

> > On Collections the appropriate keyword is fillcolors, not fillcolor. (though I think I'm noticing inconsistent support for fillcolor in some collection subclasses?)

> Which keyword do you mean? The matplotlib Collections api docs don't speak about a fillcolor?

Sorry; I meant to say "the appropriate keyword is `facecolors`, not `facecolor`."  And again I was mistaken: going from the documentation, `facecolor` (singular) is not documented as a consructor kwarg, but does happen to work.

--

Clearly, digging through the collections docs got me confused, so I made a gist to brute force all the combinations of these kwargs to really prove how things work:
https://gist.github.com/IamJeffG/2bf37498a79e7aa93ee5

Currently geopandas uses `color` in more or less the same way as `column` (i.e. matpotlib.collection's `array`), in the sense that you set one or the other (not both) and the shapes get colored accordingly. It turns out the two kwargs have different behavior with respect to default edgecolors and also to how they interact with other arguments `facecolor` and `edgecolor` when present.  This surprised me, but it's not a huge deal; we may just have to live with the inconsistency.

From this gist, I've come to agree that always passing `color`, `facecolor` and `edgecolor` directly to matplotlib collections, usually makes sense (or at least, it _will_ make sense with Collections)!
