### ISSUE TITLE
GeoParquet assign Metadata

### ISSUE THREAD

**Issue by aw-west-defra** [geopandas/geopandas#2245]
https://github.com/geopandas/geopandas/blob/4361c30f474df0751a7006e0d91f3fc8376b723c/geopandas/io/arrow.py#L299

I have a file I want to read with a wkb geometry column.
But it was written to parquet without any geo metadata.

Since I know this metadata, it would be nice to be able to pass it through.  e.g:
`gdf = gpd.read_parquet(filename, primary_column='geometry', crs='epsg:4326', encoding='WKB')`

> My current work around is this:
> ```
> df = pd.read_parquet(filename)
> gdf = gpd.GeoDataFrame(df)
> gdf.geometry = gpd.GeoSeries.from_wkb(gdf.geometry)
> gdf.set_crs(epsg=4326)
> ```

**Comment by brendan-ward** [comment]
My preference would be that we do not introduce multiple sources of truth for these values (parameters vs metadata), as that makes the underlying implementation more complex.

I think since you have a work-around for your specific example, and since that is accomplished in just a few lines of code, to not add this support to `read_parquet`, and instead leave `read_parquet` as the implementation for reading files output by GeoPandas using `write_parquet` rather than extending it to allow arbitrary parquet files.

**Comment by martinfleis** [comment]
I agree with @brendan-ward here. Especially since that workaround can be written as

```py
df = pd.read_parquet(filename)
gdf = gpd.GeoDataFrame(df, geometry=gpd.GeoSeries.from_wkb(df["geometry"], crs=4326))
```

**Comment by aw-west-defra** [comment]
Thanks 👍
