### ISSUE TITLE
QST: When is GEOS version really incompatible?

### ISSUE THREAD

**Issue by dazza-codes** [geopandas/geopandas#2355]
```
>>> import geopandas
/opt/conda/envs/gis/lib/python3.7/site-packages/geopandas/_compat.py:115: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string
>>> geopandas.show_versions()

SYSTEM INFO
-----------
python     : 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0]
executable : /opt/conda/envs/gis/bin/python
machine    : Linux-5.4.0-99-generic-x86_64-with-debian-bullseye-sid

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.3.0
GDAL data dir: /opt/conda/envs/gis/lib/python3.7/site-packages/fiona/gdal_data
PROJ       : 7.0.1
PROJ data dir: /opt/conda/envs/gis/lib/python3.7/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.5
fiona      : 1.8.20
numpy      : 1.21.1
shapely    : 1.8.1
rtree      : 0.9.7
pyproj     : 2.6.1.post1
matplotlib : 3.5.1
mapclassify: None
geopy      : 2.2.0
psycopg2   : 2.9.3 (dt dec pq3 ext lo64)
geoalchemy2: 0.8.5
pyarrow    : 3.0.0
pygeos     : 0.12.0

```

Shapely GEOS version (3.10.2-CAPI-1.16.0) 
PyGEOS GEOS version (3.10.1-CAPI-1.16.0)

These versions are only 1 patch level apart - are they _really_ incompatible?

Could the geopandas warning allow these versions to be only one patch version apart and consider that OK?  Surely a patch version of difference is not significant.

Until shapely 2.0 is released, is it possible to pin shapely and pygeos to compatible package versions that use compatible GEOS versions?

**Comment by jorisvandenbossche** [comment]
> These versions are only 1 patch level apart - are they really incompatible?

Unfortunately yes. This is about actual binary compatibility, because we are passing pointers to the geometry structs in memory. So actually this is only robust when really using the same library, and not only the same version. With using conda, you can ensure that pygeos and shapely use the exact same library, but when using wheels both pygeos and shapely will include their own GEOS version in the wheel. Even when those two GEOS versions have the exact same version, there can occur rare but strange bugs (see eg https://github.com/geopandas/geopandas/issues/2198)
