### ISSUE TITLE
TST: CI failures with PROJ 9.0.0

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2388]
Since PROJ 9.0.0, our CI is reporting failures across environments due to some changes in precision during transformation. See the report https://github.com/geopandas/geopandas/runs/5504631593?check_suite_focus=true. 

I didn't have time to debug this but we should have a look what is happening and likely adapt CI, if it is not caused by some underlying issue.

**Comment by jorisvandenbossche** [comment]
I am looking a bit into this, and it seems this is due to that fact that setting `PROJ_NETWORK` to "OFF" stopped working. Now, I don't know if that was ever really supposed to work (the documentation only mentions about setting it to "ON", although one might expect that you can then also set it to "OFF"):

```
In [1]: import os
   ...: os.environ["PROJ_NETWORK"] = "OFF"
   ...: 
   ...: import pyproj
   ...: print(pyproj.proj_version_str)
   ...: pyproj.network.is_network_enabled()
   ...: 
8.2.0
Out[1]: False
```

vs

```
In [1]: import os
   ...: os.environ["PROJ_NETWORK"] = "OFF"
   ...: 
   ...: import pyproj
   ...: print(pyproj.proj_version_str)
   ...: pyproj.network.is_network_enabled()
9.0.0
Out[1]: True
```

Maybe related to the changes in https://github.com/OSGeo/PROJ/pull/3049? cc @snowman2 @rouault

**Comment by jorisvandenbossche** [comment]
Actually, the above observation is caused by my IPython config where I already do some imports by default (including geopandas). So doing the above in a clean python env, that still gives False for PROJ 9.0.0. 

But so the correct observation of what changed in behaviour, is that setting the env variable _after importing pyproj_ no longer has effect:

```python
>>> import os
>>> import pyproj
>>> pyproj.proj_version_str
'8.2.0'
>>> os.environ["PROJ_NETWORK"] = "OFF"
>>> pyproj.network.is_network_enabled()
False
```

vs

```python
>>> import os
>>> import pyproj
>>> pyproj.proj_version_str
'9.0.0'
>>> os.environ["PROJ_NETWORK"] = "OFF"
>>> pyproj.network.is_network_enabled()
True
```

**Comment by rouault** [comment]
This is certainly due to https://github.com/OSGeo/PROJ/pull/3049 , but I don't consider that as a regression. Basically the effect of changing the value of PROJ_NETWORK after a PROJ context has been created is unspecified. Safer is to use set_network_enabled(False) as you did in https://github.com/geopandas/geopandas/pull/2397

**Comment by jorisvandenbossche** [comment]
> but I don't consider that as a regression

Yep, after realizing it was only for the case after import pyproj (which initializes a context), fully agreed that this should not be expected to work.
