### ISSUE TITLE
QST: Release & Issue Management

### ISSUE THREAD

**Issue by kai-tub** [geopandas/geopandas#2457]
Hey, I can't help but notice that there hasn't been a patch release for quite some time and this particular issue (#2367 and #2271) has caused a bit of friction, as I've seen others stumble over this issue.
I am very happy that this library exists and love using it. I would like to depend on this library for a project that uses geopandas internally, should be reproducible (i.e., linked to a specific version), and maybe published to conda-forge.
For these (and other reasons) I am not comfortable using the main branch.

I understand that releases produce a lot of additional work and can be frustrating to manage.
I would like to propose two different "ideas" and would like to get your feedback:

## Continuous Delivery

Maybe it is possible to automate the release process or parts of it?
It would already be quite helpful if the 'bug fixes' get merged and released sooner.
The project has quite a high test coverage and if new contributions always include tests, I think that these automatic releases _could_ be done relatively safely.
The work that is required to draft a release would be put much closer to the actual issue/fix and not be accumulated into a single large project.
You could argue that the frequent updates could cause package versions to be broken in production if a test case was missed, but I would argue that it would be a lot easier to write another follow-up patch since not a lot of time has passed since the "breaking" release. If releases are done rather infrequently it may be hard to remember the details of a change.

The tool that I am using, and could help with, is [auto](https://intuit.github.io/auto/).
It can be easily integrated into a GitHub action pipeline to automatically trigger a release whenever a PR with a specific label is merged.

Of course, it is easy for me to say, as I do not have a project that is this large and popular.
Also, it may require a different branch structure and adds more complexity if 'only' patches should be automatically released but nothing else.

Either way, I am happy to discuss CD (or alternative tools) in more detail if you'd like.

An alternative that would also be quite helpful:

## Defensive documentation

The issue I've linked to has been known for some time and was fixed in main before I stumbled over the issue and spend some time looking at the wrong places and _re-discovering_ the issue.
If a new issue is found and fixed on the main branch, it could be very helpful to add quick notes on the documentation page and link to "known issues" with the function and that they will be fixed in an upcoming release.
Maybe you could label these types of issues (those that require a link inside of the documentation) and create a TODO list so that other contributors can take care of adding them to the documentation (I would be happy to help!).

Again, thank you for working on such a valuable library and I hope that you see my comments from the perspective of a user that only wants to make this library _more awesome_ :)

**Comment by kai-tub** [comment]
Ups, I've missed #2444.
Please do not interpret the first paragraph as a "negative comment" but as a reasoning process for why I felt motivated to add these suggestions :)

**Comment by martinfleis** [comment]
Hi, thanks for the ideas!

I understand the frustration with the slow release rate. We have repeatedly agreed internally that we should release more often but it always fails on the same issue - time. None of the maintainers is funded to do the maintenance of geopandas and I personally had significantly less time to dedicate to it in the past months than I had before. We simply do not have enough capacity to ensure that PRs are properly reviewed in time, questions are answered, bugs are fixed and patch releases are ready to be released. We are aware of the situation but it is not easy to change it.

On the actual suggestions:

Our release process is pretty much automatised already but we often deal with more complex issues in a series of PRs, so that is one thing to look for when releasing. We use semantic versioning, which means that when we merge two PRs, one with a new method and other with a bug fix, we cannot simply release main version as a a patch release. Therefore when doing them, we need to back port bug fixes from main onto a separate branch to ensure that no new functionality or deprecation is introduced in a patch release but always in a minor or major release.

The documentation suggestion brings additional maintenance cost I'd like to avoid and does not really solve the issue for most people because the documentation on `geopandas.org` points at the latest stable release. So when we would add a note on "known issues", it would not show up there. It would render only in the latest version, which is not default and very little people actually use it.

We are trying to resolve the situation with maintenance capacity and it may become better from July onwards but we cannot promise anything.

**Comment by kai-tub** [comment]
Thank you for your quick reply!
I fully understand the limited resources for open source projects that are maintained by individuals.

> Our release process is pretty much automatised already but we often deal with more complex issues in a series of PRs, so that is one thing to look for when releasing. We use semantic versioning, which means that when we merge two PRs, one with a new method and other with a bug fix, we cannot simply release main version as a a patch release. Therefore when doing them, we need to back port bug fixes from main onto a separate branch to ensure that no new functionality or deprecation is introduced in a patch release but always in a minor or major release.

I see. Yes, it would require having a single develop branch that includes the long-running tasks and merging patches to main and syncing them back to develop with the additional synchronization overhead.
I can see that it becomes too unwieldy with longer running PRs that touch on multiple things.

> The documentation suggestion brings additional maintenance cost I'd like to avoid and does not really solve the issue for most people because the documentation on geopandas.org points at the latest stable release. So when we would add a note on "known issues", it would not show up there. It would render only in the latest version, which is not default and very little people actually use it.

Ah, ok. I wasn't aware that geopandas.org points to the latest stable release.

Again, I am thankful for the work on this project and do not 'expect' anything.
I wanted to hear your thoughts about the suggestions, which I did :)

Thank you.
