### ISSUE TITLE
QST:How to limit digits when read data from shapefiles with geopandas？

### ISSUE THREAD

**Issue by forestbat** [geopandas/geopandas#2513]
I'm using GIS data which length unit is degree，such as 

> (124.32136460574809, 43.595302060916815) # longitude and latitude

You can see the coord has 14 digits behind its decimal dots. This is enough "exact"，however too many digits will bring error and it has suffered me for a long time.

So how to limit digits of coords when read from .shp file like this：

> (124.3213646, 43.59530206) # It has only 7 digits

Thank you for very much.

**Comment by brendan-ward** [comment]
@forestbat if the question is how to read geometries from a shapefile using a fixed precision, I don't believe there is a direct way to do that using Fiona or Pyogrio engines.

Once geometries are read into a GeoDataFrame, they are stored in GEOS geometries which use double (64 bit) floating point values for storing coordinates.  This does indeed mean that the coordinates can store greater precision than is actually present within the shapely, it really depends on what the data processing steps were prior to creating the shapefile you are using.

Once you have geometries, there are probably a few options (note: did not test these):
* use [set_precision](https://pygeos.readthedocs.io/en/stable/geometry.html#pygeos.geometry.set_precision) using pygeos to snap geometry coordinates to a fixed precision grid; this can produce valid geometries but may modify geometry types in the process of doing so.
* [convert to WKT](https://pygeos.readthedocs.io/en/stable/io.html#pygeos.io.to_wkt) using pygeos with a fixed rounding precision:  (which just truncates decimal places) then convert back to geometries.  However, note that once you convert them back they are stored in doubles, so they will show more precision than your rounding precision
* use pygeos [apply](https://pygeos.readthedocs.io/en/stable/coordinates.html#pygeos.coordinates.apply) function then round coordinates in the transformation function
* [extract coordinates into numpy arrays](https://pygeos.readthedocs.io/en/stable/coordinates.html#pygeos.coordinates.get_coordinates), round them using numpy, then reconstruct your geometries; this option is more involved because there are different functions to call for reconstructing each geometry type

To do any of these, you need to have `pygeos` installed.  You can obtain the numpy array of pygeos geometries of the `geometry` column of your data frame by `gdf.geometry.values.data`.

Warning: anything other than `set_precision` may produce invalid geometries due to loss of precision; there may be self-intersections, overlaps, etc.

**Comment by forestbat** [comment]
@brendan-ward Thank for your reply，now I want to try mapshaper to do with my GIS data，and I will also consider your answer.
