### ISSUE TITLE
CI: incompatibility between numpy 1.23 and shapely 1.7.1

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2514]
38-latest-defaults.yaml started resolving with the new numpy 1.23.1 but is still using shapely 1.7.1, causing failures on our CI. Shapely 1.8 is fine with new numpy. Not sure if there's much we can do apart from pinning to older numpy here or installing shapely from PyPI.

**Comment by jorisvandenbossche** [comment]
No, we just have to pin to older numpy for old shapely. There were updates in shapely 1.8 to deal with numpy deprecations, so I think this is expected.

**Comment by jorisvandenbossche** [comment]
(it also shows that the default channel of Anaconda is quite hopelessly behind .. since they are still on 1.7.1 as the latest version of shapely. Thus it will give problems for users that install using the default channel, unless they also pin numpy to an older version. I will maybe open an issue to ask to update Shapely)
