### ISSUE TITLE
Import error for "geopandas.tools overlay"

### ISSUE THREAD

**Issue by bidhya** [geopandas/geopandas#252]
Writing this import fails as follows:
from geopandas.tools import overlay
gives the following error,
ImportError: No module named tools

I am on windows7 with canopy python installation, with geopandas version '0.1.1'
Geopandas was installed with pip install method

**Comment by micahcochran** [comment]
It has been mentioned (#242) that the project needs to release a 0.2 version.

There have been a number of patches since 0.1.1.  I would recommend using the most recent development version.

Try this first:
`pip install -U git+https://github.com/geopandas/geopandas.git`

If that does work (you may not have git installed) then do the following:
1. Download the ZIP file.
2. Uncompress the ZIP file.
3. Change into `geopandas-master` the directory.
4. run `pip install -U .`

**Comment by kjordahl** [comment]
Indeed, geopandas 0.1.1 does not have a `tools` module.
