### ISSUE TITLE
Geopandas conda install UnsatisfiableError glibc

### ISSUE THREAD

**Issue by ebebpl** [geopandas/geopandas#2522]
This is a new anaconda3 installation on centos 7.9 and geopandas is not getting installed due to UnsatisfiableError.
$ conda --version is conda 4.13.0

Please see the discussion in the below link:
https://stackoverflow.com/questions/73297278/geopandas-conda-install-unsatisfiableerror-glibc/73309293#73309293

**Comment by jorisvandenbossche** [comment]
For issues with the Anaconda distribution or packages from the default channel, you can report something at https://github.com/ContinuumIO/anaconda-issues/issues (we don't have any control over that ourselves)

We typically recommend to use the conda-forge channel, because this has more up to date packages for geopandas and its dependencies. 
The safest and most robust way to do this is to create a new environment (not using the base environment from the anaconda install), using (https://geopandas.org/en/stable/getting_started/install.html#creating-a-new-environment):

```
conda create -n geo_env
conda activate geo_env
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install python=3 geopandas
```
