### ISSUE TITLE
API/COMPAT: unary_union behaviour with shapely 2.0

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2579]
shapely 2.0 will return GeometryCollection instead of None for empty result of unary_union (https://github.com/shapely/shapely/pull/1553). Do we want to override this to get a consistent behaviour of GeoPandas or do we want to propagate this change?

I am a bit unsure what is the best approach but I would rather override this now and follow shapely 2.0 in geopandas 1.0 or at least with some deprecation period, because this is a direct output of the geopandas method.

**Comment by jorisvandenbossche** [comment]
> to get a consistent behaviour of GeoPandas

You mean depending on whether you have pygeos installed or not?

**Comment by jorisvandenbossche** [comment]
Ah, no, we apparently customized shapely's behaviour .. I didn't check this when doing that change in shapely

https://github.com/geopandas/geopandas/blob/3993bd178abed309a75d1f79a80c325fd111ed7d/geopandas/_vectorized.py#L999-L1009

So because of this custom code, shapely <2 did actually return None as well, as you will get with pygeos. So it is only shapely >=2 that now gives something different.

**Comment by martinfleis** [comment]
Yeah, that's what I meant. I suppose we should ideally transition to empty collection as well. It makes more sense as a result than None. But I would do that gradually, hence overriding behaviour of shapely 2.0 as we do for shapely 1.7/8.

**Comment by jorisvandenbossche** [comment]
The deprecation was removed in https://github.com/geopandas/geopandas/pull/3007, and so will be enforced in 1.0. Thus this can be closed?
