### ISSUE TITLE
COMPAT: pandas numeric_ony dissolve()

### ISSUE THREAD

**Issue by rraymondgh** [geopandas/geopandas#2637]
#### Is your feature request related to a problem?

Currently in **ci** there are multiple warnings of the form:
```
geopandas/geopandas/geodataframe.py:1676: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
```

#### Solution

I see two approaches to extending `dissolve()`
1. add `egg_kwargs` argument
2. add `numeric_only`  argument that is then passed to `agg()` similar to other arguments that are passed to `groupby()`3. 

Obviously 2 also needs to consider other arguments - TBD.  I'm inclined to go with option 1.  Then test cases can be updated.  With agreed approach I'll code changes and update test cases.

#### API breaking implications

None

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
import itertools
import warnings

import pandas as pd

import geopandas as gpd
from geopandas import _compat as compat

print(gpd.__version__, pd.__version__)

self = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
by = "continent"
aggfunc = "mean"
as_index = True
level = None
sort = True
observed = False
dropna = True
agg_kwargs = {"numeric_only": None}

groupby_kwargs = dict(by=by, level=level, sort=sort, observed=observed, dropna=dropna)
if not compat.PANDAS_GE_11:
    groupby_kwargs.pop("dropna")

    if not dropna:  # If they passed a non-default dropna value
        warnings.warn("dropna kwarg is not supported for pandas < 1.1.0")

# Process non-spatial component
data = self.drop(labels=self.geometry.name, axis=1)
with warnings.catch_warnings():
    warnings.simplefilter("error")
    for aggfunc, num_only in itertools.product(["mean", "first"], [None, True]):
        agg_kwargs["numeric_only"] = num_only
        try:
            aggregated_data = data.groupby(**groupby_kwargs).agg(aggfunc, **agg_kwargs)
        except FutureWarning as e:
            print(aggfunc, num_only, e)

```

**Comment by m-richards** [comment]
I think it make sense to elaborate on the discussion here in this issue, rather than the already open pull request as there are a few conflating factors:
1. What to we do about the `numeric_only` future warning thrown in pandas 1.5.x, how do we make that make sense to users from the context of dissolve
2. How do we handle the change to the default value of `numeric_only` to False on the main branch of pandas - this is what is causing failures in ci.

I think it's instructive to compare the the pure pandas situation with the geopandas case (also because the pandas numeric_only deprecation applies in a number of places, but here we're concerned only with the context of groupby.agg). Here's an example (which coincidentally is rather similar to how `dissolve` is introduced in our docs [here](https://geopandas.org/en/stable/docs/user_guide/aggregation_with_dissolve.html)) showing the pandas 1.5 behaviour with the warnings. 

```python
import geopandas as gpd
import pandas as pd
gdf = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres")).drop(columns=['iso_a3', 'gdp_md_est'])
df = gdf.drop(columns=['geometry'])
```
If we look at groupby directly, or groupby.agg (which is what dissolve internally uses) we get this warning:
```python
print(df.groupby("continent").sum())
print(df.groupby("continent").agg("sum"))
FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. 
In a future version, numeric_only will default to False. 
Either specify numeric_only or select only columns which should be valid for the function.
```
Now, I don't think this is the most clear warning ever (I guess because it is issued from a generic place) but it can be silenced as the warning indicates by writing `df.groupby("continent").aggregate("sum", numeric_only=True)` or by slicing, `df.groupby("continent")[['pop_est']].aggregate("sum")` or slice before grouping, `df[['continent', 'pop_est']].groupby("continent").aggregate("sum")`.

Now to the geopandas case, dissolve behaves like `.groupby().agg()` with the additional handling of geometry, and so 
the same thing occurs for `gdf.dissolve("continent", aggfunc="sum")`, we get a warning referring specifically to `DataFrameGroupBy.sum` 

Currently it's possible to avoid this by slicing prior to dissolve, `gdf[['pop_est', 'geometry', 'continent']].dissolve("continent", aggfunc="sum")`. 

We should also expose a way to provide numeric only as a keyword arg - which is what @rraymondgh has articulated above. Personally I think adding a keyword arg to dissolve (`aggfunc_numeric_only`) makes the most sense as whilst providing aggfunc kwargs is more generic, I've never come across a situation where I have needed to pass other arguments to aggfunc (that's not to say they don't exist) and secondly, I think this is already a complicated enough warning to explain from the geopandas context without introducing a dictionary of parameters to feed through/ explain[^1]. 



We also need to consider the new default value of numeric only - in the future context of pandas 2/ our ci failing. I personally can't see a good idea why we would deviate from pandas on this. (Pragmatically also it's a bit tricky to do anything other than this as this new default value only applies to some agg funcs `sum, mean, idxmax, min, max..` but not say `first` and `last` - so unless we manually encode when to apply the default we can't handle this ourselves). For a similar reason we are also tied to change behaviour exactly with pandas 2, we can't easily extend the period for a breaking change if we wanted to.

Now, on the warning we should raise, my first draft would be something like:
`FutureWarning: The default treatment of non numeric columns in GeoDataFrame.dissolve for aggfunc={aggfunc} is deprecated as the default for numeric_only in DataFrame.groupby().agg(*args, numeric_only=None) in pandas is deprecated. In pandas 2.0, numeric_only will defautl to False. Either specific aggfunc_numeric_only in GeoDataFrame.dissolve or call dissolve on a geodataframe which should be valid for the aggfunc provided.`

This is already quite a wordy error, so it may even benefit by linking to docs in the warning message (similar to how is done for shapely 2).

I think it would be great to have some more input on the path forward here before implementing this / updating the existing PR.

[^1]: (it's tangential to this discussion, but if there are use cases requiring args to agg I think it's probably fair to call this an advanced use case, and provide recipe in an issue to handle this by doing a dissolve on the geometry only part, and  groupby on other fields, then aligning. If this came up commonly, we might want to think about how dissolve works as a whole - say if `.groupby("continent").agg({"pop_est":"sum", "geometry":"unary_union"})` worked.)

**Comment by m-richards** [comment]
@jorisvandenbossche or @martinfleis, do you have any thoughts on this?

**Comment by martinfleis** [comment]
What about simply exposing `**kwargs` that are directly passed onto `aggfunc`? Pandas [uses the same](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html?highlight=groupby%20agg) (alongside positional args but I'd ignore those). We then don't need to add a new keyword one our side and only capture the pandas warning and raise ours instead.

**Comment by m-richards** [comment]
> What about simply exposing `**kwargs` that are directly passed onto `aggfunc`? Pandas [uses the same](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html?highlight=groupby%20agg) (alongside positional args but I'd ignore those). We then don't need to add a new keyword one our side and only capture the pandas warning and raise ours instead.

I didn't consider this originally because it might not be super clear whether kwargs go into `groupby` or `agg` from disolve. But looking at our implementation again, that does seem like a decent option as we already explicitly specify the arguments which go to `groupby`. (There are some keys to groupby that we don't support, maybe that will be confusing in the future but that's probably another issue down the track).
