### ISSUE TITLE
BUG: pd.concat crs warning when geometry column is missing from one of the arguments

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#2679]
@martinfleis thanks for the quick reply, it took me a while but I think I found the problem, it's not directly related I guess but it comes from my use of ``sjoin_nearest`` with saved geometries.

The shortest MWE I could come up with was:

```python
import osmnx as ox
import pandas as pd

area = ox.geocode_to_gdf("Ivry-sur-Seine, France").iloc[0].geometry

landuse = ox.geometries_from_polygon(area, tags={"landuse": "commercial"})

buildings = ox.geometries_from_polygon(area, tags={"building": "retail"})

buildings["savedgeom"] = buildings.geometry

nearest = landuse.to_crs('+proj=cea').sjoin_nearest(buildings.to_crs('+proj=cea'))

nearest["geometry"] = nearest["savedgeom"]
del nearest["savedgeom"]

nearest = nearest.to_crs(landuse.crs)

print(buildings.crs, nearest.crs)

pd.concat([nearest, buildings])
```

_Originally posted by @tfardet in https://github.com/geopandas/geopandas/issues/2606#issuecomment-1325571377_
 
---------------------------------------
I've just moved this to a separate issue so it is easier to track / refer to as it does describe a bug.
A minimal reproducer is
```python
import pandas as pd

import geopandas as gpd
gdf = gpd.read_file(gpd.datasets.get_path("nybb"))
print(gdf.crs)
gdf = gdf.assign(geom=gdf.geometry)
pd.concat([gdf[['geometry']],gdf[['geom', 'geometry']]] )

```

**Comment by jorisvandenbossche** [comment]
@martinfleis's explanation at https://github.com/geopandas/geopandas/issues/2606#issuecomment-1325589448 is correct. Because that column is missing for one of the dataframes, it makes an all-NA array of the correct dtype to concatenate with the actual geometry array. And thus that all-NA array has no crs, and thus we give this warning.

(this is actually something that could be solved "properly" if we would make the CRS a part of the data type, instead of just an attribute on the array object)

**Comment by m-richards** [comment]
>(this is actually something that could be solved "properly" if we would make the CRS a part of the data type, instead of just an attribute on the array object)
would there be any other benefits of doing this, or is this the only edge case you are aware of?
