### ISSUE TITLE
Migration from PyGEOS to Shapely 2.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2691]
Starting with GeoPandas 0.12, we support running geopandas with shapely >= 2, but at the moment we still default to pygeos, if installed as well (as discussed in the original PR https://github.com/geopandas/geopandas/pull/2275, see eg https://github.com/geopandas/geopandas/pull/2275#issuecomment-1206347135 and https://github.com/geopandas/geopandas/pull/2605#issuecomment-1284099711). 

When both pygeos and shapely 2.0 are installed, we do give a warning about that we still use pygeos and you have to enable shapely 2.0 manually (https://github.com/geopandas/geopandas/pull/2605).

Various things we can / should do at some point in time:

* Start with changing the text of the warning to indicate this will change to default to shapely in the next? release (and how they need to manually set it to pygeos to keep using pygeos on the short term)
* Document what will change if we switch to shapely, how you can migrate from geopandas+pygeos to geopandas+shapely.
* The main interaction point with geopandas and direct use of pygeos, is getting the underlying geometries as a numpy array of pygeos objects (`gdf.geometry.array.data`). _In theory_, we could add a deprecation warning to `GeometryArray.data` (and eg internally switching to `_data`) _if_ this returns pygeos objects, warning that this will become shapely objects in the future.
* At some points switch the default to shapely if both are installed
* At some point also deprecate the option to use pygeos

Other things I am forgetting?  Ideas about a timeline for those? (I would say we could start with an already stronger warning in 0.13 that the default will change to shapely)

cc @brendan-ward @martinfleis 

* https://github.com/geopandas/geopandas/pull/2834
* https://github.com/geopandas/geopandas/pull/2833

**Comment by martinfleis** [comment]
I see the transition as 3 steps, within 3 upcoming releases.

**0.13** (early 2023)
1. We should change the warning to the `FutureWarning` explicitly saying that shapely 2.0 will take a precedent over pygeos in the next release.
2. Add migration guide explaining how to use geopandas+shapely instead of geopandas+pygeos. That should not be complicated as it is in most cases just a replacement but there are some changes.

**0.14** (mid 2024)
1. Change default engine to shapely 2.0 but keep the support of pygeos. This way people can use pygeos-based code for a bit longer if they really need it.

**1.0** (early 2024)
1. Remove both pygeos and shapely<2 support.

That way, we will have two releases indicating that folks should migrate (0.12 and 0.13) plus one more to keep it running (0.14) and then we can switch.

Time-wise, I'd aim to get 1.0 about a year after 0.13, so January 2024. This should give others enough time to migrate and us to finish what we'd like to see in 1.0.

Potentially, there may be 0.15 in the meantime (possibly moving the default switch from 0.14 to 0.15) but I'd try to stick to the end of this migration period around early 2024.

> we could add a deprecation warning to GeometryArray.data

that sounds reasonable to me.

**Comment by martinfleis** [comment]
I looked at a possible ways of migration from pygeos to shapely across the PySAL org and given we use very wide range of functions and often also those like `polygons` to create geoms, I am not sure if GeoPandas can actually help a ton in the transition. 

What is doable right now is to depend on shapely 2.0 and replace all pygeos bits with shapely and instead of getting the `df.geometry.values.data` to work on, pass a GeoSeries directly. If shapely 2.0 is a backend, all is fine. If pygeos is, there is a conversion cost (roughly 1 µs per geometry, linear scaling, when installed from conda-forge) but the code works as expected as well. I don't see a reasonable transition with support of 1.8 without version-based if/else clauses like we have.

It would not follow NEP29 on backwards support but GeoPandas 1.0 will also intentionally violate that. So I would recommend downstream projects to replace pygeos with shapely 2, pin it and hope the ecosystem won't break.

It is not optimal but nothing is right now. If nothing else, it will at least speed up the transition to shapely 2 and make the GeoPandas 1.0 release less bumpy.

**Comment by m-richards** [comment]
>I don't see a reasonable transition with support of 1.8 without version-based if/else clauses like we have.
I suppose one could wrap this up nicely and encourage use of the wrapper api rather than raw if elses - but that would be a lot of work in itself (and I suppose for pysal, because it's a collection of packages that wrapper needs to be a package itself then).

Personally (and perhaps this is not the most wholistic view) as breaking changes go, pygeos & shapely 1.8 -> shapely 2 is relatively friendly. Now a breaking change might not be NEP29 compliant or follow professional software engineering best practice, but most open source maintainers are not professionals in open source, they're volunteers and their time is precious. If a clean break makes things simpler to implement, maintain and test then that seems quite valuable. Perhaps however the average user doesn't think about the perspective of maintainers though.

**Comment by martinfleis** [comment]
Migration has been completed (on main).
