### ISSUE TITLE
State of geopandas?

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#276]
Hi All!

I've been thinking of switching into `geopandas` from `arcpy` for a while, but have been holding out for the integration of a spatial join to the library (since I'm not sure how to do most of what I do without a spatial join). Out of curiosity, I took a look through the `git` repository and found that you had in fact implemented a spatial join (!) it just hadn't been added to the docs. 

Looking a little more, it seems like a lots been added (mostly in late 2015), but none of it has been documented, and the git repo seems pretty quite. It also looks like `geopandas` hasn't had a release since late 2014. 

With that in mind, I was wondering: what is the state of this library? Has it been abandoned? It seems like an amazing resource -- I hate looping over all my features and querying dictionaries any time I want to do anything with `shapely`, and hate `arcpy` almost as much for even more reasons. But I don't want to switch over my code if this is a project that just never got traction. 

Relatedly, if there are places a newcomer could contribute, please let me know. Seems like the docs are the big issue (which I don't know enough to fix), but I know `shapely` and `pandas` pretty well, so if I can help get this to 0.2 I'd love to (though I'm trying to finish a dissertation, so also want to be realistic about how much I can do).

**Comment by jorisvandenbossche** [comment]
To give the perspective of a recent (satisfied) user and contributor (I also gave a lightning talk about it at EuroScipy https://gist.github.com/jorisvandenbossche/7b30ed43366a85af8626). Being able to combine the geometry objects and method of shapely with the power of dataframes is for me really important.

It is certainly not abandoned (you can see some recent activity in PRs), but it is true that it really needs a new release. 

I was planning to propose to volunteer to do that in a few weeks (@kjordahl gave me commit rights so I should be able to do it), as I should have some time for this in april (if my dissertation is finished :-)). If a release hasn't happened before that, I still can do that. 
My idea is to just release it as is (it's more important to have a release quickly), and some fixed or new features in PRs can always be added in a follow-up release (since it is pure python releasing is not that difficult).

I think indeed that the docs are an area that need improvement and would be a good place to contribute. For example, if you start using the spatial join, it's maybe an idea to write some docs about that? Further, docstrings in general can also use improvements (there are some issues about that).

**Comment by nickeubank** [comment]
Oh why hello @jorisvandenbossche  -- fancy meeting you here. :) Also terrified to hear you're also trying to survive a dissertation. 

I haven't actually played with the spatial join yet -- just discovered it was in the master branch -- but if you can point me to a few functions that need to be written up I can take a swing at learning by doing and updating the relevant docs.

**Comment by perrygeo** [comment]
@nickeubank A lot of the spatial join and overlay functionality is "documented" by way of examples on the wiki: https://github.com/geopandas/geopandas/wiki/Notebooks

Agreed, we need a 0.2 release!

**Comment by kjordahl** [comment]
@nickeubank Indeed, I haven't had much bandwidth to keep up with geopandas lately, but @jorisvandenbossche and others have been contributing and keeping things moving.

I feel like we've made significant progress from 0.1, and the main obstacle to a 0.2 release is documentation. Please see the [0.2 milestone](https://github.com/geopandas/geopandas/milestones/0.2%20release) for issues. We really need to have the docs in sync with current features for a release. Any help on that front would be appreciated.

I'm going to close this issue, as I hope that we've answered you're question. Please feel free to continue to comment here and on other issues. Thanks for the spur to get 0.2 out there.

**Comment by nickeubank** [comment]
@kjordahl Great, thanks! I'll submit an issue after playing around with a list of things that appear to need updating.
