### ISSUE TITLE
ENH: Write vector files with metadata (tagging)

### ISSUE THREAD

**Issue by drStacky** [geopandas/geopandas#2777]
It would be very useful to be able to tag certain metadata (ex: `version=1.3.0`) in the vector files. Something along the lines of how `rasterio` allows tagging rasters with dictionaries.

https://rasterio.readthedocs.io/en/latest/topics/tags.html

Currently you can assign a property `gdf['version'] = '1.3.0'`, but this gets assigned to every single geometry, which seems wasteful for something like this.

I believe `DataFrame.attrs` does not propagate through operations on the dataframe and are not written to file, so it would probably take a lot of work to go that route.

Looks like `Fiona` implemented a tagging solution for `>=v1.9.0`.

https://github.com/Toblerity/Fiona/issues/713

A solution might use a `tags` dictionary:
```
gdf.tags = {'version': '1.3.0'}
gdf.to_file('foo/bar.gpkg', driver='GPKG', layer='baz', tags={'version': '1.3.0'}) 
```

**Comment by jorisvandenbossche** [comment]
The fiona support is released now with 1.9.0, so we could indeed support this through `to_file`. I would start with an additional keyword where the user can specify the metadata as a key/value dict (instead of checking some attribute on the GeoDataFrame), i.e. your second line in the example above.

Contributions are certainly welcome!

**Comment by DahnJ** [comment]
I will have a few spare hours on Wednesday and might give this a shot. Leaving my thoughts here in case anybody was already working on this / wanted to comment on it.

I would add
```python
colxn.update_tags(tags)
```

to [_fo_file_fiona](https://github.com/geopandas/geopandas/blob/b16173ea3d001d60c7970cc1580659b4bd4b307f/geopandas/io/file.py#L546).

And then propagate the `tags` argument to [_to_file](https://github.com/geopandas/geopandas/blob/b16173ea3d001d60c7970cc1580659b4bd4b307f/geopandas/io/file.py#L438) and [GeoDataFrame.to_file](https://github.com/geopandas/geopandas/blob/b16173ea3d001d60c7970cc1580659b4bd4b307f/geopandas/geodataframe.py#L1125).

I would also raise `NotImplementerError` if the user attempts to write tags with `engine == "pyogrio"` for now (https://github.com/geopandas/pyogrio/issues/218)

**Comment by jorisvandenbossche** [comment]
@DahnJ that sounds good! the change you describe sounds good, most of the work will probably be to write a test for it.

One aspect I am wondering about (but that shouldn't prevent you making a PR) is whether we want to call this "metadata" instead of "tags" on the geopandas side. That is what GDAL calls it, and if we add the same feature to pyogrio, we might want to call it like that as well.
