### ISSUE TITLE
BUG: Buffer 0 a MultiPoint or a Point results in an empty polygon

### ISSUE THREAD

**Issue by tqa236** [geopandas/geopandas#2819]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely.geometry import MultiPoint, Point

multipoint = MultiPoint([Point(0.5, 0.5), Point(100, 100)])
gdf = gpd.GeoDataFrame({"geometry": [multipoint]}, geometry="geometry")
gdf.geometry.buffer(0)
```

#### Problem description
Before dissolving a GeoDataFrame, I often use `.buffer(0)` to avoid the `TopologyException`, also mentioned here: https://github.com/geopandas/geopandas/issues/915#issue-408583190

However, when I call `.buffer(0)` on a MultiPoint or Point geometry, it results in an empty polygon, as shown in the snippet of code above. I'm nor sure if this is a bug or intended behavior.

#### Expected Output

Call `.buffer(0)` on a MultiPoint geometry results in itself. 

#### Output of ``geopandas.show_versions()``

<details>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

SYSTEM INFO
-----------
python     : 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
executable : /home/\<user\>/virtual_env/venv/bin/python3
machine    : Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.4.3
GDAL data dir: /home/\<user\>/virtual_env/venv/lib/python3.10/site-packages/fiona/gdal_data
PROJ       : 9.1.0
PROJ data dir: /home/\<user\>/virtual_env/venv/lib/python3.10/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.1
numpy      : 1.23.5
pandas     : 1.5.2
pyproj     : 3.4.0
shapely    : 2.0.1
fiona      : 1.8.22
geoalchemy2: None
geopy      : 2.3.0
matplotlib : 3.6.2
mapclassify: 2.4.3
pygeos     : 0.13
pyogrio    : v0.4.2
psycopg2   : None
pyarrow    : 10.0.1
rtree      : 1.0.1

</details>

**Comment by brendan-ward** [comment]
This is expected behavior and comes directly from GEOS, by way of shapely.  `buffer` always produces output polygons, and in this case, a radius of 0 around a point does not circumscribe any area - hence an empty polygon.  The `.buffer(0)` trick is only valid for polygons / multipolygons; for everything else it would modify the geometry type, which would cause bigger issues in data processing where geometry types are expected to remain the same.

I'm not clear on what you are trying to accomplish with buffering points in this way?  They don't have the same toplogy issues as polygons where `.buffer(0)` would be useful.  Perhaps you need to apply `.buffer(0)` to only those geometries within your GeoDataFrame that are polygons or multipolygons, and ignore the rest?

**Comment by tqa236** [comment]
@brendan-ward thanks for confirming that this is the intended behavior. We just have a thin wrapper function that always calls `.buffer(0)` before dissolving in hope of not having to face the topology exception. We'll probably need to be more selective in buffering as you suggested. 

I'll close the issue as my question is answered.
