### ISSUE TITLE
API: sindex query() vs query_bulk() method - only keep query()?

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2823]
Our current `.sindex` interface still has both `query()` and `query_bulk()` methods. 

In Shapely 2.0, in the end we decided to merge those two methods into a single `query()` (passing scalar -> return 1D array of indices, passing array -> return 2D array of left/right indices).

Should we follow that change in our sindex interface as well?

**Comment by brendan-ward** [comment]
Since there is no breaking change if you call `query()` with scalar inputs (the only change is for non-scalar inputs), perhaps we can use a deprecation warning on `query_bulk()` and route both to shapely's single `query()`, then drop `query_bulk()` in 0.14?

This does mean a slight refactor of the rtree methods to match shapely.

**Comment by martinfleis** [comment]
I would also deprecate `query_bulk` and use `query` for any input as shapely does. 

Regarding the rtree methods, is it worth the effort? That will go away soon-ish anyway and when we actually remove query_bulk we will remove whole rtree part as well.

**Comment by jorisvandenbossche** [comment]
> Regarding the rtree methods, is it worth the effort? 

We already have an implementation mimicking query_bulk for the rtree-based sindex, so moving that into query is quite easy. And that ensures we can just call query ourselves everywhere (in sjoin/overlay and in the tests)

**Comment by jorisvandenbossche** [comment]
-> https://github.com/geopandas/geopandas/pull/2831
