### ISSUE TITLE
scipy presentation?

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#304]
It strikes me that it makes sense to try and finish 0.2 by SciPy, and (if anyone is planning to attend) doing a presentation on the topic. Any thoughts on feasibility? I think docs will be in good shape by then, though unfortunately I won't be attending so cannot present.

**Comment by kjordahl** [comment]
@nickeubank It's too late for a talk submission, but having a release by then would be great. I plan to attend. A lightning talk is a possibility, as is a sprint if there will be others interested.

**Comment by nickeubank** [comment]
@kjordahl Sounds good -- it'd be great if anyone attending wanted to do a sprint. 

Relatedly, if you or @jorisvandenbossche have a chance to clear some PRs I think it'd help. There are enough things up in the air in open PRs it's a little hard to keep moving forward. Once the doc updates and changelog are integrated, for example, I can try and do finals cleaning. And if we decided to add the dissolve function or example data, I can integrate those into docs too.

**Comment by jorisvandenbossche** [comment]
@kjordahl @nickeubank I reviewed some of the docs PRs last week. If it would be possible to have a release earlier, I would prefer that.

I have some time the coming week, and I can help with finalizing the release. The remaining issues with a milestone of 0.2 are not much work I think.

IMO it would be better to release now, and we can always do follow-up (minor) releases the coming months for further issues/features. On Stack Overflow, there was already a question that some examples were not working because of using the released version instead of the master version.

**Comment by nickeubank** [comment]
I'm all for sooner! Just thought that was a good deadline to keep everything moving.

**Comment by nickeubank** [comment]
Seems like this is wrapped up unless someone wants to do a spring / lightening talk.
