### ISSUE TITLE
MAINT: Remove internal dependency on geopandas.datasets in tests

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#3079]
As part of 1.0 we want to remove the geopandas.datasets module and direct users to use geodatasets instead.
We also need to decide how to handle this in our own tests, these are the options I see:
1. Keep the test files as part of the library, but only expose them via a pytest fixture (no direct way for users to use them), least effort option
   * Or perhaps there is a slight variant where the tests are no longer included on main on github / in the wheel, but are downloaded and cached via a fixture and pooch - we'd need this to be robust to go down this path though, don't want running the tests successfully to be a barrier to contribution.
2. Transition tests to use geodatasets
   * This is somewhat straightforward for tests using nybb, although I've had a quick look at some of our tests make assumptions about nybb being zipped, and in geodatasets the path unzipped
   * For tests dependending on naturalearth the options are:
      * Do some form of (1) for these tests, and perhaps migrate some tests which are straight IO tests across to use another geodatasets dataset
      * Replace all the tests with another dataset with similar qualities. My preference would be not to do this (at least not first up) as this is going to be time intensive and our maintainer time is already a bit stretched at the moment

I'm happy to look into doing this, but would be good to agree on the approach first

**Comment by martinfleis** [comment]
> Keep the test files as part of the library, but only expose them via a pytest fixture (no direct way for users to use them)

This would be my preference. For the reasons of effort and especially safety. Changing tests to depend on different data is always dangerous because we may unknowingly stop testing some corner cases that are present in naturralearth but may not be in a replacement dataset.

> downloaded and cached via a fixture and pooch

That is essentially in-house geodatasets solution. I wrote several tests depending on geodatasets and outside of some cases where multiple workers in `pytest-xdist` tried to download and write/read the file at the same time, which lead to IO errors due to corrupted files, there were no issues so far. And this one was easy to fix by fetching the data in a separate step on GHA prior running pytest.

I'd be fine with this but also don't think it is necessary thing to implement. I am happy if we just move the source files somewhere private and add a fixture that gives us the path to be replaced in tests.

**Comment by m-richards** [comment]
> This would be my preference.

Okay glad we are on the same page, that feels like the best use of time - and I was also worried about subtly breaking tests
