### ISSUE TITLE
ENH: Specify datetime format and rounding frequency when reading a file

### ISSUE THREAD

**Issue by andreweryan** [geopandas/geopandas#3082]
#### Is your feature request related to a problem?

This feature request is related to a potential problem which prevents files from being read using fiona if they contain different datetime formats and precisions. If your datetime field(s) have mixed formats/precision it can break import, exit with error and prevent from reading the file.  I would like GeoPandas to allow for setting datetime format and rounding precision upon reading a file through the `read_file` function. 

#### Describe the solution you'd like

`geopandas.read_file()` should have an argument such as `datetime_format='mixed'` and `datetime_precision='ms'` to allow for mixed datetimes and different datetime precision upon reading the file and provide the user more flexibility. Defaulting to mixed format should prevent some issues upon reading files with different datetimes and allowing for users to specify datetime precision, e.g., second, minute, day.

#### API breaking implications

I don't believe this will break the API per se but would require changes to the arguments for `read_file()` and a change to kwargs in `_read_file_fiona()`. 

#### Describe alternatives you've considered

Alternate methods are manually parsing a GeoJSON to convert/ round datetime formats before reading into a GeoDataFrame or manually exporting a CSV from QGIS and reading into Pandas then GeoPandas. 

#### Additional context
Pandas `to_datetime()` and `dt.round()` support specifying the datetime format and frequency of rounding
https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.round.html

I believe that all that is needed is allow the format and frequency arguments for `pd.to_datetime()` and `as_dt.dt.round()` to be accessed and altered by args or kwargs to `_read_file_fiona()` on lines 401-411 in io/file.py _read_file_fiona()`

```python

format='mixed'
frequency='ms' # alternatively, '1s', 'min', 'd'

for k in datetime_fields:
    as_dt = pd.to_datetime(df[k], format=format, errors="ignore")
    if as_dt.dtype == "object":
        as_dt = pd.to_datetime(df[k], format=format, errors="ignore", utc=True)
    if not (as_dt.dtype == "object"):
        df[k] = as_dt.dt.round(freq=frequency)
```

**Comment by m-richards** [comment]
Would you be able to provide an example file containing mixed formats? Based on what you say it sounds like `read_file` crashes when getting mixed formats / precision - that definitely should not happen, whether or not extract kwargs are exposed.

In the first instance we should see if the automatic parsing could be a bit more robust without additional arguments. We certainly could expose these arguments directly, but it becomes a bit messy, as the existing IO args and kwargs are passed to the IO engine (fiona or pyogrio). 

In terms of rounding, we currently  round to ms precision (and with pyogrio and pandas 2 we switch to the ms datetime dtype) as that's the limitation of datetime types in GDAL. To me, there's no real need to expose this as part of read_file, a user can perform any kind of rounding they like after the file is read into a geodataframe (but I could be persuaded on this). If however in future we did try to infer the rounding, rather than just applying a fixed rule, then I could see the sense in being able to alter that behaviour by passing in explicit parameters.
