### ISSUE TITLE
BUG: __geo_interface__ can return output other than lng/lat degrees

### ISSUE THREAD

**Issue by ajfriend** [geopandas/geopandas#3097]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of geopandas.

Hey folks, thanks for the great tool! I had a question about the output format of `__geo_interface__`, and didn't see this discussed anywhere else. 

The `__geo_interface__` spec (https://gist.github.com/sgillies/2217756) describes that the `coordinates` key should be in terms of (longitude, latitude) pairs. The GeoJSON spec (https://datatracker.ietf.org/doc/html/rfc7946#section-4) goes further, saying it should be in decimal degrees, and specifically use WGS 84. 

However, when using `geopandas` the `__geo_interface__` output will vary depending on the CRS that's set. For example,
`df = geopandas.read_file(geodatasets.get_path('nybb'))` will default to EPSG:2263 and `__geo_interface__` will output a GeoJSON-like dictionary but in feet instead of degrees.

Is this expected/intended behavior? Would it make sense to always convert the underlying CRS to WGS 84 when computing `__geo_interface__` to align with the GeoJSON spec, or are there reasons for the current behavior?

**Comment by martinfleis** [comment]
Hi, thanks for the question!

This is expected behaviour and is unlikely to change. `__geo_interface__` does not follow the 2016 GeoJSON specification to a letter. The spec of the `__geo_interface__` explicitly says:

> This is an (x, y) or (longitude,
latitude) tuple in the case of a "Point", a list of such tuples in the "LineString" case, or a list of lists in the "Polygon" case

There is no restriction about CRS that is being used and it would be impractical given the use case for the `__geo_interface__`. 

If you want to create a JSON following the latest GeoJSON specification, use `to_json(to_wgs84=True)`. By default, `to_json` follows 2008 version of the specification (as does GDAL) thus allowing custom CRS. With `to_wgs84=True`, we transform geometries to WGS84, if necessary, to follow the 2016 spec. 

Also, keep in mind that the `__geo_interface__` is from 2012, hence predates 2016 GeoJSON specification and when it is referring to the "GeoJSON", it is referring to the 2008 version.

**Comment by ajfriend** [comment]
Thanks for the answer! I'm trying to think through the best ways for our library `h3-py` to interact with `geopandas`. For example, you can see the "CRS" section here: https://gist.github.com/ajfriend/0b7de6153acdd6a1ca04cd9033285beb

I'm anticipating that a common gotcha is going to be people forgetting to convert to WGS 84 before applying `h3-py` functions. Obviously, if `__geo_interface__` always output WGS 84, then we'd be fine, but I understand that that isn't going to change. 

Would it be possible to return a `'crs'` tag in the dictionary output of `__geo_interface__`? Would that break any current use cases? That would allow us to either confirm we got the right input or error out.

I could recommend `to_json(to_wgs84=True)` as the idiomatic way to do things, but it seems like that method only exists for dataframes, and I think we'd like to be able to operate on shapes individually.

I'm new to interfacing with `geopandas`. Are there existing recommended patterns for working with transformations of geometry columns that depend on having a certain CRS or at least knowing what it is?

**Comment by dfellis** [comment]
The `crs` attribute *is* part of the GeoJSON 2008 specification that Geopandas says it is adhering to, [and that specification says that if it is not included, one can assume the coordinate system is WGS84](https://geojson.org/geojson-spec.html#coordinate-reference-system-objects) and if you want it to be another coordinate system, it should be an object that provides information to determine what coordinate system is in use.

So whether you go by the 2008 or 2016 specification, Geopandas is *not* in compliance at this time.

**Comment by martinfleis** [comment]
> So whether you go by the 2008 or 2016 specification, Geopandas is not in compliance at this time.

I am sorry but that is not correct. There seems to be a misunderstanding of what a GeoJSON is and what a `__geo_interface__` is as they are not the same.

When you want a GeoJSON, GeoPandas provides two options how to create one. One is via `to_json()` method where the `to_wgs84` keyword controls whether the result follow 2008 version of the specification (`False`) or 2016 version of the specification (`True`). Second option is to use `to_file()` method and let GDAL create the GeoJSON for you. That, by default, follows the 2008 specification, unless you pass a RFC7946 flag to GDAL.

On top of these explicit methods generated a GeoJSON, GeoPandas also implements `__geo_interface__`, which is a protocol allowing an exchange format for geospatial data. `__geo_interface__` is GeoJSON-like but it is not a GeoJSON per GeoJSON specification. It happens to use the structure of mapping from GeoJSON but the specification does not deal with CRS in any way. `"crs"` shall not be included as the spec does not talk about nor it specifies in which format should the CRS information be serialised. `__geo_interface__` further makes no assumptions about the CRS and explicitly allows coordinates either as `(x, y)` or `(longitude, latitude)` tuples. There were some suggestions to include `"crs"` in the `__geo_interface__` but none of them was accepted and as a result, `__geo_interface__` does not bear any information about the projection that is used.

I am sorry that you are disappointed but in all three cases (GeoJSON 2016, 2008 and `__geo_interface__`), GeoPandas follows the respective specifications in methods that are designed for them.

If you expect `__geo_interface__` to be precisely following GeoJSON spec (either of them), than it is a misunderstanding of what it is and what its specification says.

**Comment by ljwolf** [comment]
Just to provide a little more historical context: 

Sean's justification for the `__geo_interface__` in the post was to mimic/complement the ongoing discussions at the time about `__array_interface__`: a way to offer zero-copy interoperability between geometry objects throughout the ecosystem (like PySAL, ArcPy, and shapely, mentioned in the original `__geo_interface__` spec). This was mainly at the *object*/geometry level, while `crs` info was managed at a "higher" featurecollection/dataframe level.  

As in the preamble of the `__geo_interface__` spec, we sought simple "`as_geometry()`" functions for zero-copy object translation. Hence (as @martinfleis notes) the `__geo_interface__` spec explicitly allows for (`x,y`) as separate from `longitude, latitude`.

To be sure, `shapely`'s `__geo_interface__` also does not ensure nor require outputted `__geo_interface__` objects to be in a specific coordinate system, and indeed this makes sense because it does not [support coordinate systems](https://shapely.readthedocs.io/en/stable/manual.html#coordinate-systems): 

```python
>>> import shapely
>>> box = shapely.box(1000,1000,1001,1001)
>>> box.__geo_interface__
{'type': 'Polygon',
 'coordinates': (((1001.0, 1000.0),
   (1001.0, 1001.0),
   (1000.0, 1001.0),
   (1000.0, 1000.0),
   (1001.0, 1000.0)),)}
```

The [ArcPy](https://desktop.arcgis.com/en/arcmap/latest/analyze/arcpy-functions/asshape.htm) implementation also suggests that `asShape()` does not process `crs` information. 

If you want *geojson*, @martinfleis's suggestion of `to_json(to_wgs84=True)` is the best way forward.

**Comment by dfellis** [comment]
An interchange format (that is what `__geo_interface__` is) that doesn't provide any guarantees on what the type of data it is transmitting is, is an essentially useless interchange format. It provides no safeguards at all against GIGO, and *will* cause unexpected and sometimes hard-to-detect bugs when different libraries have slightly different assumptions of what the interchange format's data actually represents.

The `crs` property in the 2008 specification states that it belongs on the top-level object, whatever that may be, so attaching it to the `Polygon` object in the example above would be reasonable if you don't want to follow the 2016 specification.

As for Shapely, a lack of a coordinate system at all is supposed to be represented by attaching the `crs` property with the value explicitly set to `null` according to the 2008 GeoJSON specification, as a lack of the property should be assumed to mean `WGS84`, and the current behavior should also be considered to be a bug.

Using the excuse "that's how we've always done it" makes improvement to the ecosystem impossible, and that there are workarounds to this bug doesn't mean it's not a bug. If someone is using my library incorrectly, I want them to immediately know about it before it causes them or their users problems, and if someone else's popular library allows itself to be used incorrectly and then get reported as a bug in my own library, you can be sure that I will report it upstream so they can correct it.

In the current state of things, it it simply *unsafe* to consume the output of `__geo_interface__` except if you are simply passing it along to something else (database, filesystem, http response, etc) because *any* interpretation of the `coordinates` is suspect, and there is no way for the consuming library to know if `2` means `2 meters`, `2 degrees`, 2 radians`, or even `2 furlongs`, and that number demonstrates how you can't *actually* solve this with a simple `(-90, 90), (-180, 180)` bounds check, as all of these contain at least the range of `(0,Pi)` as valid inputs that mean vastly different things.

If you don't want to follow the 2016 GeoJSON specification and convert everything to WGS84, then please at least follow the 2008 GeoJSON specification to eliminate this ambiguity -- even just setting `'crs': None` so we can see that and reject the input so the *user* quickly understands that they need to use something like `to_json(to_wgs84=True)`, rather than after they've run days of data processing and produced (or even based decisions on) garbage output.

**Comment by martinfleis** [comment]
I understand your frustration but GeoPandas repository is not the right place to ventilate it. There are two (three if counting 2008 and 2016) specifications of serialising geospatial data to a JSON format. One is GeoJSON specified at https://geojson.org and the other is `__geo_interface__`, specified at https://gist.github.com/sgillies/2217756. **Neither of them is defined by GeoPandas.** We simply implement methods to convert GeoDataFrames and GeoSeries' to these specifications. And there, we precisely follow the specification, which means that in case of GeoJSON, you can enforce WGS84 and long/lat coordinates or include a `"crs"` to follow the 2008 spec if you prefer that. And for `__geo_interface__` we directly serialise whatever coordinates happen to be in our geometries and do not include `"crs"` as that would go **against** the specification.

I do understand the use case to include a `"crs"` information in the JSON and I also understand that there are situations when it would be helpful to have it included in `__geo_interface__`. But as long as the specification of `__geo_interface__` does not change, GeoPandas will not change the implementation as that would mean deviation from the spec.

If you think that `"crs"` should be part of the `__geo_interface__` specification, you can try to bump the discussion on that topic in https://gist.github.com/sgillies/2217756. If there will be a version 2.0 of the `__geo_interface__` specification that includes the `"crs"`  either as WKT2, PROJJSON or anything else, I'd be happy to ensure that GeoPandas is first to support it. But until then, we stick to the specification.

And a side note - the fact that you still insist that there is a bug in geopandas even though we've been quite clear and extensive in our explanations of the situation is a bit insulting and those 👎 emojis under every of my posts where I try to patiently explain to you what is going on don't help my willingness to dedicate my free time to this discussion. I am still doing that but wanted to let you know that it has a deterring effect.
