### ISSUE TITLE
DOC: Errors in website providing Geoplot examples

### ISSUE THREAD

**Issue by AlexMuresan** [geopandas/geopandas#3103]
When looking through Geoplot examples in Geopandas I ran across multiple errors inside the online documentation.

#### Screenshot

I think the issue stems from here:
![image](https://github.com/geopandas/geopandas/assets/16186217/96f4e019-429a-40cb-9f89-83e018742412)

But it breaks the code on the whole page:
![image](https://github.com/geopandas/geopandas/assets/16186217/8e198431-eb0e-40fd-bc84-43a4620eda50)

#### Problem description
[Link to page](https://geopandas.org/en/stable/gallery/plotting_with_geoplot.html)
Data is not loaded properly into Geopandas and therefore it can't be used for plotting.

#### Expected Output

The expected output is a properly rendered map.

**Comment by martinfleis** [comment]
Thanks! We are aware. Geoplot is not a maintained library and I think that the best solution for us would be to remove the example until the situation is resolved. These errors come from geoplot, not geopandas.

**Comment by aeturrell** [comment]
Is there any chance of geopandas absorbing geoplot? The visualisation capabilities of the two libraries combined are really key to the success of both, at least for the use cases I am often teaching.

**Comment by martinfleis** [comment]
We have discussed it but there's no bandwidth in the geopandas team at the moment to take on additional stuff of this extent. We'd be happy to support anyone willing to maintain geoplot but can't do that ourselves.

**Comment by aeturrell** [comment]
Completely understand. It feels like we need a better system to connect supply and demand in open source-I bet there are devs out there looking for a high impact package to work on.

Thanks for your swift reply and your amazing work on **geopandas**.

**Comment by nicholas-ys-tan** [comment]
> We'd be happy to support anyone willing to maintain geoplot but can't do that ourselves.

Is that something @ResidentMario is looking for?

I haven't worked with geoplot before, but I've done a fair bit with geopandas, matplotlib, seaborn and cartopy at my previous job.

**Comment by martinfleis** [comment]
Not sure about the status. I suggest checking with @ResidentMario in the geoplot repository. It seems that not even easy PRs get attention (e.g. https://github.com/ResidentMario/geoplot/pull/293) so it is hard to tell. A lot of fancy visualisation tools based on JavaScript have appeared in the meantime, so there may not be that much audience any longer.

**Comment by nicholas-ys-tan** [comment]
Thanks @martinfleis , that makes sense.

I've had a look and managed to get geoplot working with the latest versions of its dependencies. At least based on the examples and tests in geoplot and the example that was removed in this PR (with some corresponding updates), and some of the issues raised. There are probably more things I'll need to look at.

I'll see if I can get in touch with the maintainer if he would like to merge my commits into his repo, or point to my fork or otherwise.

Out of curiosity, which tools based on JavaScript have come up in the last 2 years since maintenance for this repo ended? (It's been about that long since I stopped doing data vis at work).
