### ISSUE TITLE
ENH: Will geopandas load geodata from s3 server with storage_options argument？

### ISSUE THREAD

**Issue by forestbat** [geopandas/geopandas#3129]
I want to load file from my minio server which is compatible with amazon s3 filesystem，when I try to read ordinary csv file from server，I can use this code：
```
import pandas as pd
storage_option = {'key': 'my_account', 'secret': 'my_password',
                      'client_kwargs': {'endpoint_url': '……'}}
csv_dataset = pd.read_csv('s3://……', storage_options=storage_option) 
```
However when I use geopandas to read shapefile from minio server like this:
```
import geopandas as gpd
storage_option = {'key': 'my_account', 'secret': 'my_password',
                      'client_kwargs': {'endpoint_url': '……'}}
gdf = gpd.read_file('s3://……', storage_options=storage_option, engine='pyogrio') 
```
it crashed with this:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\geopandas\io\file.py", line 287, in _read_file
    return _read_file_pyogrio(filename, bbox=bbox, mask=mask, rows=rows, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\geopandas\io\file.py", line 447, in _read_file_pyogrio
    return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\pyogrio\geopandas.py", line 239, in read_dataframe
    result = read_func(
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\pyogrio\raw.py", line 194, in read
    result = ogr_read(
  File "pyogrio\\_io.pyx", line 1124, in pyogrio._io.ogr_read
  File "pyogrio\\_io.pyx", line 171, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: AWS_SECRET_ACCESS_KEY and AWS_NO_SIGN_REQUEST configuration options not defined, and C:\Users\Administrator\.aws\credentials not filled
```
In fact, not only fiona but also pyogrio will spawn this crash, so I think you should adjust your method for loading data from s3 like pandas.
Waiting for your reply.

**Comment by brendan-ward** [comment]
I'm not very familiar with the use of `storage_options` but my understanding is that Pandas provides that support.  Fiona and Pyogrio provide a very different way of interacting with a data source, so it is reasonable to expect that the parameters you need to pass to `read_file` will be different.  Mostly we've been trying to have parity in the parameters between Fiona and Pyogrio, but not necessarily with other I/O functions.

Both Fiona and Pyogrio use GDAL under the hood, which uses a virtual file interface to read from S3-like APIs.  See the [GDAL docs](https://gdal.org/user/virtual_file_systems.html) for more info on this, esp. the use of environment variables or configuration parameters for the S3 parameters.

For Pyogrio, it might be possible to pass these options like this:

```Python
gdf = gpd.read_file('s3://……', engine='pyogrio', dataset_options={'AWS_ACCESS_KEY_ID': '<key>', 'AWS_SECRET_ACCESS_KEY': '<secret>', 'AWS_NO_SIGN_REQUEST': True, 'AWS_S3_ENDPOINT': '<minio endpoint>'})
```

Unfortunately I don't have an S3 URL to test with, so I don't know if that works.

If that doesn't work, I see from one of our test cases in Pyogrio that it is possible to pass those as config options to GDAL, so you might be able to do something like:

```Python
from pyogrio import set_gdal_config_options

set_gdal_config_options(
        {
            "AWS_ACCESS_KEY_ID": "<key>",
            "AWS_SECRET_ACCESS_KEY": "<secret>",
            "AWS_NO_SIGN_REQUEST": True,
            "AWS_S3_ENDPOINT": "<minio endpoint>"
        }
    )

gdf = gpd.read_file('s3://……', engine='pyogrio')
```

**Comment by forestbat** [comment]
I came back, however the two methods both have problem:
```
import geopandas as gpd
gdf = gpd.read_file('s3://……shp', engine='pyogrio', dataset_options={'AWS_ACCESS_KEY_ID': '<key>', 'AWS_SECRET_ACCESS_KEY': '<secret>', 'AWS_NO_SIGN_REQUEST': True, 'AWS_S3_ENDPOINT': <endpoint>})
```
Crash looks like this:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\geopandas\io\file.py", line 287, in _read_file
    return _read_file_pyogrio(filename, bbox=bbox, mask=mask, rows=rows, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\geopandas\io\file.py", line 447, in _read_file_pyogrio
    return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\pyogrio\geopandas.py", line 239, in read_dataframe
    result = read_func(
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\pyogrio\raw.py", line 194, in read
    result = ogr_read(
  File "pyogrio\\_io.pyx", line 1124, in pyogrio._io.ogr_read
  File "pyogrio\\_io.pyx", line 171, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: AWS_SECRET_ACCESS_KEY and AWS_NO_SIGN_REQUEST configuration options not defined, and C:\Users\Administrator\.aws\credentials not filled
```
And when I try this code, it still crashed with a new report:
```
from pyogrio import set_gdal_config_options
set_gdal_config_options(
    {
        "AWS_ACCESS_KEY_ID": "<key>",
        "AWS_SECRET_ACCESS_KEY": "<secret>",
        "AWS_NO_SIGN_REQUEST": True,
        "AWS_S3_ENDPOINT": "<endpoint>"
    }
)
gdf = gpd.read_file('s3://bucket/dir/shap.shp', engine='pyogrio')
```
crash:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\geopandas\io\file.py", line 287, in _read_file
    return _read_file_pyogrio(filename, bbox=bbox, mask=mask, rows=rows, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\geopandas\io\file.py", line 447, in _read_file_pyogrio
    return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\pyogrio\geopandas.py", line 239, in read_dataframe
    result = read_func(
  File "C:\Users\Administrator\PycharmProjects\AIFloodForecast\venv\lib\site-packages\pyogrio\raw.py", line 194, in read
    result = ogr_read(
  File "pyogrio\\_io.pyx", line 1124, in pyogrio._io.ogr_read
  File "pyogrio\\_io.pyx", line 171, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: CURL error: Could not resolve host: test.http
```
So how to solve this "CURL error"?

@brendan-ward @martinfleis

**Comment by brendan-ward** [comment]
Thanks for doing further testing; you confirmed that it is necessary to use `set_gdal_config_options`, so we should probably add more explanation of that to the pyogrio documentation for using S3.  It looks like Fiona handles this with an `Env` context manager: https://fiona.readthedocs.io/en/stable/manual.html#cloud-storage-credentials
so we may need to give some thought as to how to harmonize handling cloud credentials a bit better between the two engines.

Your error `CURL error: Could not resolve host: test.http` sounds like an issue with your value of `AWS_S3_ENDPOINT`.  I don't use `minio`, so I'm not able to guide you as to a valid value there, but you'll need to have something that can resolve the host properly.  If your `minio` endpoint is only accessible via HTTP and not HTTPS, you might also need to set the `AWS_HTTPS` parameter, per the GDAL docs.

Perhaps this [GDAL issue](https://github.com/OSGeo/gdal/issues/1609) will be helpful; note that the examples are focused on using GDAL raster drivers and the GDAL python library, but the tips around setting the GDAL config parameters may be useful for you.

**Comment by brendan-ward** [comment]
Given that shapefiles are composed of multiple individual files, that may be part of the problem.  Not sure, I don't have an example of an unzipped shapefile on S3 to test with.

I found an example on S3 in the Fiona test suite that works here:

```
s3 = s3fs.S3FileSystem(anon=True)
gdf = geopandas.read_file(s3.open('s3://fiona-testing/coutwildrnp.zip'), engine='pyogrio')
len(gdf)
# 67

gdf = geopandas.read_file(s3.open('s3://fiona-testing/coutwildrnp.zip'), engine='fiona')
len(gdf)
# 67
```

I found that if I try to reuse the object returned by `s3.open` multiple times I get the same kind of `vsimem` error as above because the stream has already been consumed (you might need to call `.seek(0)` on the handle after reading before reading again).  However, in your case, that could be masking other issues to do with configuration of the S3 handle.

What happens of you put a zip containing all files for the shapefile on your minio instance and try to read that instead?  Or use one of the single-file formats, like GPKG, or FlatGeobuf.

Sorry, I just don't have enough experience trying to use S3 or mini-hosted objects to provide more guidance here.

**Comment by forestbat** [comment]
OK, I think this is probably GDAL's problem.
I'll close this issue and reopen it when I think it's necessary.

**Comment by metazool** [comment]
hi @forestbat - ran into this kind of problem today, trying to read shapefile data into geopandas from a non-AWS s3 store, and read this https://github.com/OSGeo/gdal/issues/9042 as well

Can confirm that if the `.shp` is zipped up with the ancillary files and read from s3, `geopandas` works as intended, but reading the `.shp` alone returns the `/vismem/` path error, think I see where the root cause is in `fiona`:

(At this point the file path is being read as bytes)[https://github.com/geopandas/geopandas/blob/a38e1941afa0f3c43e5ccc5e544ecedca1b42b41/geopandas/io/file.py#L303] and `from_bytes` is set as `True` and we create a fiona `BytesCollection` reader

That reader then has special handling for [setting a `vsi` parameter with `.zip` files](https://github.com/Toblerity/Fiona/blob/ec9768a9389530a0570446e3c34ae91448d28cf4/fiona/collection.py#L756), but not without them, and whether a file is zipped or not is [detected from the first few bytes](https://github.com/Toblerity/Fiona/blob/ec9768a9389530a0570446e3c34ae91448d28cf4/fiona/collection.py#L723), rather than looking at the filename.

Up in its `__init__` function [if vsi is not set, regular path parsing kicks in and that triggers the error](https://github.com/Toblerity/Fiona/blob/ec9768a9389530a0570446e3c34ae91448d28cf4/fiona/collection.py#L169)

I'm not sure where I'd try to fix this! `get_filetype` in `fiona.collection` has a `TODO` for handling other file types that GDAL cares about, but that could get brittle. While `geopandas` knows a lot more about the file than it's offering through `_read_file_fiona`...

I don't have access to an AWS s3 store to see if the behaviour's the same there. At least I know it's not me :)

**Comment by mattjbr123** [comment]
@metazool this was exactly the comment I was looking for today, thank you for posting your solution!
