### ISSUE TITLE
MAINT: Fiona 1.10 support

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#3207]
In our CI builds our fiona tests are failing against the 1.10a wheels, as a new path opening API is introduced (https://github.com/Toblerity/Fiona/pull/1331/files). We use `fiona.parse_path`, `fiona.path.ParsedPath`, `fiona.path.UnparsedPath` and `fiona.path.ParsedPath.from_uri(path)` at a quick glance. Now I think if we'd imported `fiona.path` instead of getting it relative to `import fiona` we'd just hit a warning that these will be removed in fiona 2.0 instead of hard crashes, but we may as well look at solving the root problem right now.

Edit: had a bit of a look and it seems to keep the same level of convenience witth zipfiles we might need to either vendor some things from fiona (or use the private internals), or use fsspec or similar

**Comment by sgillies** [comment]
@m-richards fiona's path module was never intended to be used by other projects. It's only public by accident. If I had known geopandas was using them, I would have warned you all sooner. Geopandas should try to rely only on passing URIs to its reader/writer.

**Comment by jorisvandenbossche** [comment]
Temporarily pinning to fiona 1.9 to get green CI -> https://github.com/geopandas/geopandas/pull/3208

**Comment by jorisvandenbossche** [comment]
The main usage of `fiona.path` in our code is related to handling with zip files. It might also be that things have improved on fiona's side lately and not everything might still be needed.

We have this helper to check if a path points to a zip-file:

https://github.com/geopandas/geopandas/blob/fb8da80fb2f170bdcb6b635a783d9d1424222021/geopandas/io/file.py#L179-L186

and then if that is the case, we have the following piece of code to add "zip" to the path's scheme:

https://github.com/geopandas/geopandas/blob/fb8da80fb2f170bdcb6b635a783d9d1424222021/geopandas/io/file.py#L321-L339

This is to make sure a user you can just pass a path to a zipfile like `"path/to/file.zip"`, instead of needing to do `"zip://./path/to/file.zip"`.
