### ISSUE TITLE
API: Series alignment for non binary op methods

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#3256]
We have a few geo methods which take an additional arraylike input as a parameter; `interpolate`, `offset_curve` and `voronoi_polygons`, but we don't have a consistent way of dealing with alignment between `self.geometry` and the passed arraylike when it is a Series.

>Just noticing we have a bit of inconsistency of how to handle when we have a non binary op method expecting an arraylike. For binary ops, we  warn on alignment, here we auto align, in `interpolate`, distance throws a ValueError if it does not align, and for `offset_curve` we just feed unaligned GeometryArray to shapely.

I would prefer we warn or throw on unaligned data, but whatever we decide we should be consistent across similar situations.

_Originally posted by @m-richards in https://github.com/geopandas/geopandas/pull/3177#discussion_r1570298342_

**Comment by martinfleis** [comment]
This is the current situation.

| function               | param                        | helper               | solution                              | version   |
| ---------------------- | ---------------------------- | -------------------- | ------------------------------------- | --------- |
| concave_hull           | ratio, allow_holes           | _delegate_geo_method | ignore index                          | 0.14      |
| delaunay_triangles     | tolerance, only_edges        | _delegate_geo_method | ignore index                          | 0.14      |
| offset_curve           | distance, quad_seqs...       | _delegate_geo_method | ignore index                          | 0.14      |
| remove_repeated_points | tolerance                    | _delegate_geo_method | ignore index                          | 0.14      |
| segmentize             | max_segment_length           | _delegate_geo_method | ignore index                          | 0.14      |
| force_3d               | z                            | _delegate_geo_method | ignore index                          | main      |
| buffer                 | distance...                  | _delegate_geo_method | raise for distance, ignore for others | 0.5       |
| simplify               | tolerance, preserve_topology | _delegate_geo_method | ignore index                          | shapely 2 |
| interpolate            | distance                     | _delegate_geo_method | raise                                 | 0.5       |

So we don't align in any case. We either raise or ignore the index. Ignoring the index does not feel as a correct behaviour because users may expect alignment, which silently does not happen resulting in misaligned args. I think that we have two options:

1. raise when the index is not equal like we do in buffer (for distance). This does not require any additional keywords and users can align themselves if needed. We can include a note on how in the error message.
2. add `align` keyword everywhere and mirror the behaviour of binary geometry ops.

Given most of the affected methods are from 0.14, I think we can just do the hard breaking change here, whatever we decide. I am leaning towards the first option as it is easier but if we want to do full consistency, the second is probably better.

I would also hold with merging of shapely parity PRs affected by this so I can update them based on the selected behaviour.

**Comment by m-richards** [comment]
I'm leaning towards option 1, because we should be able to give a nice instructive error for this (here's how to align, and here's how to convert to an array if you didn't want to align). Personally feel adding an align keyword (and remembering to add an align keyword for any future methods) doesn't provide enough convenience to warrant extra complexity (even if it's not super complex). 

From the perspective of a breaking change, I also like that we go from ignore -> raise, as then users need to deal with it in cases where it matters, vs ignore -> align (or align and and warn) by default which could be missed or ignored (appreciate not everyone would agree with that though)

**Comment by jorisvandenbossche** [comment]
Yes, also agreed to go with option 1. Adding an `align` keyword everywhere seems a lot of bloat for a corner case that users can solve themselves (either aligning manually first, or passing the `.values`), and in addition can also be ambiguous if there are multiple keywords where the value could be aligned or not.
