### ISSUE TITLE
Support file-like objects in to_file() and read_file()

### ISSUE THREAD

**Issue by timtroendle** [geopandas/geopandas#388]
[Similar to pandas write functions](http://pandas.pydata.org/pandas-docs/version/0.18.1/generated/pandas.DataFrame.to_csv.html) `GeoPandas.to_file()` should accept file-like objects. This would allow using `io.StringIO` or `tempfile.TemporaryFile` amongst others.

**Comment by jorisvandenbossche** [comment]
Yes, fully agree, and PRs are very welcome!

**Comment by timtroendle** [comment]
Had a quick look at that: unfortunately this is currently blocked by https://github.com/Toblerity/Fiona/issues/409, i.e. `fiona` is not supporting file-like objects.

**Comment by ResidentMario** [comment]
Actually, this appears to be possible to implement. See, well, the issue above, but also [this GIS Stack Exchange answer](http://gis.stackexchange.com/a/225589/74038).

It shouldn't be *too* hard, I think, to also wrap this fetch code so that `gpd.read_file` can real in URLs too (e.g. `pd.read_csv` does this RN, and it's very handy!)

However, in Toblerity/Fiona#409 @sgillies discusses porting `rasterio` in-memory files to `fiona`, and in a comment [here](http://gis.stackexchange.com/questions/225586/reading-raw-data-into-geopandas#comment348542_225589) removing this `BytesCollection` trick.

Maybe you can put that on a deprecation cycle? I think shimming this feature into `geopandas` using what exists now would be valuable, while that feature is being developed. We could have a working implementation using what's there now, and swap in an update using the new `fiona` funcs later. Is that a good idea?

**Comment by jdmcbr** [comment]
Closed by #1329
