### ISSUE TITLE
Make the "id" property in geodataframe.to_json() optional

### ISSUE THREAD

**Issue by dirkschneemann** [geopandas/geopandas#390]
Looking at the [GeoJSON specification](https://tools.ietf.org/html/rfc7946#section-3.2), one can see that the `id` property of a feature is optional. 

In the current implementation of [geodataframe.to_json()](http://geopandas.org/reference.html#GeoSeries.to_json), however, there is no choice whether one wants the `id` property being part of the output or not. Instead, it is always inserted as part of the [iterfeatures method](https://github.com/geopandas/geopandas/blob/master/geopandas/geodataframe.py#L294).

It would be convenient to optionally do something like `geodataframe.to_json(id=False)`, similarly to how one can already set `show_bbox=False` (which is default).

**Comment by sgillies** [comment]
@dirkschneemann the `id` member of a feature is optional, but only because the IETF's GeoJSON working group couldn't arrive at consensus on fixing the bug in the original spec. Feature ids can allow persistent identification of features and are a hallmark of good GeoJSON datasets. Consider Tim Berners-Lee's 5 star system for deployment of open data (http://5stardata.info/en/): without Feature ids, we can't get to number 4.

That said, I don't think the ids that iterfeatures() generates do allow persistent identification because they are just the row number in the data frame, right? Insert new rows, reserialize, and the ids have changed. Disabling ids that aren't meaningful could make sense.

**Comment by jorisvandenbossche** [comment]
@dirkschneemann PR welcome!

It would maybe also make sense to use the dataframe's index instead of the row number as the id.

**Comment by dirkschneemann** [comment]
Thank you for the clarification, @sgillies , I didn't know that before.
@jorisvandenbossche , can't do it right now but I'll see what's possible in the near future :+1:

**Comment by jdmcbr** [comment]
Closed by #1637
