### ISSUE TITLE
*Inquiry on Pull Request*  Function to Read zipped shapefile from disk or web and return geodataframe

### ISSUE THREAD

**Issue by linwoodc3** [geopandas/geopandas#441]
I made a function ([using functionality from this post](https://gis.stackexchange.com/questions/225586/reading-raw-data-into-geopandas/225627)) that can take a string, and load a zipped shapefile into a geopandas dataframe.  The string can be an HTTP link or a string to a file on disk.  The main point is, same function/method, but handles zipped shapefiles remotely or local.

Would geopandas benefit from having this?  I don't mind doing a pull request but want to know if it's worth it for the project.  

Here is a [working gist of my function](https://gist.github.com/linwoodc3/72b2f24b6d2ff6ffde1597f1ca2dea3f).  It's very simple, but just want to know if it would help the project.

**Comment by linwoodc3** [comment]
Aw man, you added it. Cool, wish I could have given it a go.  :-(.  Thanks for considering the concept.

**Comment by jdmcbr** [comment]
@linwoodc3 Thank you for the suggestion, and I'm sorry to have not replied earlier. One nice aspect of the PR that was eventually merged was that it changed internal logic to expand functionality, rather than creating a new standalone function. Anyway, future contributions to geopandas from you would certainly be welcome!

**Comment by jorisvandenbossche** [comment]
Yeah, sorry, it was at a code sprint and somebody was interested in it, so didn't hold him back (as I added it to the list of possible issues)
