### ISSUE TITLE
Faster data ingestion notes

### ISSUE THREAD

**Issue by mrocklin** [geopandas/geopandas#491]
With the Cython work happening at #473 I decided to look at data ingestion, which is the current performance bottleneck for many workloads now that other operations are fast.

Data ingestion seems to be handled well by the GDAL/OGR library, which handles reading and writing to many formats in a uniform way.  Currently there are a few ways of using this library:

1.  From GDAL/OGR itself, which is a C++ library
2.  From the C API of this library
3.  From Fiona, which wraps functions in Python/Cython, but generally emits one feature at a time as Python objects, and so can be slow
4.  From `osgeo.ogr` which is an unfortunately faithful rendition of the C++ API in Python.  This uses Swig, and also operates in a row-by-row manner

Typically we've used the C API wrappers of underlying libraries (this is what we did for GEOS) and that might be feasible again here as well.  Unfortunately, I'm unable to find a C-wrapper function for the [OGRGeometry::exportToGEOS](http://www.gdal.org/classOGRGeometry.html#a2ea594db36b7281f73242273e22d62c2) function (OGR has its own geometry type).  However, looking briefly at the [source code](https://github.com/nasa/World-Wind-Java/blob/master/GDAL/GDAL-1.7.2/ogr/ogrgeometry.cpp) it looks like it's just round-tripping through WKB serialization, to which we do have access.

The API to OGR is unpleasant, but is straightforward so this seems to be a sensible approach.

I don't have a sense for how much faster/slower this will be over the current fiona implementation.  @sgillies do you have any intuition here?  Or any advice on how hard/annoying this process is likely to be?

I'm also curious about database ingestion.  GDAL claims to support reading/writing from/to PostGIS, which I notice has been an issue lately.  I have no idea how (if?) it handles authentication but I'm curious if some GeoPandas issues can be handled just by relying on Fiona (or whatever we build here) more carefully.

**Comment by jorisvandenbossche** [comment]
@mrocklin thanks for the exploration!

Some general thoughts:

- I would be very hesitant to start interfacing on the C/cython level to GDLA/OGR ourselves (in geopandas, for additional complexity/maintenance reasons)
- It would be interesting to explore how much performance improvement could be gained from writing a specialized "fiona Collection to new GeometryArray based GeoDataFrame" converter (fiona indeed emits one record at a time as dicts. Currently those are converted using `GeoDataFrame.from_features` under the hood, which converts to shapely objects, and this step could be optimized). 
  Potentially this already improves performance, using the current fiona bindings to OGR.
- Would `fiona` be interested in gaining some functionality to emit full arrays instead of single records? 
  - For points this can be rather straightforward I think, but eg for Polygons less so. As the number of coordinates varies, the numpy array has to be object dtype, probably removing part of the possible performance gains

> I'm also curious about database ingestion

Currently reading from postgresql/postgis can return WKB. It might be sufficient to have a more efficient conversion of a columns with WKB elements to a GeometryArray to boost performance? (and I suppose this functionality to convert WKB -> GeometryArray actually is already present in the geopandas-cython branch)

**Comment by mrocklin** [comment]
> I would be very hesitant to start interfacing on the C/cython level to GDLA/OGR ourselves (in geopandas, for additional complexity/maintenance reasons)

We're already depending on this library being around.  I'm not overly concerned about touching its C-API.  I don't think that this is particularly dangerous.

That being said, if Fiona is near full-speed then that sounds great.  My expectation was that was this wasn't likely to be the case, but I'd be happy to be surprised.

**Comment by jorisvandenbossche** [comment]
> I'm not overly concerned about touching its C-API. I don't think that this is particularly dangerous.

Not saying it would necessarily be dangerous, but when looking at the cython code of fiona (https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext2.pyx), I would be hesitant to have to replicate part of this complexity (dealing with encodings, managing the schema, ...). 
Just to say that if there is a possibility to either use fiona as is or fiona with some additional features to expose data column-like instead of record-like, this would be my preference.

> That being said, if Fiona is near full-speed then that sounds great. My expectation was that was this wasn't likely to be the case, but I'd be happy to be surprised.

BTW, this is also my expectation. I would suppose going through the fiona dict-like records iteration will have a considerable performance overhead if you want to access the full data at once.

**Comment by mrocklin** [comment]
Yeah, I can imagine reusing a lot of the code there to determine schemas.

**Comment by jorisvandenbossche** [comment]
I quickly profiled the current geopandas `read_file` function, and (for a specific small shapefile, the nybb one), ca 80% of the time the function takes is spent by the shapely `shape` method to construct the geometries. So it seems also with the current fiona, an already nice performance improvement can be obtained.

**Comment by martindurant** [comment]
The following functions should be all that are required:
- OGR_L_GetFeatureCount and OGR_L_GetNextFeature in ogr_api.h (GDAL)
- Fiona's existing open file and list layers API is probably fine; the schema attribute gives list of column names/dtypes appropriate for allocating arrays/data-frame (like in fastparquet). 
- FeatureBuilder.build() in Fiona's ogrext2.pyx shows how to extract fields (no need to build a Fiona geometry object)
- OGR_G_ExportToWkb in ogr_api.h (GDAL) with the geom handle from the above
- GEOSWKBReader_read in geos_c with the string from above

**Comment by jorisvandenbossche** [comment]
@martindurant Thanks for the exploration. Are you planning to do some actual coding on this issue? 
I also opened on issue on the fiona tracker about improvements there that could help this: https://github.com/Toblerity/Fiona/issues/469

**Comment by martindurant** [comment]
I am happy to to wait to see if people at Fiona have anything to say on the matter, but I think solving this would be fun.

**Comment by jorisvandenbossche** [comment]
We don't necessarily need to wait, as a proof of concept can certainly be made outside of fiona, and then we can still see whether fiona wants to accept the needed parts of it or we fully include it in geopandas (and a proof of concept with nice improvements can also be a nice showcase of the usefulness to include it in fiona)

**Comment by martindurant** [comment]
I made a start, but actually didn't get anything working yet: https://github.com/martindurant/Fiona/commit/ea7a60e9c6635c8eec49cea005522ce981775918 (the WKBReader doesn't get allocated, presumably because I'm passing the geos context handle incorrectly).

**Comment by martindurant** [comment]
There is not reason this has to live inside Fiona, but it seems to me to make use of the Session which Fiona normally uses to iterate over features.

**Comment by jorisvandenbossche** [comment]
Matt already implemented something using the WKBReader in geopandas:

https://github.com/geopandas/geopandas/blob/43546c47da5baec4de506aa8ba95f301acd1cd55/geopandas/vectorized.pyx#L1050-L1056

but I don't directly see the difference with what you do to create the reader.

**Comment by jorisvandenbossche** [comment]
@brendan-ward is experimenting with this at https://github.com/brendan-ward/pyogrio/

**Comment by martinfleis** [comment]
Pyogrio is reach 0.4.0 release and with #2225 will be accessible from geopandas directly. Vast majority of what is discussed here will be then resolved. Thanks all!
