### ISSUE TITLE
Column types changes in sjoin

### ISSUE THREAD

**Issue by rutgerhofste** [geopandas/geopandas#519]
when spatially joining two gdfs the column datatype is not preserved (int64->float):

`gdfJoined = gpd.sjoin(gdf1, gdf2, how="left", op='intersects')`

**Comment by jdmcbr** [comment]
@rutgerhofste I took a look at this, and saw this behavior when doing the join on, say, the left frame meant the inclusion of NaN entries in columns from the right frame when there was no element in the right frame on which to join. I was not otherwise able to produce this type promotion. This is known behavior (if perhaps still surprising to a user); see https://pandas.pydata.org/pandas-docs/stable/gotchas.html#nan-integer-na-values-and-na-type-promotions for more details. If you have an example of this type change occurring in a different situation, please provide a small example showing this. Otherwise, I'll close this.

**Comment by rutgerhofste** [comment]
Hi James, I think you are right. This behavior is similar to pandas and makes sense from a datat type perspective since you want to be able to store the NaNs. Thanks and you can close this

**Comment by mrocklin** [comment]
@rutgerhofste you can also close issues that you have opened.
