### ISSUE TITLE
Have GeoSeries return regular Series if not geo-like

### ISSUE THREAD

**Issue by jtratner** [geopandas/geopandas#53]
I.e. `GeoSeries([1.0, 2.0, 3.0])` return `Series([1.0, 2.0, 3.0])`. That way you don't have to decide whether to use GeoSeries or Series in operations. Very simple to implement if this is something people want.  Related question - how do you validate that something is  geo-like?

**Comment by IamJeffG** [comment]
I think we could take the performance penalty only on initial `GeoSeries` instantiation via the public API: i.e. a call to the `GeoSeries(...)` constructor or classmethods like `GeoSeries.from_file`.  And also when setting a `GeoDataFrame`'s geometry column, again via the public API.

Methods that internally create a GeoSeries from another GeoSeries wouldn't have to do further type validation, since the source GeoSeries had been type checked already.  Examples are some methods on  a `GeoPandasBase` (e.g. `_geo_unary_op`, `_geo_op`, `representative_point`, ...).  They could create the new `GeoSeries` using a private constructor that skips validation and its performance hit.

To @jtratner's initial question: the convenience to use `GeoSeries` where I really meant `Series` doesn't have much value; actually I would appreciate a warning when creating a GeoSeries from non-geoms.  Personally, I'd find a `is_geo` method on a GeoSeries to be redundant.

**Comment by jorisvandenbossche** [comment]
Now we have the pandas ExtensionArray under the hood, the performance implication of needing to check and validate all elements to be a geometry, is only done on initial creation of the GeometryArray. The operations that we know do not return geometry data also don't have to such check. 

So I deprecated the behaviour of letting GeoSeries fall back to Series when non-geometry data are passed. See https://github.com/geopandas/geopandas/pull/1085
