### ISSUE TITLE
Access to Fiona's crs_wkt and/or meta attributes when using read_file() 

### ISSUE THREAD

**Issue by cratcliff** [geopandas/geopandas#543]
I have a shapefile which I open in geopandas using read_file(). It is in GDA94 mga54 (epsg: 28354).
In geopandas it will print the crs attribute as 
```
import geopandas as gpd
source_gdf = gpd.read_file('c:\data\test\boxes_gda94mga54.shp')
print source_gdf.crs
{u'zone': 54, u'ellps': u'GRS80', u'no_defs': True, u'proj': u'utm', u'units': u'm', 'wktext': True, u'south': True}`
```
When opening in Fiona and printing the coordinate information using the meta attribute it produces 
```
import fiona,pprint
source_fio = fiona.open('c:\data\test\boxes_gda94mga54.shp')
pprint.pprint (source_fio.meta)
{'crs': {u'ellps': u'GRS80',
         u'no_defs': True,
         u'proj': u'utm',
         u'south': True,
         u'units': u'm',
         u'zone': 54},
 'crs_wkt': u'PROJCS["GDA94_MGA_zone_54",GEOGCS["GCS_GDA_1994",DATUM["Geocentric_Datum_of_Australia_1994",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",141],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",10000000],UNIT["Meter",1]]',
 'driver': u'ESRI Shapefile',
 'schema': {'geometry': 'Polygon',
            'properties': OrderedDict([(u'Id', 'int:10'), (u'float_area', 'float:13.11'), (u'double_Len', 'float:19.11'), (u'short_id', 'int:10'), (u'Long_vert', 'int:10'), (u'Date_Creat', 'date'), (u'part_type', 'str:50')])}}
```

If I then save the file using geopandas to_file() without transforming/re-projecting then look at projection attributes of the saved file using Fiona's meta again it produces a different crs_wkt result when compared with the above.

```
source_gdf.to_file('c:\data\test\boxes_gda94mga54_copy.shp',driver="ESRI Shapefile")

new_fio = fiona.open('c:\data\test\boxes_gda94mga54_copy.shp')
pprint.pprint (new_fio.meta)
'crs': {u'ellps': u'GRS80',
         u'no_defs': True,
         u'proj': u'utm',
         u'south': True,
         u'units': u'm',
         u'zone': 54},
 'crs_wkt': u'PROJCS["UTM_Zone_54_Southern_Hemisphere",GEOGCS["GCS_GRS 1980(IUGG, 1980)",DATUM["unknown",SPHEROID["GRS80",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",141],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",10000000],UNIT["Meter",1]]',
 'driver': u'ESRI Shapefile',
 'schema': {'geometry': 'Polygon',
            'properties': OrderedDict([(u'Id', 'int:9'), (u'float_area', 'float:24.15'), (u'double_Len', 'float:24.15'), (u'short_id', 'int:9'), (u'Long_vert', 'int:9'), (u'Date_Creat', 'str:80'), (u'part_type', 'str:80')])}}

```
Is there a way when using geopandas read_file() to store or access the crs_wkt or meta attribute that could then then be used as a parameter in to_file() to correctly assign the original projection to the output file?

**Comment by jdmcbr** [comment]
Yes, I think that should be relatively straightforward to do. Are you interested in taking a shot at it yourself?

**Comment by cr29** [comment]
Unfortunately I don't think I have the experience to be able to make this change. I am happy to either provide test files, and/or help with testing.

It would also be nice to be able to use the crs_wkt string as an input the to_crs() function as well, and return the new crs_wkt string.  The ESRI generated _"GDA94_MGA_zone_54"_ string shown above doesn't contain the EPSG number, and doesn't use the same keywords as the official EPSG database so finding the correct EPGS number can be problematic. Being able use the crs_wkt from an existing dataframe would help.

**Comment by jorisvandenbossche** [comment]
The general problem is that the representation `pyproj` uses (the proj4 string), is not a format that contains all possible information (only the minimal to do coordinate transforms), and thus is not necessarily roundtrippable. 
So unless we start saving the `crs_wkt` as well on all operations and crs conversions, it is not possible to do this in general. And this is not that a straightforward change I think (certainly for crs conversions, as pyproj (what we currently use) does not support wkt).

As a workaround for now, *I think* (did not try) you can do the following:

```
source_gdf = gpd.read_file('c:\data\test\boxes_gda94mga54.shp')
source_crs_wkt = fiona.open('c:\data\test\boxes_gda94mga54.shp').meta['crs_wkt']

source_gdf.to_file('...', driver="ESRI Shapefile", crs_wkt=source_crs_wkt)
```

I think this should work because `fiona.open` supports this `crs_wkt` keyword, and the `to_file` kwargs are passed to fiona.open.

**Comment by jdmcbr** [comment]
Aha, I didn't realize `pyproj` didn't support WKT. Sorry @cr29 for the misleading comment. @jorisvandenbossche I had tested the workaround that you wrote above (which did work for the example I'd tried), and thought it would be a matter of incorporating that logic in `read_file` and `to_file` and paying attention to `crs_wkt` in the `to_crs` functionality.

**Comment by cr29** [comment]
Thanks @jdmcbr and @jorisvandenbossche  for the advice. I have tested the workaround and it does work. 

I still think it would be beneficial to have access to a crs_wkt (and maybe epsg as well) as a reference and continue with the proj4 string for conversions. Its easy enough to convert epsg & crs_wkt to proj4 by using GDALs SpatialReference methods which is a dependency of Fiona. This will then provide a more detailed description of the data frames coordinate system to the user when it changes or becomes disconnected from the source.

I am keen to use pandas and geopandas for a project i'm working on which will manipulate and analyze data coming from various sources (shapefiles and csv’s). The analysis will include several datasets and projections to perform multiple geometry operations (buffering, overlays etc) and column calculations, and I will end up with multiple geodataframes so it would be good if the crs_wkt attribute were attached to the data frame rather than managed through separate variables or a custom class.

**Comment by martinfleis** [comment]
This seems to be fixed by using pyproj.CRS under the hood to store CRS information. Roundtrip correctly returns `GDA94 / MGA zone 54`, not `UTM_Zone_54_Southern_Hemisphere` anymore.
