### ISSUE TITLE
Impoved reading and writing from/to PostGIS (SQL in general?) support

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#595]
Currently we only have a very basic `read_postgis` function, and we certainly want a write function as well (https://github.com/geopandas/geopandas/issues/189). But, we currently also have some different open (overlapping) PRs and issues related to improving the IO support for PostGIS. Therefore I thought to open a new general issue to get some overview.

Open PRs:

* https://github.com/geopandas/geopandas/pull/440 PR adding to_postgis
* https://github.com/geopandas/geopandas/pull/457 PR with both read/write for postgis
* https://github.com/geopandas/geopandas/pull/546 PR to use geoalchemy in from_postgis
* one not related to postgis: https://github.com/geopandas/geopandas/pull/101 PR to add support for sqlite

Does somebody have an insight in what the main differences are between the postgis PRs? How to proceed with those?

Some questions related to this that we might need to answer:

* Do we want to use geoalchemy (https://geoalchemy-2.readthedocs.io/en/latest/)? (and thus add it as an optional requirement) What does it bring?
* Can we actually support more than PostGIS? More general SQL support? (https://github.com/geopandas/geopandas/issues/490) Eg also MySQL has spatial data data types (https://dev.mysql.com/doc/refman/5.7/en/spatial-datatypes.html) But eg geoalchemy does not seem to support that.
* Naming of the functions (https://github.com/geopandas/geopandas/issues/161): currenlty `GeoDataFrame.from_postgis` and `read_postgis`. Depending on the question above, we might want to make it more general (`read_sql`, `to_sql`). Personally I would retire the 'from_postgis' for `read_postgis` (or `read_sql`) anyhow.

There is some relevant discussion in https://github.com/geopandas/geopandas/issues/161 as well.

Other related issues: https://github.com/geopandas/geopandas/issues/451 on adding SRID support in `read_postgis`

cc @jdmcbr @dimitri-justeau @showjackyang @adamboche @kuanb @emiliom @perrygeo @carsonfarmer

**Comment by jorisvandenbossche** [comment]
cc @carsonfarmer

**Comment by jdmcbr** [comment]
@jorisvandenbossche Well, my answer is biased, but not being aware of significant advantages `geoalchemy2` would provide, I'd be inclined to keep the `geopandas` writing functionality a little lighter weight. That said, if someone were to point out some real advantages of `geoalchemy2`, my opinion would likely change.

I don't have any personal experience with spatial MySQL, but if someone has a test database set up they'd be willing to give access to, I'd be happy to try to connect with `geopandas` and see what breaks.

I'm fine with retiring `from_postgis`. I remembering finding the pandas choice regarding `to` and `read` slightly unintuitive at first, but we might as well be consistent with that standard.

**Comment by mrocklin** [comment]
I'm curious, GDAL / OGR must offer PostGIS support.  Why does GeoPandas not
rely on it?  Does it not support actual queries?

**Comment by jdmcbr** [comment]
@mrocklin I would guess mainly that tacking light geometry handling on top of `pandas` SQL support offered roughly the same capabilities with considerably less work. I've never looked seriously into using GDAL for postGIS access, but I don't see anything at http://www.gdal.org/drv_pg.html that pops out as motivating a move to rely on GDAL.

**Comment by mrocklin** [comment]
We generally rely on GDAL through the fiona Python library.  My comment
above might be better interpretted by replacing all cases of GDAL with
fiona.

**Comment by jdmcbr** [comment]
Well, the fiona manual has this to say: "If your data is in a RDBMS like PostGIS, use a Python DB package or ORM like SQLAlchemy or GeoAlchemy. Maybe you’re using GeoDjango already. If so, carry on."

**Comment by mrocklin** [comment]
Well then that solves it :)

**Comment by dimitri-justeau** [comment]
Hello everyone, sorry I am answering a bit late to this topic, I have been very busy lately.

Here are the reasons of my choice to rely on `geoalchemy2`:

- Pandas relies on sqlalchemy for its `to_sql` method. The advantage is that Pandas does not have to worry about building sql statements. It just binds a dataframe's datatypes to sqlalchemy's datatypes. I think that this strategy is a good one since each library deals with what it had been designed for: pandas with dataframes, sqlalchemy with RDBMs. If new backends are supported by sqlalchemy, they are automatically available within Pandas, as well as API changes.

- I wanted to keep close to this approach, since geoalchemy2 provides an abstraction layer over PostGIS datatypes. If the code I added in https://github.com/geopandas/geopandas/pull/546 can seems a lot, it is actually more or less a replication on what exists in Pandas. I just had to fully rewrite some methods of the subclassed objects to use the appropriate object types.

@jdmcbr Your approach in https://github.com/geopandas/geopandas/pull/440 is in fact much simpler and does not introduce a new dependency, but is also in its current state more limited. In fact, in the PostGIS tables that are created, the geometry type is just `geometry`, without any SRID information. The SRID could be easily informed relying on EWKT instead of WKT (c.f. https://github.com/geopandas/geopandas/pull/546). The datatypes could also be inferred the same way I did subclassing the SQLTable to GeoSQLTable.

From this point, I think that the choice to rely on geoalchemy2 or not is mainly a design decision since the same functionalities could be achieved with both approaches.

Cheers,

Dim'

**Comment by jorisvandenbossche** [comment]
Would using `geoalchemy2` take care of updating the "geometry_columns" table in postgis?

**Comment by snowman2** [comment]
This looks promising: https://github.com/awburgess/geopandas-postgis/issues/7

**Comment by HTenkanen** [comment]
Hi all, 

I find using the GeoAlchemy sometimes frustratingly slow, especially if there is a need to upload a large number of rows (e.g. millions). For large bulk uploads, I implemented following that might be of use to someone: 

```
def copy_to_postgis(gdf, engine, table, if_exists='fail', geometry='geometry', 
                    srid=4326, schema='public', dtype=None):
    """
    Fast upload of GeoDataFrame into PostGIS database using COPY. 
    
    Parameters
    ----------
    
    gdf : GeoDataFrame
        GeoDataFrame containing the data for upload.
    engine : SQLAclchemy engine.
        Connection.
    if_exists : str
        What to do if table exists already: 'replace' | 'append' | 'fail'.
    geometry : str
        Column name for storing the geometries in the db.
    srid : int
        Spatial Reference ID (epsg: code) of the input data.
    schema : db-schema
        Database schema where the data will be uploaded (optional).
    dtype : dict of column name to SQL type, default None
        Optional specifying the datatype for columns. The SQL type should be a 
        SQLAlchemy type, or a string for sqlite3 fallback connection.
    """
    
    conn = engine.raw_connection()
    cur = conn.cursor()
    
    # Create table creation schema (ignore 'geometry')
    # If dtypes is used, update table schema accordingly.
    table_schema = pd.io.sql.get_schema(frame=gdf.drop(geometry, axis=1), name=table, dtype=dtype).replace('\n', '')
    
    # Add geometry column
    table_schema = table_schema[:-1] + ', "{geometry}" GEOMETRY)'.format(geometry=geometry)
    
    # Check if table exists
    if pd.io.sql.has_table(table_name=table, con=conn, schema=schema):
        # If it exists, check if should overwrite    
        if if_exists == 'replace':
            cur.execute("DROP TABLE {table}".format(table=table))
            cur.execute(table_schema)
        elif if_exists == 'fail':
            raise Exception("Table {table} exists in the database.".format(table))
        elif if_exists == 'append':
            pass
    else:
        cur.execute(table_schema)
    
    # Convert geometry to wkt
    gdf[geometry] = gdf[geometry].apply(lambda geom: geom.wkt)
    
    # Create file buffer
    buffer = io.StringIO()
    gdf.to_csv(buffer, sep='\t', index=False, header=False)
    buffer.seek(0)

    try:
        cur.copy_from(buffer, table, sep='\t', null='')
        cur.execute("SELECT UpdateGeometrySRID('{schema}', '{table}', '{geometry}', {epsg})".format(schema=schema, table=table, geometry=geometry, epsg=srid))
        conn.commit()
    except Exception as e:
        conn.connection.rollback()
        conn.close()
        print(e)
    conn.close()
```

It's not perfect yet, but does the basic things quite efficiently.

**Comment by jorisvandenbossche** [comment]
@HTenkanen thanks a lot for reviving this! 

Yes, the `to_sql` is known to be slow due to going row by row through Python. I think many people are using the COPY approach with csv to have a faster solution. In pandas we are somewhat hesitant to add functionality specific to a certain database (that might open a can of worms, sqlalchemy gives us this database agnostic approach). But for GeoPandas, given the special status of Postgis, it probably makes sense to actually look into specific approaches that are faster.

Some questions / remarks

- Pandas has a `method` argument in `to_sql` that allows one to use COPY FROM approach as well (see https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#insertion-method). It would be interesting to see if that could be used. Although a potential problem is that there you get an iterator over the data, instead of the actual data (so can't directly use `to_csv`, but would need to do a timing to see if that gives a slowdown)
- Can Postgis also read CSV data where the geometries are stored as (hex) WKB instead of WKT? (if so, that should be faster)
- The `get_srid_from_crs` will be able to be improved once we use the new pyproj.CRS interface (see https://github.com/geopandas/geopandas/issues/1003)
- It might be interesting to time the different parts of your function above to see where the remaining bottlenecks are. Is it mainly the actual copy to postgres, or also some of the preprocessing? It might be possible (certainly in light of https://github.com/geopandas/geopandas/issues/1155) to further optimize some of the preprocessing steps.

**Comment by HTenkanen** [comment]
@jorisvandenbossche Thanks for your comments! I will make some tests based on these ideas, and report back with more detailed profiling of the different parts of the code 👍 Ah, the new pyproj CRS class seems superb! Is the plan to introduce this new class into Geopandas soon? It definitely would make life a lot easier. :)

**Comment by Sangarshanan** [comment]
Hey, I was looking to revive this again and maybe help out/ contribute in any way possible

I worked on the above mentioned points, converting geometries to wkb and used to the to_sql copy method, borrowed from `psql_insert_copy` and `copy_to_postgis` defined above 

```python
def get_geometry(data):
    if len(set(list(data.geom_type))) == 1:
        dtype = {'geometry' : Geometry(geometry_type= data.geom_type[0].upper())}
    else:
        return "Multiple dtypes !!!!"
    return dtype

def insert_to_postgis(data, con, table_name ,schema=None, dtype=None,
                      index=False,if_exists='replace'):

    data = data.copy()
    dtype = get_geometry(data)
    # borrowing from HTenkanen 
    srid = get_srid_from_crs(data)
    geom_col = data._geometry_column_name
    # convert geometries to wkb
    data[geom_col] = data[geom_col].apply(lambda x: dumps(x, hex=True))
    dbapi_conn = con.raw_connection()
    cur = dbapi_conn.cursor()

    pandas_sql = pd.io.sql.SQLDatabase(con)
    tbl = pd.io.sql.SQLTable(name=table_name, pandas_sql_engine=pandas_sql, 
                             frame=data, dtype=dtype, index=index)

    args = [list(data[i]) for i in data.columns]
    if index:
        args.insert(0,list(data.index))
    # generator of list (borrowed from pandas)
    data_iter = zip(*args)

    # Check if table exists (from HTenkanen)
    if tbl.exists():
        # If it exists, check if should overwrite    
        if if_exists == 'replace':
            pandas_sql.drop_table(table_name)
            tbl.create()
        elif if_exists == 'fail':
            raise Exception("Table '{table}' exists in the database.".format(table=table_name))
        elif if_exists == 'append':
            pass
    else:
        tbl.create()

    # get list of columns using pandas
    keys = tbl.insert_data()[0]
    columns = ', '.join('"{}"'.format(k) for k in list(keys))
    # borrowed from https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#insertion-method
    s_buf = StringIO()
    writer = csv.writer(s_buf)
    writer.writerows(data_iter)
    s_buf.seek(0)

    sql = 'COPY {} ({}) FROM STDIN WITH CSV'.format(
        table_name, columns)
    cur.copy_expert(sql=sql, file=s_buf)
    cur.execute("SELECT UpdateGeometrySRID('{table}', '{geometry}', {srid})".format(
    schema=schema, table=table_name, geometry=geom_col, srid=srid))

    dbapi_conn.commit()
    cur.close()
```
Comparison 

```
In [1]: data = gpd.read_file(
'https://raw.githubusercontent.com/ebrelsford/geojson-examples/master/brooklyn.geojson').explode(

In [2]: %timeit insert_to_postgis(data, table_name='test', con=con, if_exists='replace', index= None)
13.2 s ± 236 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]: %timeit copy_to_postgis(data, table='test', engine=con, if_exists='replace', index= None)
13.6 s ± 421 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Appreciate feedback / suggestions to start

**Comment by HTenkanen** [comment]
Hi @Sangarshanan and thanks for reviving this and your contributions! 👍 

I now finally had time to get back to this and I went through your edits @Sangarshanan and included them to this Gist:
https://gist.github.com/HTenkanen/3b214be899f0d3885bad48577de48150

I left some of the earlier parts as they were, so that the function is able to handle mix between single vs multi-geometries automatically (e.g. mix between Polygon and MultiPolygon).

@jorisvandenbossche: I now also updated the CRS reading using the new pyproj CRS class so it should work now quite nicely with different types of CRS information. In addition, I now tested swapping from shapely.wkb to pygeos.wkb as it also provided some improvements on the performance.

I did some time profiling on the different parts (see [GIST](https://gist.github.com/HTenkanen/3b214be899f0d3885bad48577de48150)) and currently the performance is as follows:

### With Pygeos WKB:

```
In [1]: data = gpd.read_file("https://gist.githubusercontent.com/HTenkanen/456ec4611a943955823a65729c9cf2aa/raw/be56f5e1e5c06c33cd51e89f823a7d770d8769b5/ykr_basegrid.geojson")
In [2]: engine = create_engine("postgresql+psycopg2://myuser:mypwd@localhost:5432/mydb")
In [3]: %timeit copy_to_postgis(data, engine, table='ykr_test', if_exists='replace')
717 ms ± 58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
And this is how long different parts take:
```
'get_srid_from_crs'  0.01 seconds
'get_geometry_type'  0.02 seconds
'convert_to_wkb'  0.13 seconds
'write_to_db'  0.55 seconds
'copy_to_postgis'  0.77 seconds   # In total
```

### With Shapely WKB

In [2]: %timeit copy_to_postgis(data, engine, table='ykr_test', if_exists='replace',  schema=None, dtype=None, index=True)
874 ms ± 44.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

And this is how long different parts take:
```
'get_srid_from_crs'  0.01 seconds
'get_geometry_type'  0.02 seconds
'convert_to_wkb'  0.26 seconds
'write_to_db'  0.50 seconds
'copy_to_postgis'  0.86 seconds  # In total
```

So as we can see, using the Pygeos instead of Shapely is twice as fast, and now most of the time goes to actually writing the data into the database which is normal. 

Couple of questions for @jorisvandenbossche :

- I have understood that the Pygeos things will eventually be integrated into Shapely. But I guess that might still take some time, so should we continue with this Pygeos approach, i.e. converting geometries from shapely to pygeos, and then those to wkb? Or should we stick with normal Shapely wkb-dumps for now, as this would naturally bring a new dependency to Geopandas? What are the current thoughts about integrating Pygeos to Geopandas?

- I guess the most logical place to add this `to_postgis()` -functionality would be in the `..geopandas/io/sql.py` -file, would you agree? 

- Any recommendations / ideas about how we should test these functionalities? I see that for testing the reading from PostGIS, you have the `create_postgis()` -function that populates a `test_geopandas` database. I guess we could take a similar approach here and test that populating the nybb data works with the `to_postgis()` function?

**Comment by HTenkanen** [comment]
@jorisvandenbossche @martinfleis @snowman2:

I have now implemented a method `GeoDataFrame.to_postgis()` for writing data from GeoDataFrame to PostGIS. 
You can check it from this fork: https://github.com/HTenkanen/geopandas

It now supports all the same functionalities as Pandas, i.e. you can also use "replace" and "append" when pushing the GeoDataFrame to PostGIS. When appending, the crs of the GeoDataFrame and the target table needs to match. When writing it uses `copy_expert` under the hood as suggested by @jorisvandenbossche and kindly written by @Sangarshanan. For checking the CRS from the GeoDataFrame, it now uses the new `pyproj.CRS` -class, which works quite nicely for extracting the epsg-code (although I needed to lower the `min_confidence` to 25 when parsing the epsg with `CRS.to_epsg()` -function.)

All the tests are passing (locally), and I wrote a few basic tests for the `write_postgis()` functionality into [test_sql.py](https://github.com/HTenkanen/geopandas/blob/master/geopandas/io/tests/test_sql.py). For testing, I used the same `nybb` dataset that was also used with some other tests.

There are few things that I think would be good to discuss before making a PR from this.

- This functionality brings a new (optional) dependency to geopandas: [GeoAlchemy2](https://geoalchemy-2.readthedocs.io/en/latest/). **Are we okay with this?** This package cannot be found from conda `defaults` channel, so from the current environments only the `conda-forge` yml works. Which made me thinking that should the `37-dev.yaml` also include `conda-forge` channel? Or is there a specific reason to include only `defaults` channel there?
- I now used `pygeos` for converting shapely geometries to wkb (which is another new dependency). I implemented it as optional, and if the pygeos cannot be imported OR the GEOS versions between shapely and pygeos do not match, it will use the wkb-dumps from shapely. **Do we want to keep this like this?** It's a bit hackish as currently the pygeos even needs to be built from master (PYPI v0.5 of pygeos does not yet have the `from_shapely` -function that @jorisvandenbossche wrote). 
  - For installing the pygeos from master in travis, I added a `PYGEOS` flag to [.travis.yml](https://github.com/HTenkanen/geopandas/blob/master/.travis.yml#L15) so that pygeos will be installed from pygeos source during `37-latest-conda-forge.yaml` environment. This is not needed if/when the new version of pygeos will be released, as this can be added to the yml-file. @jorisvandenbossche Any idea when this might happen?

Any comments and all the feedback is very welcome. 🙂  I try to finish this now as soon as possible.

**Comment by martinfleis** [comment]
@HTenkanen Great job! Few notes from me. 

`pyproj.CRS` will be used as GeoDataFrame.crs from next release (#1101), so we will be able to clean those conditions then. 

I am fine with GeoAlchemy2, it is a pure python package installable from PyPI. Recent GeoPandas in not available on defaults either. @jorisvandenbossche will be able to tell more about the channels support.

The plan was to use pygeos under the hood within geopandas anyway (#1155), but I am not sure what is the current situation after the decision to merge pygeos with shapely. I am not very keen to use the logic you implemented, but once this pygeos/shapely/geopandas relation will be clearer we might come up with a simpler way.

**Comment by HTenkanen** [comment]
@martinfleis Do you have an idea when the next release is aimed to be rolled out? And has the features for that release already been locked, or could this be able to fit for that release as well?

I agree that the current pygeos implementation is quite a hack and maybe it would be better to wait and go purely with shapely for now until things are settled between pygeos/shapely/geopandas. :+1:

**Comment by martinfleis** [comment]
@HTenkanen The date have not been set nor the feature list. This should certainly be part of the next release. I think best would be to open a PR now, we can discuss detail there.

Yes, I would probably go with shapely now, assuming that shapely itself will get pygeos boost at one point, so we don't have to deal with it here.

Re GeoAlchemy, add it to pip install to non conda-forge envs.

**Comment by HTenkanen** [comment]
@martinfleis Okay, great 👍 I will remove the `pygeos` parts from the codes and then make a PR from this, so we can continue from there. 

> Re GeoAlchemy, add it to pip install to non conda-forge envs.

Ah true, I'll do that.
