### ISSUE TITLE
geodesic parameter in geopandas

### ISSUE THREAD

**Issue by rutgerhofste** [geopandas/geopandas#634]
I am trying to use geopandas to store a google earth engine feature. Earth engine feature geometries have a geodesic (boolean) parameter: https://developers.google.com/earth-engine/geometries_planar_geodesic 

I struggle handling this geodesic paramater in geopandas. Geopandas has the .crs attribute but when I plot a geodesic crs (4326) (gdf.plot() or folium) the result is a square geometry instead of a geodesic one. 

also, when exporting the geoDataFrame to geoJSON, there is no geodesic parameter in the geoJSON:

Example geoJSON from an earth engine feature:
{u'type': u'Polygon', u'geodesic': True, u'coordinates': [[[-170.0, -80.0], [-170.0, 80.0], [170.0, 80.0], [170.0, -80.0], [-170.0, -80.0]]]}

Same from a geoDataFrame.to_json():
{"type": "Polygon", "coordinates": [[[-170.0, -80.0], [-170.0, 80.0], [170.0, 80.0], [170.0, -80.0], [-170.0, -80.0]]]}

is there a way to specify this geodesic parameter in geopandas and should it influence the plotting behavior?

**Comment by martinfleis** [comment]
This is a limitation of `shapely`, which supports only planar geometry. In pure GeoPandas, you will not be able to plot geodesic polygon. 

However, we do store the information that the geometry is geodesic in CRS. So once you export to JSON, this information is in CRS rather than in individual geometries.
