### ISSUE TITLE
geopandas.plotting.plot_point_collection

### ISSUE THREAD

**Issue by JPelda** [geopandas/geopandas#635]
geopandas.plotting.plot_point_collection(ax, shapely.geometry.Point(1,2))

x = geoms.x.values
y = geoms.y.values
, line 193, in plot_point_collection
    x = geoms.x.values
AttributeError: 'float' object has no attribute 'values'

geopandas.plotting.plot_point_collection(ax, [shapely.geometry.Point(1,2), shapely.geometry.Point(3,3)])

line 193, in plot_point_collection
    x = geoms.x.values

AttributeError: 'list' object has no attribute 'x'

**Comment by jdmcbr** [comment]
@JPelda I've generally understood `plot_point_collection` as a primarily internal method, since they're only designed for use in plotting geoseries and geodataframes, and both those objects have a `plot` method defined (which internally calls `plot_point_collection`, if applicable). I suppose we might prepend `_` to the function name to make that clearer. Or raise a more explicit error when you try to do what you did above. If you're just looking to figure out how to plot geometries, you should first create a geodataframe or geoseries, and then use their `plot` method (see http://geopandas.readthedocs.io/en/latest/set_operations.html for an example).

**Comment by jorisvandenbossche** [comment]
Yes, those methods take a GeoSeries, not a single geometry or list of geometries.

The question is a bit to what extent those plot_.._collection functions can be useful apart from the .plot()` method. I am not really sure if there is a good use case.
