### ISSUE TITLE
Indexing with an empty series results in dropping all column info

### ISSUE THREAD

**Issue by WeatherGod** [geopandas/geopandas#685]
Ran into this problem while I was trying to work around the (recently fixed) problem of errors when loading an empty shapefile. I would then create a blank geodataframe and then pass it into a function which selects only the features within a bounding box:
```
import geopandas as gpd
import pandas as pd
from shapely.geometry import box
blankdata = \
            {'FIRENAME': pd.Series([], dtype=np.dtype('O')),
             'STATE': pd.Series([], dtype=np.dtype('O')),
             'ACRES': pd.Series([], dtype=np.dtype('int64')),
             'CONTAINDAT': pd.Series([], dtype=np.dtype('<M8[ns]')),
             'PERCENTCON': pd.Series([], dtype=np.dtype('int64')),
             'REPORTDATE': pd.Series([], dtype=np.dtype('<M8[ns]')),
             'DATECRNT': pd.Series([], dtype=np.dtype('<M8[ns]')),
             'IRWINID': pd.Series([], dtype=np.dtype('O'))}
points = gpd.GeoDataFrame(blankdata,
            crs='EPSG:4326', geometry=gpd.GeoSeries())
conus = box(-126, 24, -66, 50)
points = points[points.intersects(conus)]
```
Before the indexing, `points` is:
```
Empty GeoDataFrame
Columns: [ACRES, CONTAINDAT, DATECRNT, FIRENAME, IRWINID, PERCENTCON, REPORTDATE, STATE, geometry]
Index: []
```

The indexing array (result of the intersection) is:
```
Series([], dtype: float64)
```

After the indexing, points is:
```
Empty DataFrame
Columns: []
Index: []
```

So, the rest of the code is expecting an object with a bunch of columns that I guaranteed earlier in my code, and this intersection dropped them all unexpectedly. I eventually hit an AttributeError for a missing column name.

Tested with geopandas v0.3.0.

**Comment by jorisvandenbossche** [comment]
Thanks for the report!

This seems to be an issue with pandas as well:

```
In [36]: df = pd.DataFrame({'a': pd.Series([], dtype=int), 'b': pd.Series([], dtype=float)})

In [37]: df
Out[37]: 
Empty DataFrame
Columns: [a, b]
Index: []

In [38]: df[pd.Series()]
Out[38]: 
Empty DataFrame
Columns: []
Index: []
```

But, if you do eg a comparison operation in pandas on an empty, then it does work correctly:

```
In [39]: df[df['a'] > 10]
Out[39]: 
Empty DataFrame
Columns: [a, b]
Index: []
```

this is because pandas ensures it is still a boolean series although empty:

```
In [40]: df['a'] > 10
Out[40]: Series([], Name: a, dtype: bool)
```

So it seems the bug is in `GeoSeries.intersects` not being of type boolean when empty.

The fix will be to explicitly put the dtype on the series return value here:

https://github.com/geopandas/geopandas/blob/891c5cd73c604862fbefd014cc6536faf571d260/geopandas/base.py#L53-L54

(although we might need to make a separate version for this for the predicate methods that return boolean values)

PR always welcome.

**Comment by WeatherGod** [comment]
I'll see what I can do today. Should we also file a bug report to pandas as
well?

**Comment by jorisvandenbossche** [comment]
> Should we also file a bug report to pandas as well?

I think not (but not fully sure). The empty series (because it is not boolean), is regarded as a selection on the columns. See eg example this case where the dataframe is emtpy but the series not:

```
In [41]: df = pd.DataFrame({'a': pd.Series([], dtype=int), 'b': pd.Series([], dtype=float)})

In [42]: df
Out[42]: 
Empty DataFrame
Columns: [a, b]
Index: []

In [43]: df[pd.Series(['a'])]
Out[43]: 
Empty DataFrame
Columns: [a]
Index: []
```

It selected on the columns. In case of an empty series, it is of course a bit ambiguous, as it could both be a selection on the rows as columns. But probably pandas looks at the dtype of the series then.

**Comment by WeatherGod** [comment]
Looking at the code for `_series_op` I am guessing that the more pedantic solution is actually to set the dtype to the dtype of the null_value?

**Comment by jorisvandenbossche** [comment]
Or in addition to `null_val = False if op != 'distance' else np.nan` add a `dtype = bool if op != 'distance' else float`.

**Comment by WeatherGod** [comment]
I like my approach if only because it is then consistent with the change that would need to happen in `_series_unary_op()` as well, because it can take floats, bools or strings (which I think needs to be treated as objects, right?)

**Comment by jorisvandenbossche** [comment]
Ah, yes there the case exists as well. Doesn't really matter to me how exactly it is done. The 'None' case (for strings) would indeed be object.

**Comment by WeatherGod** [comment]
And it looks like the place for tests seems to be test_geom_methods.py. I think I will update it so that it will have a combination of (empty, something), (something, empty), and (empty, empty) operations.

**Comment by WeatherGod** [comment]
anybody against me reworking that test file a bit to take advantage of pytest.parametrize? I won't go overboard, but this is a good place to use it to run tests on different combinations of data.

**Comment by WeatherGod** [comment]
Hmm, reworking the test file is turning into quite a bear. I'll leave it off as a separate PR for later, and just add explicit tests for this.
