### ISSUE TITLE
Passing in list of facecolors to gdf.plot() seems to have a bug

### ISSUE THREAD

**Issue by bjlobo** [geopandas/geopandas#730]
Passing in a list of facecolors to the gdf.plot() function appears to be broken - all features (some are polygons and some are multi-polygons) should be colored red except for one which should be orange.  However, the figure below generated using the code below shows two distinct polygons (not a multi-polygon) colored orange.

    import geopandas as gpd
    import matplotlib.pyplot as plt

    zctas_gdf = gpd.read_file('zcta/zcta.shp')

    fig, ax = plt.subplots(figsize=(12, 7))
    ax.set_aspect('equal')
    ax.axis('off')

    facecolor = ['red'] * len(zctas_gdf)
    facecolor[2] = 'orange'
    zctas_gdf.plot(ax=ax, alpha=0.85, facecolor=facecolor, edgecolor='black')

    plt.grid(False)
    plt.tight_layout()
    plt.show()
    plt.close()

[zcta.zip](https://github.com/geopandas/geopandas/files/2028062/zcta.zip)
![figure_1](https://user-images.githubusercontent.com/4724032/40382034-57141e2c-5dcb-11e8-9fea-b8b26256df2e.png)

**Comment by jorisvandenbossche** [comment]
@bjlobo Thanks for the report.

This is actually not really supported, and working in certain cases 'by accident'. Currently the code simply passes the `facecolor` argument to the matplotlib collection constructor. That seems to work as long you have single geometries. But for MultiPolygons, we "flatten" the array of (Multi)Geometries to only single geometries. In that case, we should also insert duplicate values in the `facecolor` list of colors, as is done for values here:

https://github.com/geopandas/geopandas/blob/6e0fd9b18e5e992434143e79db72c20104e9f3ef/geopandas/plotting.py#L83

And it seems that matplotlib, if the `facecolors` list is too short, it just repeats the list, which is why a random other one gets colored orange.

**Comment by jorisvandenbossche** [comment]
BTW, I think a PR would certainly be welcome to try to fix this. We just need to think a bit about how to best handle the different cases (single string, array version of a color, 1D array of strings, 2D array of numeric rgb values, ..)

**Comment by Casyfill** [comment]
Sounds relatively easy.. will work on this, if no objection!

**Comment by bjlobo** [comment]
No objection from me if that is what you are asking, since I am not sure
what the solution is.
