### ISSUE TITLE
[clip vs. intersect] polygons lost due to dropping duplicates generated by .overlay()

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#790]
I was testing the `.overlay() ` function and got some interesting issues.
I imported two geojson files as the following:
The first one has a shape of (2167, 17), with a OBJECTID column:
![plot1](https://user-images.githubusercontent.com/33796896/43417575-5b13f17c-9409-11e8-9615-4998a75bf734.png)
The second one has a shape of (5, 5):
![plot2](https://user-images.githubusercontent.com/33796896/43417574-5b033b84-9409-11e8-8a81-3c89ca35b4cf.png)
I ran `.overlay(how='intersection')`, and got the following map with a shape of (3195, 21)
![plot3](https://user-images.githubusercontent.com/33796896/43417576-5b225bfe-9409-11e8-8fdb-b7b8da6be7cd.png)
The above map looks right, but there are many duplicated rows in the geodataframe. I used the method posted by folks [here](https://github.com/geopandas/geopandas/issues/521), and transferred the geometry column to wkb. I then ran `.nunique()` and saw there are 2165 unique values in OBJECTID, but there are 3195 unique values in the geometry column. I'm confused that why the number is not 2165 and exceeds both geodataframes I imported. Then I dropped those duplicated values based on the OBJECTID column with `.drop_duplicates(subset='OBJECTID', inplace=True)`. I plotted the geodataframe again and got the following map. I realized that some of the polygons have lost. (Btw, I used both geojson files in QGIS before and got an identical map like the one above by `.overlay(how='intersection')`, and the clipped layer got  2165 rows in the attribute table, so it seems that 2165 is the right number to expect)
![plot4](https://user-images.githubusercontent.com/33796896/43422452-b58c344e-9417-11e8-846c-df460c8df368.png)
I checked GeoPanads's API and didn't see any way to prevent those duplicated rows from generating. I don't know why there are 3195 rows in the geodataframe, and why those polygons are lost by dropping duplicates.

**Comment by stevencollinscn** [comment]
@ozak 
I was using `0.3.0` and just upgraded to `0.4.0`, but the problem still exists.  I checked my input layer, and there is no duplicate in the `objectid` column. This time I got a layer with 2255 rows. I checked the clipped layer and there is 90 duplicates in the `objectid` column. The layer that I got with QGIS has a 2165 rows, which exactly equals to 2255 - 90. 

Please find all the files [here](https://github.com/stevencollinscn/Python_test).

**Comment by ozak** [comment]
It seems the issue are certain tracts that are close to the borders. If you plot the duplicated ``objectid`` you get

![image](https://user-images.githubusercontent.com/650534/44071301-f3071f50-9f4d-11e8-8e1c-24112bf8a8a1.png)

and looking at the list of duplicates I see that many are in two boroughs.

```python

dups = clipped.loc[clipped.objectid.duplicated()].objectid

dups
Out[43]: 
22        16.0
26        18.0
31        20.0
48        33.0
442      396.0
448      400.0
465      414.0
482      435.0
485      436.0
505      464.0
512      474.0
520      484.0
524      486.0
980     1146.0
1205    1738.0
1232    1762.0
1253    1777.0
1294    1804.0
1312    1815.0
1388    1942.0
1753    2163.0
1756    2164.0
1764    2168.0
1779    2177.0
1896    2244.0
1954    2280.0
1981    2295.0
2236    2458.0
2611    3095.0
2643    3136.0
 
946     1010.0
950     1012.0
952     1013.0
956     1015.0
958     1016.0
962     1018.0
972     1141.0
1041    1470.0
1044    1472.0
1207    1744.0
1330    1854.0
2190    2420.0
2196    2422.0
2263    2487.0
2350    2555.0
2356    2563.0
2450    2630.0
2457    2634.0
2776    3331.0
2808    3498.0
2823    3511.0
2879    3947.0
2883    3949.0
2885    3950.0
2943    3987.0
2946    3988.0
3041    4096.0
3063    4108.0
3082    4126.0
3356    4670.0
Name: objectid, Length: 90, dtype: float64

clipped.loc[clipped.objectid.apply(lambda x: x in dups.values)][['boro_code', 'objectid']]
Out[50]: 
      boro_code  objectid
22          3.0      16.0
23          4.0      16.0
26          3.0      18.0
27          4.0      18.0
31          3.0      20.0
32          4.0      20.0
49          4.0      33.0
48          3.0      33.0
116         2.0      85.0
117         4.0      85.0
243         2.0     215.0
244         4.0     215.0
355         4.0     321.0
354         2.0     321.0
442         3.0     396.0
443         4.0     396.0
449         4.0     400.0
448         3.0     400.0
466         4.0     414.0
465         3.0     414.0
482         3.0     435.0
483         4.0     435.0
485         3.0     436.0
486         4.0     436.0
506         4.0     464.0
505         3.0     464.0
512         3.0     474.0
513         4.0     474.0
520         3.0     484.0
521         4.0     484.0
        ...       ...
2714        3.0    3198.0
2777        4.0    3331.0
2776        1.0    3331.0
2809        2.0    3498.0
2808        1.0    3498.0
2823        1.0    3511.0
2824        2.0    3511.0
2880        3.0    3947.0
2879        1.0    3947.0
2883        1.0    3949.0
2884        3.0    3949.0
2885        1.0    3950.0
2886        3.0    3950.0
2945        4.0    3987.0
2944        3.0    3987.0
2943        1.0    3987.0
2947        3.0    3988.0
2946        1.0    3988.0
3041        1.0    4096.0
3043        4.0    4096.0
3064        2.0    4108.0
3063        1.0    4108.0
3082        1.0    4126.0
3083        2.0    4126.0
3184        2.0    4387.0
3185        4.0    4387.0
3356        1.0    4670.0
3357        3.0    4670.0
3393        4.0    4904.0
3392        3.0    4904.0

[178 rows x 2 columns]
```

It does not seem to be the intersection that is the issue. Not sure why QGIS is generating different results. Did you reproject at any point? I see that ``nyc`` has a different ``crs``. 

Do you have the original data as a shapefile? I wonder if this is related to geojson. I've seen a couple of open issues related to them (e.g. #677), but I am not sure what the issue is exactly.  In #677 it seemed it was due to not valid geometries, but yours seem to be ok.

**Comment by ozak** [comment]
Something seems  to be wrong with these files or with the geojson API. If I try to export to shapefile it just hangs and does not write anything.

**Comment by stevencollinscn** [comment]
@ozak Those were shapefiles indeed and I exported them as geojson files. In terms of the projection, I think it is another issue in geopandas. Those three layers actually share the same crs but look differently for some reasons. I tried to change the crs of those two input layers and plot them again, but nothing happened. I will try to find the original files tomorrow and get back to you. Thanks.

**Comment by ozak** [comment]
Ok...Did you export them to geojason in geopandas?

**Comment by stevencollinscn** [comment]
@ozak no, I export them to geojason in QGIS

**Comment by stevencollinscn** [comment]
@ozak I looked at everywhere but couldn't found where I downloaded the original shapefile for that NYC tracts layer with water area. Thus, I searched again and download two shapefiles, [NY State Census Tracts](https://www.census.gov/geo/maps-data/data/cbf/cbf_tracts.html) and NYC [Boundaries](https://data.cityofnewyork.us/City-Government/Borough-Boundaries/tqmj-j8zm/data).  
I tried it again and the problem is the same. Geopandas still generated duplicates. I also imported both layers into QGIS. I set their crs to `epsg: 4269`, and then did a clip, and got a layer with 2194 rows. Then I did the same thing in Geopandas, and got a layer with 2281 rows. I checked the `GEOID `column in the layer and got 87 duplicates. Well... 2281 - 87 = 2194.
Please find the `shapefiles.zip` [here ](https://github.com/stevencollinscn/Python_test), which includes everything.

**Comment by jorisvandenbossche** [comment]
@stevencollinscn thanks for the feedback and the reproducible example!

I think the different result comes from a difference in expectations. The `overlay` with 'intersection' is not the same as a "clip" operation (I think), so you should not expect it to give necessarily the same result.

As far as I understand "clip", it basically cuts the left dataframe based on the "area of interest" of the right dataframe, no matter how the right dataframe is divided into multiple geometries. 
On the other hand, "overlay" (or at least how it is implemented in geopandas) combines the actual geometries of both left and right dataframe by taking the intersections (in this case).

To be more practical, for the geometries in `state` (left) dataframe that overlap with a border of the boroughs (right) dataframe: `overlay` will actually cut them in two by taking the intersection with each of the overlapping boroughs, while "clip" simply limits each of those geometries to the area that overlaps with all boroughs combined. 

That explains why the "duplicate" values in the result are near the borders. 
But also note that those are not really duplicate. It's only the object id that is duplicated, because each of the two "duplicated" values comes from a single geometry in `state`.

Currently, geopandas does not provide such a "clip" behaviour out of the box. 
One way would be to combine the geometries with the same object id after doing the overlay, which you can do with `dissolve`:

```
>>> clipped = geopandas.overlay(state, br, how='intersection')
>>> len(clipped)
2281
>>> clipped2 = clipped.dissolve('GEOID')
>>> len(clipped2)
2194
```

which gives the desired 2194 number of features.

Or alternatively (potentially conceptually simpler / closer to "clip"), is to simply take the intersection with the union of the right dataframe and drop the empty geometries:

```
>>> clipped3 = state.copy()
>>> clipped3['geometry'] = clipped3.intersection(br.unary_union)
>>> clipped3 = clipped3[~clipped3.is_empty]
>>> len(clipped3)
2194
```

however this is (in this case) slower as the overlay + dissolve.

**Comment by stevencollinscn** [comment]
@jorisvandenbossche It seems that with `.dissolve()`, `GEOID` becomes an index instead of a column. Is there anywhere to keep it as a column and avoid generating a multilevel index? I could run something like that: 
```
df['geoid'] = df.index
df.columns.names = ['']
df = df.reset_index(drop=True)
```
but it doesn't seem very pandorable.

**Comment by ozak** [comment]
Looking at the video it seems clip is just intersect, but dropping the columns of the geometry you intersected with, no? Which is different than what @jorisvandenbossche suggests. Guess it depends on the exact use you need.

Now, one has to be careful, there are really no duplicates in the intersection, since now ``['boro_code', 'objectid']`` jointly should be considered the underlying  identifier. Each geometry in the intersection represents this joint ID and thus has no duplicates. Although as I showed above there are duplicates in ``objectid`` since after the intersection different parts of the original geometry are in different boroughs.

**Comment by stevencollinscn** [comment]
@ozak I think you're right. There is no duplicate in terms of geometry indeed, but there are duplicates in terms of geoid/objectid. We are just looking at the different things. Indeed, 'boro_code' and 'objectid' together should be the identifier in the new layer after the intersection, but for me, the indentifier I want is objectid/geoid and use it to indentify different census tracts. The solution from @jorisvandenbossche actually works for me and makes it easier for me to merge dataframe that also use GEOID as an identifier. 

Btw, I mentioned the projection issue last night, but it seems like an issue geopandas has with reading geojosn files. Not matter what the crs in the geojosn file, it will always read it as epsg: 4326. It is a known [issue](https://gis.stackexchange.com/questions/159681/geopandas-cant-save-geojson).

**Comment by austinorr** [comment]
@stevencollinscn I followed the links at that issue and it appears that the GeoJSON spec removed support for arbitrary crs information in 2016, and now only supports EPSG 4326. The spec change is [here](https://tools.ietf.org/html/rfc7946#section-4) and the article from your linked issue with a thorough discussion is [here](https://macwright.org/2015/03/23/geojson-second-bite.html).

This makes the current implementation of loading all GeoJSON files with 4326 appropriate and should likely not be 'fixed' in `geopandas` when reading data. If you know you have a special case, it's possible to set the crs on any loaded GeoDataFrame using the `my_geoseries.crs = {'init' :'epsg:whatever'}` after it's been loaded.

Protecting users from writing non-compliant GeoJSON could be worth discussing, but it might have to be done upstream in `fiona`'s GeoJSON driver (if it's not already).

**Comment by stevencollinscn** [comment]
@austinorr Thanks for letting me know. Based on my experience, the most .`shp` I used have a `crs 4269`. It seems that we have to set it to 4326 everytime if we want to save the file as a GeoJSON file.

**Comment by austinorr** [comment]
@stevencollinscn don't forget to use the `gdf.to_crs()` method if you're going from one crs to another. If the data you're using is already in 4269, then you need to _convert_ the crs of the frame to `epsg 4326` rather than _assign_ `epsg 4326` to the frames' `.crs` asttribute.

**Comment by stevencollinscn** [comment]
@austinorr thank you for mentioning that man. I was assuming that both are the same.

**Comment by stevencollinscn** [comment]
@austinorr Since you mentioned, when I was doing a spatial join, I usually just do the following before the join. Is it legitimate?
`gdf_points.crs = gdf_polygons.crs`

**Comment by austinorr** [comment]
@stevencollinscn yes _if and only if_ the points dataframe currently has no crs, but the coordinates in it's `geometry` series already happen to be in the same units _and_ projection as the polygons frame. The only other valid case would be if the points frame already has a crs and it's identical to the polygons crs (rendering this statement redundant). 

In the more likely and relevant case in which you're loading points from one data preparer (lets say the points are in wgs nad83) and the polygons from another preparer (let's say state plane US Feet, in some state and in some zone) then the syntax you're looking for (if you e.g., want which polygon the point falls into) is:

```
gdf_polygons = geopandas.read_file("path/to/your/stateplane/polygon/shapefile.shp")
gdf_points = (
    geopandas.read_file("path/to/your/wgsnad1983/points/shapefile.shp")
    .to_crs(gdf_polygons.crs)
)
assert gdf_points.crs == gdf_polygons.crs # this must not raise if you're doing a spatial join

new_points_gdf = geopandas.sjoin(gdf_points , gdf_polygons, how="inner", op='intersects')
```

There are pretty good docs for managing the projections of a gdf [here](http://geopandas.org/projections.html) and managing spatial joins [here](http://geopandas.org/mergingdata.html#spatial-joins). But one thing they don't mention is that managing projections and re-projections is not done inside the `sjoin` or `overlay` method, and that setting the `.crs` attribute of a gdf does not do any actual math on the coordinates stored in its `geometry`. Basically all re-projections are the programmers job _prior_ to the call to a function/method which spatially joins or overlays datasets. and careful attention must be paid to the crs/projection information of the datasets when they're different. Overlapping feature coordinates in x y feet with another set of feature coordinates given in decimal degrees as lat long makes no sense, but overlay will allow it (as of 0.3.0. I'm not sure if the upgraded overlay is crs-aware in 0.4.0, but i doubt it). Best case it'll produce an empty set and you'll catch the problem quickly, but in some cases (like in relative coordinate systems such as state plane) you'll get a lot of features in your output and believe your analysis is complete even though none of the features make any sense.

It might be time to close this issue and continue the discussion on the gis stack exchange or on stack overflow with a `geopandas` tag. if you want to continue talking about this, i'd be glad to move this over to a [gist ](https://gist.github.com/austinorr/6fca2c1bd724b1c4885dcac368022ae9) i wrote a while ago about crs-aware overlay operations so that we can close this issue but continue the discussion.

**Comment by austinorr** [comment]
@stevencollinscn I agree with everything you just said; 1) don't confuse crs assignment with crs conversion, and 2) crs matters during spatial intersections, so way to go `geopandas` for the helpful `userwarning` so we don't shoot our feet.

**Comment by stevencollinscn** [comment]
@austinorr Thanks, btw I think this case should be closed by now.

**Comment by StevenLi-DS** [comment]
@austinorr I believe you brought this issue to me before. What do you think of https://github.com/geopandas/geopandas/issues/1027 ?
