### ISSUE TITLE
ReProjecting XYZ coordinate gets wrong Z coordinate

### ISSUE THREAD

**Issue by Davidswinkels** [geopandas/geopandas#794]
Heyo GeoPandas,

Thanks for Geopandas. Was doing a reprojection from a projected coordinate system (e.g. EPSG:28992) to a geographic coordinate system (e.g. EPSG:4326) and the Z coordinate gets a weird offset of 45 meters. The Z coordinates of both coordinate systems are in meters and have 0 set at mean sea level. So when reprojecting XYZ points with a height of 0 meters, you expect them to have a height of 0 meters after reprojection. This is not the case in Geopandas (which uses PyProj), PyProj and GDAL. 

Can you help to solves this issue? Thanks in advance!

```
import geopandas as gpd
from shapely.geometry import Point

geometry = [Point(192080.218800001, 326727.25, 0.0)]
crs = {'init': 'epsg:28992'}
pointRDnew = gpd.GeoDataFrame(index=[0], crs=crs, geometry=geometry)
pointWGS84 = pointRDnew.to_crs(epsg="4326")
print(pointWGS84.geometry[0])
```
`POINT Z (5.914611042609124 50.92907898070797 45.24482111539692)`

```
from pyproj import Proj, transform

x1, y1, z1 = 192080.218800001, 326727.25, 0.0
inProj = Proj(init='epsg:28992')
outProj = Proj(init='epsg:4326')
x2, y2, z2 = transform(inProj, outProj, x1, y1, z1)
print(x2, y2, z2)
```

`5.914611042609124 50.92907898070797 45.24482111539692`

```
from osgeo import ogr, osr

wktGeometry = 'POINT (192080.218800001 326727.25 0.0)'
epsgTransformation = epsgToWGS84Transformation(28992)
geometryFromWkt = ogr.CreateGeometryFromWkt(wktGeometry)
geometryFromWkt.Transform(epsgTransformation)
print(geometryFromWkt)
```

`POINT (5.91461112637604 50.9290789739909 45.2474540863186)`

**Comment by kjordahl** [comment]
@Davidswinkels this is expected behavior for reprojecting 3D points in different coordinate systems. In particular, [EPSG:28992](http://spatialreference.org/ref/epsg/amersfoort-rd-new/) uses a different ellipsoid than EPSG:4326, so the vertical reference is different. (I haven't verified that the specific offset is correct for this projection, but the fact that you're seeing the same behavior in `pyproj` and GDAL/OGR is consistent with this being an expected result).

If your z-values are really relative to the WGS84 ellipsoid (or some local datum like mean sea level) and not Bessel 1841, then I would suggest that you project x, y values separate from the z values.
