### ISSUE TITLE
Boto3 Missing requirements for tests

### ISSUE THREAD

**Issue by mazzma12** [geopandas/geopandas#823]
It looks like the dependency is required by `fiona`. See the failed build here : https://travis-ci.org/geopandas/geopandas/jobs/428929519

**Comment by jorisvandenbossche** [comment]
This is a known bug in fiona: https://github.com/Toblerity/Fiona/issues/507 which now surfaces because installing fiona with conda-forge seemed to have started to install the alpha release. So as a temporary workaround, we could also install `boto3` as a test requirement (or otherwise keep fiona at the released version)

**Comment by mazzma12** [comment]
Thanks for the highlight, I had no clue what I did wrong. I will temporarly fix Fiona version then.

**Comment by ocefpaf** [comment]
@jorisvandenbossche and @mazzma12 note that the dev version of `fiona` in conda-forge (`fiona 1.8a2-py36hb00a9d7_0`) leaked to the main channel due to https://github.com/conda-forge/conda-smithy/issues/886 and that is what triggered the issue here. I moved it manually to the `dev` label and if one wants to use that package for testing the right way to get is with:

```
conda install conda-forge/label/dev::fiona
```

**Comment by jorisvandenbossche** [comment]
@ocefpaf Yes, I was actually planning to ask about it in the fiona feedstock if this was on purpose, so apparently not! :)

**Comment by jorisvandenbossche** [comment]
OK, so then we can close this. I think it would still be a good idea to add one travis build with fiona dev, but that is a separate issue

**Comment by ocefpaf** [comment]
It took me a while to fix it, sorry. (I was away for most of the weekend.)
BTW, I'll move `boto3` to a required dep in the dev package for now, so you can use it for tests here.

**Comment by jorisvandenbossche** [comment]
No worries, thanks a lot for building it!

**Comment by mazzma12** [comment]
My travis build still fails even after adding `boto3` to test requirements :  https://travis-ci.org/geopandas/geopandas/jobs/429453107#L1230.

It only occurs on some version with miniconda, I wonder if it does not cache the install... do you have a clue ?

**Comment by ocefpaf** [comment]
@mazzma12 that is transient as I transfer the new packages to the dev channel. It should be OK again, can you retry and let me know?

**Comment by mazzma12** [comment]
Thank you it passed now. I have other issues but this is mainly due to how I write test with Postgis
