### ISSUE TITLE
.merge() keep returning pandas dataframe due to duplicate geometry columns

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#824]
`geopandas: '0.4.0'`

I imported one `shapefile `and one dbf file and tried to merge them together. I have tried to read the `.dbf` file as either a `geodataframe `or `dataframe`, but no matter what geopandas keep returning a pandas `dataframe `instead of a `geodataframe`. Am I missing something? 

My files and code could be found [here](https://github.com/stevencollinscn/Python_test/blob/master/geopandas_merge.zip)

```
# setting up python environment
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
plt.style.use('seaborn')
pd.set_option('display.max_colwidth', 50)
pd.set_option('display.max_columns', 50)
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# loading shapefile
gdf = gpd.read_file('.\geo1_pe2007\geo1_pe2007.shp')
# formatting columns
gdf.columns = [col.lower() for col in gdf.columns]
# review geodataframe
gdf.head()

# loading dbf file
gdf1 = gpd.read_file('Peru_Demog_Health_Infra_ID.dbf')
# formatting columns
gdf1.columns = [col.lower() for col in gdf1.columns]
# reveiw geodataframe
gdf1.head()

# merging dbf as a GeoDataFrame
gdf.rename(columns={'dept2007': 'id'}, inplace=True)
gdf1.id = gdf1.id.astype(str)
gdf_merged = gdf.merge(gdf1, on='id')
# returns a pandas DataFrame
type(gdf_merged)

# merging dbf as a DataFrame
df = pd.DataFrame(gdf1)
gdf_merged = gdf.merge(df, on='id')
# still returns a pandas DataFrame
type(gdf_merged)

# must convert it back to GeoDataFrame
gdf_merged = gpd.GeoDataFrame(gdf_merged, geometry='geometry_x')
type(gdf_merged)
```

**Comment by jorisvandenbossche** [comment]
@stevencollinscn Thanks for the report. What version of pandas and geopandas are you using?

**Comment by stevencollinscn** [comment]
@jorisvandenbossche `geopandas: '0.4.0'

**Comment by jorisvandenbossche** [comment]
@stevencollinscn I checked your reproducible example, and apparently, it is due to the fact that there is a 'geometry' column in the second dataframe. 
If I drop that first, the result is correctly a GeoDataFrame:

```
In [22]: gdf1 = gdf1.drop(columns='geometry')

In [23]: gdf_merged = gdf.merge(gdf1, on='id')

In [24]: type(gdf_merged)
Out[24]: geopandas.geodataframe.GeoDataFrame
```

The underlying reason for this is that we check that the resulting frame still has the "geometry" column (or the name that is registered as the geometry column in `gdf._geometry_column_name`), and because `merge` mangles the names if they are present in both the left and right dataframe.

**Comment by stevencollinscn** [comment]
@jorisvandenbossche Thank you and I should've realized that since it returns `'geometry_x'`. I opened the `dbf` file in QGIS and didn't find a `'geometry' `column, so it seems like geopandas generated a `'geometry'` column itself. This makes sense since `'dbf'` could contain geo-info. I think geopandas perhaps offers the easiest way to read a `dbf` file and then convert it to a pandas dataframe. Thus, I wonder if geopandas could add an arugement like `dataframe=True` or something to read a `dbf` or other types of files like `.shp` as a pandas dataframe. 

Meanwhile, after dropping` 'geometry'` columns, it is still a geodataframe. I wonder if geopandas should convert it to a dataframe automacially instead.
