### ISSUE TITLE
Spatial join loses index names of input

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#846]
Small example:

```
In [15]: countries = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))

In [16]: cities = geopandas.read_file(geopandas.datasets.get_path('naturalearth_cities'))

In [17]: countries = countries.rename(columns={'name': 'country_name'}).set_index('country_name')

In [21]: cities.index.name = 'id'

In [22]: geopandas.sjoin(cities, countries, op='within').head()
Out[22]: 
             name                                     geometry index_right     pop_est continent iso_a3  gdp_md_est
0    Vatican City  POINT (12.45338654497177 41.90328217996012)       Italy  58126212.0    Europe    ITA   1823000.0
1      San Marino    POINT (12.44177015780014 43.936095834768)       Italy  58126212.0    Europe    ITA   1823000.0
192          Rome    POINT (12.481312562874 41.89790148509894)       Italy  58126212.0    Europe    ITA   1823000.0
2           Vaduz  POINT (9.516669472907267 47.13372377429357)     Austria   8210281.0    Europe    AUT    329500.0
184        Vienna  POINT (16.36469309674374 48.20196113681686)     Austria   8210281.0    Europe    AUT    329500.0
```

So both the index name of the left dataframe is lost, as the index name of the right dataframe (which has become the generic 'index_right' column)

**Comment by bnaul** [comment]
I'd be interested in fixing this as I find this behavior pretty counterintuitive. But at the same time I can imagine this "fix" being a pretty big breaking change (I know my own code has `index_right` hard-coded here and there). @jorisvandenbossche or anyone else, do you think the next release is "big" enough for this behavior to change or should it wait until a really major version?

**Comment by martinfleis** [comment]
@bnaul I vote for fixing this in the next release. After all, it is a bug. The longer it will take to fix it the more issues it might cause.

**Comment by donlo** [comment]
would like to pick up this issue to work on
shall the desired output be like below?

```ipython
In [22]: geopandas.sjoin(cities, countries, op='within').head()
Out[22]: 
             name                                     geometry country_name     pop_est continent iso_a3  gdp_md_est
id
0    Vatican City  POINT (12.45338654497177 41.90328217996012)       Italy  58126212.0    Europe    ITA   1823000.0
1      San Marino    POINT (12.44177015780014 43.936095834768)       Italy  58126212.0    Europe    ITA   1823000.0
192          Rome    POINT (12.481312562874 41.89790148509894)       Italy  58126212.0    Europe    ITA   1823000.0
2           Vaduz  POINT (9.516669472907267 47.13372377429357)     Austria   8210281.0    Europe    AUT    329500.0
184        Vienna  POINT (16.36469309674374 48.20196113681686)     Austria   8210281.0    Europe    AUT    329500.0
```

**Comment by brendan-ward** [comment]
It seems like part of this could be done without resulting in a breaking change.

Nonbreaking change:
In the case of `how="left"` and `how="inner"` the index of the left data frame is used as the index for the result.  In this case, instead of setting it as `None` it could be set to the original name of the left index.  Hopefully nobody is relying on the returned index having no name, so setting the name to the original shouldn't cause any issues.

Likewise, for `how="right"` the same could be done with the right index name.

It seems like this fix could / should be done at any time.


Potentially breaking change:
The name of the index on the opposite end of the join (e.g., the right index in the case of `how="left"` and `how="inner"`) may well be a breaking change, since folks are already specifically handling the column with the name as returned here (as stated above).  So either this should wait for a new release or left as is.

**Comment by srenoes** [comment]
In #498 there is some similar discussion about whether to keep the indeces or not. And it is talked about consistancy with pandas.
I guess that geopandas.sjoin is something like short for "gdf.join(gdf2, on='geometry operation')". What does pandas really do in such cases? It looks like it always transhes the right index, no matter what even for right joins with keyword on=xxx as it seems, which is quite disturbing actually as you get Nans there:

``` python:
>>> df1=pd.DataFrame([[1,3,6],[3,4,1]],columns=['d1','b1','d1'],index=pd.Index([2,1],name='s'))
>>> df2=pd.DataFrame([[0,3,2],[1,5,2]],columns=['d2','b2','d2'],index=pd.Index([3,4],name='t'))
>>> df3=df1.join(df2,how='outer')
>>> print(df3)
    d1   b1   d1   d2   b2   d2
1  3.0  4.0  1.0  NaN  NaN  NaN
2  1.0  3.0  6.0  NaN  NaN  NaN
3  NaN  NaN  NaN  0.0  3.0  2.0
4  NaN  NaN  NaN  1.0  5.0  2.0

>>> df3=df1.join(df2.set_index('b2'),on='b1',how='outer')
>>> print(df3)
      d1  b1   d1   d2   d2
2.0  1.0   3  6.0  0.0  2.0
1.0  3.0   4  1.0  NaN  NaN
NaN  NaN   5  NaN  1.0  2.0

>>> df3=df1.join(df2.set_index('b2'),on='b1',how='left')
>>> print(df3)
   d1  b1  d1   d2   d2
s
2   1   3   6  0.0  2.0
1   3   4   1  NaN  NaN

>>> df3=df1.join(df2.set_index('b2'),on='b1',how='right')
>>> print(df3)
      d1  b1   d1  d2  d2
2.0  1.0   3  6.0   0   2
NaN  NaN   5  NaN   1   2

```
 

My question is now if there would be a possible workaround by assigning property ***setters or getters for properties index_right/index_left***, such that one could still use old codes without immideatly getting into trouble? 
Pandas also offers to name variables as non column variables for subclassing (***Define original properties*** in https://pandas.pydata.org/docs/development/extending.html). But I dont know if you need it

so what about property methods combined with some ***subclassing of [ ] or __getitem__/__setitem__ and calling pandas __getitem__/__setitem__after that*** ? Not sure though what happens with loc[ ] then. A real mess!

Even in pandas it does not always trash the name of the index, only when the right index is involved it vanishes. And .. in pandas there is never any column that refers to old left or right indexes... as far as I can see from above tests. They are just dropped

Man that is a complicated problem.

Now, as is, the name of the ***to be index is kept*** and just the ***other index name is not transferred into column name*** and pretty sure people use other.index_right/left . And changing it will break their code

Is this at all viable? Since again property decorators are also used for extending constructors somehow (again https://pandas.pydata.org/docs/development/extending.html , ***Override constructor properties*** ). I don't know.

But maybe you guys can get some idea about how to solve this issue???

**Comment by jorisvandenbossche** [comment]
I currently have a PR that changes the behaviour to now preserve the name of the index of the right dataframe -> https://github.com/geopandas/geopandas/pull/2144

It _is_ indeed a change that can breaking code that uses this "index_right" name. But I am not sure if there is any way around breaking this, if we want to fix this.

**Comment by jorisvandenbossche** [comment]
> I'd be interested in fixing this as I find this behavior pretty counterintuitive. But at the same time I can imagine this "fix" being a pretty big breaking change (I know my own code has `index_right` hard-coded here and there).

@bnaul  I know I am referencing an old comment here, but do you remember the typical context of why you have "index_right" hard-coded? Is it to get rid of it (eg drop it), or to actually use it?

**Comment by bnaul** [comment]
Some of each...for us it'd be straightforward to just grep for index_right and update if needed, but hard to say how disruptive it might be for others

**Comment by jorisvandenbossche** [comment]
Thanks for the quick response! (but yeah, always difficult to estimate such impact in general ...)

Another idea that I mentioned at https://github.com/geopandas/geopandas/pull/2144#issuecomment-1038220712 is that we could also preserve the index of the right DataFrame _only_ if it has a name. Part of the additional complexity in the current `sjoin` implementation comes from the way we now generate some name for the index (and with that PR sometimes generate a name if it has none, and otherwise preserve the name). But so this alternative option would mean that we never try to generate such a name. It would then basically be a check to see if the index has a name, and in that case do a `reset_index`, and that's it.  
Such a `reset_index` is of course also easy to do by the user up front if they want to keep the index, but this alternative might preserve a bit more the current behaviour in cases when it is useful. 

Now, whathever we choose (always keep the index, never keep it, or only keep it if it has a name (so we don't have to invent a name)), this will always be a backwards incompatible change if you had a meaningful index with a name, because in any of those options there would no longer be a column named "index_right".
