### ISSUE TITLE
git link broken on geopandas docs

### ISSUE THREAD

**Issue by ebauch** [geopandas/geopandas#852]
![image](https://user-images.githubusercontent.com/3758223/47595782-ffad6e80-d94f-11e8-8a99-aaff43a170b3.png)

gitlink appears broken on docs pages

![image](https://user-images.githubusercontent.com/3758223/47595794-148a0200-d950-11e8-8848-70492669064f.png)

**Comment by jdmcbr** [comment]
@ebauch Thanks for the report. It looks like this is only occurring on the gallery page, due to the fact that the contents of the gallery are generated from the 'geopandas/examples' folder, so there isn't a `doc/gallery/index.rst` file under version control. I didn't come across any way to fix this directly for sphinx gallery generated files. @choldgraf Would you happen to have any ideas?

**Comment by choldgraf** [comment]
Hmmm that one is tough... Im also not sure how you could get around that, other than by committing your built rst files to the repo but you probably don't want to do that...

**Comment by jdmcbr** [comment]
Thanks @choldgraf. That certainly would be misleading, given the rst file is being generated. I've not been able to see any way with readthedocs to remove the edit link for a single page (and the "edit on github" link works for all the pages for which we do have rst files under version control), I don't see much of anything we can do here. Happy to re-open this if I'm mistaken though.
