### ISSUE TITLE
pipenv install geopandas error

### ISSUE THREAD

**Issue by devtycoon** [geopandas/geopandas#866]
# Pipenv install error

Collecting geopandas
  Using cached https://files.pythonhosted.org/packages/24/11/d77c157c16909bd77557d00798b05a5b6615ed60acb5900fbe6a65d35e93/geopandas-0.4.0-py2.py3-none-any.whl
Collecting fiona (from geopandas)
  Using cached https://files.pythonhosted.org/packages/25/50/0466d5d83e1859c5ca38351ee932d64cc5635f9d4dad522879e58f4b0018/Fiona-1.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

    ----------------------------------------

Error:  An error occurred while installing geopandas!
Command "python setup.py egg_info" failed with error code 1 in ~\AppData\Local\Temp\pip-install-sz0emls_\fiona\

This is likely caused by a bug in geopandas. Report this to its maintainers.

**Comment by jorisvandenbossche** [comment]
This is not a bug in geopandas, but an installation problem with one of its dependencies (Fiona). 

I assume you are using windows?

Fiona does not provide binary packages when installing through pip for Windows, so it is trying to build from source and not finding GDAL. 
I would recommend to use Anaconda to install geopandas on windows (or otherwise, with pip, you can download binaries for Fiona and Shapely at https://www.lfd.uci.edu/~gohlke/pythonlibs/)

**Comment by sarkyscouser** [comment]
Set up an anaconda environment that points to conda-forge (nothing else) and then install geopandas otherwise you will get lots of conflicts between conda-forge and the default conda channel when it comes to gdal etc

This works for me:
conda create -n new_env_name -c conda-forge python=3.5 geopandas

**Comment by devtycoon** [comment]
thanks!

also found this link that is telling me to do the same thing or download the wheels and do it manually.
[https://geoffboeing.com/2014/09/using-geopandas-windows/](https://geoffboeing.com/2014/09/using-geopandas-windows/)
