### ISSUE TITLE
Creating a new geopandas by equating to another gpd, causes the later to become dependant on the former

### ISSUE THREAD

**Issue by shadeqwerty** [geopandas/geopandas#950]
filename="../foobar.shp"                  #........ import any shapefile
db_file1 = geopandas.GeoDataFrame.from_file(filename)
db_file2=db_file1  #... Equating one geopandas to another, essentially creating a copy
db_file2.code=(db_file2.code*2) #.........Where "code" is a valid column header
print (db_file2,"\n",db_file1)

# the output shows that db_file1 has been modified, even though nothing like that has been done.

**Comment by jcusick13** [comment]
Python is different from some other languages in that setting `a=b` means both `a` and `b` refer to the same address in memory. This [SO post](https://stackoverflow.com/questions/16348815/python-assigning-multiple-variables-to-same-value-list-behavior) helps explain more detail about the issue.

For a quick workaround, try using `db_file2 = db_file1.copy()` in order to later modify `db_file2` without impacting `db_file1`.

**Comment by jorisvandenbossche** [comment]
That explanation is indeed fully correct, thanks @jcusick13 !
