### ISSUE TITLE
Problem with Translation after Projection

### ISSUE THREAD

**Issue by njanakiev** [geopandas/geopandas#959]
I run into the issue that the geometry is not properly projected after a translation. I wanted to create the geometry in mercator projection, project it to WGS84 and then move according to some lat lon point:

```python
import geopandas as gpd
from shapely.geometry import LineString

WGS84 = {'init': 'epsg:4326'}
MERC = {'init': 'epsg:3857'}

lon, lat = 4.899431, 52.379189

square = LineString([(-1, 1), (-1, -1), (1, -1), (1, 1), (-1, 1)])
s = gpd.GeoSeries([square], crs=MERC)
s = s.scale(1000, 1000).buffer(100)
s.to_crs(WGS84).translate(lon, lat).to_crs(MERC).plot();
```
![image](https://user-images.githubusercontent.com/9904103/55398843-d2da3480-5549-11e9-8acd-2284a65dd50c.png)

It works when I manually project the coordinates with the `pyproj` package:

```python
import pyproj

p = pyproj.Proj(MERC)
x, y = p(lon, lat)

s.translate(x, y).to_crs(WGS84).to_crs(MERC).plot();
```
![image](https://user-images.githubusercontent.com/9904103/55398882-e84f5e80-5549-11e9-8e58-f4b4ad95e6dc.png)

Did I miss something or is this an issue in the code? I assume it could affect also the other [Geometric Manipulations](http://geopandas.org/geometric_manipulations.html).

**Comment by jorisvandenbossche** [comment]
@njanakiev Thanks for opening the issue!

If I understand the issue correctly, I think this is due to how geographic coordinates (lat, lon) and projections work. 
In the first case, you have a square in Mercator (at 0, 0) and convert this to lon/lat (still at 0, 0). After translating this square to (4.90, 52.38), this is still a square in geographic coordinates, but because you are away from the equator, where a degree of latitude is no longer equal in length as a degree of longitude, the object is no longer an actual square in projected space. 
In the second case, however, you keep the square in Mercator (projected), and translate it in Mercator, which preserves the square shape (at least in Mercator coordinates).

**Comment by njanakiev** [comment]
Thanks for the clarification @jorisvandenbossche!

I understand, switching between projections got me confused. So the translation does not take the projection into account, which makes sense since it is just moving the geometry.
