### ISSUE TITLE
jenks plot legend issue

### ISSUE THREAD

**Issue by roehnan** [geopandas/geopandas#997]
I noticed that depending on the number of classes, Fisher-Jenks (or Natural Breaks) classification incorrectly represents the classifications when plotted. The first class is essentially set to itself:

![image](https://user-images.githubusercontent.com/22568428/57944199-0d462980-788b-11e9-82f2-ab4c7bb1fc4f.png)

I am not sure why the plot legend shows "0.38 - 0.38".

I've attached the shapefile that contains the data. The 'classif' column is calculated as "Reg_Total" / "POP2000". 

[totalreg.shp.zip](https://github.com/geopandas/geopandas/files/3192406/totalreg.shp.zip)

**Comment by jGaboardi** [comment]
The was determined not to be a `pysal` issue in pysal/pysal#1099.

**Comment by martinfleis** [comment]
Hi, it is not a bug, that just how your data looks like. Fisher Jenks binning will generate these bins:

                 Fisher_Jenks            
 
    Lower          Upper            Count
    =====================================
            x[i] <= 0.380               1
    0.380 < x[i] <= 0.474               6
    0.474 < x[i] <= 0.507               5
    0.507 < x[i] <= 0.552               7
    0.552 < x[i] <= 0.599               6
    0.599 < x[i] <= 0.649               5
    0.649 < x[i] <= 0.707               3
    0.707 < x[i] <= 0.798               1

Because the first bin has only one element, it is effectively the minimum and maximum value for that bin at the same time. That is why there is no range.

I think that this is desired outcome, but if you have a better idea how to handle these cases, we can think about it.

Thanks for the report anyway!
